// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M10

using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Debug UI overlay showing spook level, active spirit, emotion, and fog density.
/// Also provides a slider for manually adjusting spook level.
/// Stripped in release builds to avoid exposing debug controls.
/// </summary>
public class DebugUI : MonoBehaviour
{
#if UNITY_EDITOR || DEVELOPMENT_BUILD
    [Header("UI Components")]
    [SerializeField] private GameObject debugPanel;
    [SerializeField] private TMP_Text debugText;
    [SerializeField] private Slider spookSlider;

    [Header("Settings")]
    [SerializeField] private KeyCode toggleKey = KeyCode.F1;
    [SerializeField] private KeyCode randomSpiritKey = KeyCode.F2;
    [SerializeField] private KeyCode toggleChatKey = KeyCode.F3;
    [SerializeField] private KeyCode skipSceneKey = KeyCode.F4;
    [SerializeField] private KeyCode resetSpookKey = KeyCode.F5;

    [Header("Display")]
    [SerializeField] private float updateInterval = 0.25f;

    private float lastUpdateTime = 0f;
    private bool isVisible = false;

    private void Start()
    {
        // Initialize debug panel
        if (debugPanel != null)
        {
            debugPanel.SetActive(false);
        }

        // Setup slider
        if (spookSlider != null)
        {
            spookSlider.minValue = 0;
            spookSlider.maxValue = 5;
            spookSlider.wholeNumbers = true;
            spookSlider.value = 0;
            spookSlider.onValueChanged.AddListener(OnSliderChanged);
        }
    }

    private void Update()
    {
        // Handle hotkeys
        HandleHotkeys();

        // Update debug display
        if (isVisible && Time.time - lastUpdateTime >= updateInterval)
        {
            lastUpdateTime = Time.time;
            UpdateDebugDisplay();
        }
    }

    /// <summary>
    /// Handles debug hotkey inputs.
    /// </summary>
    private void HandleHotkeys()
    {
        // F1: Toggle debug panel
        if (Input.GetKeyDown(toggleKey))
        {
            ToggleDebugPanel();
        }

        // F2: Summon random spirit
        if (Input.GetKeyDown(randomSpiritKey))
        {
            SummonRandomSpirit();
        }

        // F3: Toggle chat UI
        if (Input.GetKeyDown(toggleChatKey))
        {
            if (UIChat.Instance != null)
            {
                UIChat.Instance.ToggleChat();
            }
        }

        // F4: Skip to portal (debug)
        if (Input.GetKeyDown(skipSceneKey))
        {
            if (PortalSequence.Instance != null)
            {
                PortalSequence.Instance.SkipToScene();
            }
        }

        // F5: Reset spook level
        if (Input.GetKeyDown(resetSpookKey))
        {
            ResetSpook();
        }
    }

    /// <summary>
    /// Toggles the debug panel visibility.
    /// </summary>
    public void ToggleDebugPanel()
    {
        isVisible = !isVisible;

        if (debugPanel != null)
        {
            debugPanel.SetActive(isVisible);
        }

        if (isVisible)
        {
            UpdateDebugDisplay();

            // Sync slider with current spook level
            if (spookSlider != null && EventManager.Instance != null)
            {
                spookSlider.SetValueWithoutNotify(EventManager.Instance.SpookLevel);
            }
        }

        Debug.Log($"[DebugUI] Panel visibility: {isVisible}");
    }

    /// <summary>
    /// Updates the debug text display.
    /// </summary>
    private void UpdateDebugDisplay()
    {
        if (debugText == null) return;

        System.Text.StringBuilder sb = new System.Text.StringBuilder();

        // Spook Level
        int spookLevel = EventManager.Instance?.SpookLevel ?? 0;
        sb.AppendLine($"Spook: {spookLevel}/5");

        // Active Spirit
        string activeSpirit = LLMManager.Instance?.ActiveSpirit ?? "None";
        sb.AppendLine($"Spirit: {activeSpirit}");

        // Current Emotion
        string emotion = RitualLoop.Instance?.GetCurrentEmotion() ?? "neutral";
        float intensity = RitualLoop.Instance?.GetEmotionIntensity() ?? 0f;
        sb.AppendLine($"Emotion: {emotion} ({intensity:F2})");

        // Fog Density
        sb.AppendLine($"Fog: {RenderSettings.fogDensity:F3}");

        // LLM Status
        bool isStreaming = LLMStreamManager.Instance?.IsStreaming() ?? false;
        sb.AppendLine($"LLM: {(isStreaming ? "Streaming..." : "Idle")}");

        // FPS
        sb.AppendLine($"FPS: {(int)(1f / Time.deltaTime)}");

        debugText.text = sb.ToString();
    }

    /// <summary>
    /// Called when the spook slider value changes.
    /// </summary>
    private void OnSliderChanged(float value)
    {
        if (EventManager.Instance != null)
        {
            EventManager.Instance.SetSpookLevel((int)value);
        }
    }

    /// <summary>
    /// Summons a random spirit (debug function).
    /// </summary>
    private void SummonRandomSpirit()
    {
        if (LLMManager.Instance != null)
        {
            string randomSpirit = LLMManager.Instance.GetRandomSpiritKey();
            LLMManager.Instance.SummonSpirit(randomSpirit);
            Debug.Log($"[DebugUI] Summoned random spirit: {randomSpirit}");
        }
    }

    /// <summary>
    /// Resets the spook level to zero.
    /// </summary>
    private void ResetSpook()
    {
        if (EventManager.Instance != null)
        {
            EventManager.Instance.ResetSpook();

            // Sync slider
            if (spookSlider != null)
            {
                spookSlider.SetValueWithoutNotify(0);
            }

            Debug.Log("[DebugUI] Spook level reset");
        }
    }

    /// <summary>
    /// Gets whether the debug panel is currently visible.
    /// </summary>
    public bool IsVisible()
    {
        return isVisible;
    }
#endif
}
