// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M10 - Debug UI

using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Debug UI overlay for monitoring and controlling spook level.
/// Shows real-time game state information during development.
/// </summary>
public class SpookLevelDebugUI : SceneSingletonBase<SpookLevelDebugUI>
{
    [Header("UI References")]
    [SerializeField] private Canvas debugCanvas;
    [SerializeField] private Slider spookSlider;
    [SerializeField] private Text spookValueText;
    [SerializeField] private Text debugInfoText;
    [SerializeField] private GameObject debugPanel;

    [Header("Settings")]
    [SerializeField] private bool showOnStart = false;
    [SerializeField] private KeyCode toggleKey = KeyCode.F12;
    [SerializeField] private float updateInterval = 0.25f;

    // State
    private bool isVisible = false;
    private float updateTimer = 0f;

    private void Start()
    {
        // Create UI if not assigned
        if (debugCanvas == null)
        {
            CreateDebugUI();
        }

        // Initialize slider
        if (spookSlider != null)
        {
            spookSlider.minValue = 0;
            spookSlider.maxValue = 5;
            spookSlider.wholeNumbers = true;
            spookSlider.onValueChanged.AddListener(OnSliderChanged);

            // Set initial value
            if (EventManager.Instance != null)
            {
                spookSlider.value = EventManager.Instance.SpookLevel;
            }
        }

        // Set initial visibility
        SetVisible(showOnStart);
    }

    private void Update()
    {
        // Toggle visibility
        if (Input.GetKeyDown(toggleKey))
        {
            ToggleVisibility();
        }

        // Update debug info periodically
        if (isVisible)
        {
            updateTimer += Time.deltaTime;
            if (updateTimer >= updateInterval)
            {
                updateTimer = 0f;
                UpdateDebugInfo();
            }
        }
    }

    /// <summary>
    /// Creates the debug UI elements programmatically.
    /// </summary>
    private void CreateDebugUI()
    {
        // Create canvas
        GameObject canvasObj = new GameObject("DebugCanvas");
        canvasObj.transform.SetParent(transform);

        debugCanvas = canvasObj.AddComponent<Canvas>();
        debugCanvas.renderMode = RenderMode.ScreenSpaceOverlay;
        debugCanvas.sortingOrder = 1000;

        canvasObj.AddComponent<CanvasScaler>();
        canvasObj.AddComponent<GraphicRaycaster>();

        // Create panel
        debugPanel = new GameObject("DebugPanel");
        debugPanel.transform.SetParent(canvasObj.transform);

        Image panelImage = debugPanel.AddComponent<Image>();
        panelImage.color = new Color(0f, 0f, 0f, 0.8f);

        RectTransform panelRect = debugPanel.GetComponent<RectTransform>();
        panelRect.anchorMin = new Vector2(0f, 0.6f);
        panelRect.anchorMax = new Vector2(0.3f, 1f);
        panelRect.offsetMin = new Vector2(10f, 10f);
        panelRect.offsetMax = new Vector2(-10f, -10f);

        // Create title
        GameObject titleObj = CreateTextElement(debugPanel.transform, "DEBUG PANEL (F12)", 16, TextAnchor.UpperCenter);
        RectTransform titleRect = titleObj.GetComponent<RectTransform>();
        titleRect.anchorMin = new Vector2(0f, 0.9f);
        titleRect.anchorMax = new Vector2(1f, 1f);
        titleRect.offsetMin = new Vector2(5f, 0f);
        titleRect.offsetMax = new Vector2(-5f, -5f);

        // Create slider label
        GameObject sliderLabel = CreateTextElement(debugPanel.transform, "Spook Level:", 14, TextAnchor.MiddleLeft);
        RectTransform sliderLabelRect = sliderLabel.GetComponent<RectTransform>();
        sliderLabelRect.anchorMin = new Vector2(0.05f, 0.75f);
        sliderLabelRect.anchorMax = new Vector2(0.5f, 0.85f);

        // Create slider value text
        GameObject valueObj = CreateTextElement(debugPanel.transform, "0", 14, TextAnchor.MiddleRight);
        spookValueText = valueObj.GetComponent<Text>();
        RectTransform valueRect = valueObj.GetComponent<RectTransform>();
        valueRect.anchorMin = new Vector2(0.7f, 0.75f);
        valueRect.anchorMax = new Vector2(0.95f, 0.85f);

        // Create slider
        GameObject sliderObj = CreateSlider(debugPanel.transform);
        RectTransform sliderRect = sliderObj.GetComponent<RectTransform>();
        sliderRect.anchorMin = new Vector2(0.05f, 0.65f);
        sliderRect.anchorMax = new Vector2(0.95f, 0.75f);

        // Create debug info text
        GameObject infoObj = CreateTextElement(debugPanel.transform, "", 12, TextAnchor.UpperLeft);
        debugInfoText = infoObj.GetComponent<Text>();
        RectTransform infoRect = infoObj.GetComponent<RectTransform>();
        infoRect.anchorMin = new Vector2(0.05f, 0.05f);
        infoRect.anchorMax = new Vector2(0.95f, 0.6f);
    }

    /// <summary>
    /// Creates a text UI element.
    /// </summary>
    private GameObject CreateTextElement(Transform parent, string content, int fontSize, TextAnchor anchor)
    {
        GameObject textObj = new GameObject("Text");
        textObj.transform.SetParent(parent);

        Text text = textObj.AddComponent<Text>();
        text.text = content;
        text.fontSize = fontSize;
        text.color = Color.white;
        text.alignment = anchor;
        text.font = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");

        RectTransform rect = textObj.GetComponent<RectTransform>();
        rect.anchorMin = Vector2.zero;
        rect.anchorMax = Vector2.one;
        rect.offsetMin = Vector2.zero;
        rect.offsetMax = Vector2.zero;

        return textObj;
    }

    /// <summary>
    /// Creates a slider UI element.
    /// </summary>
    private GameObject CreateSlider(Transform parent)
    {
        GameObject sliderObj = new GameObject("SpookSlider");
        sliderObj.transform.SetParent(parent);

        spookSlider = sliderObj.AddComponent<Slider>();
        spookSlider.minValue = 0;
        spookSlider.maxValue = 5;
        spookSlider.wholeNumbers = true;

        RectTransform sliderRect = sliderObj.AddComponent<RectTransform>();
        sliderRect.anchorMin = Vector2.zero;
        sliderRect.anchorMax = Vector2.one;

        // Background
        GameObject bgObj = new GameObject("Background");
        bgObj.transform.SetParent(sliderObj.transform);
        Image bgImage = bgObj.AddComponent<Image>();
        bgImage.color = new Color(0.2f, 0.2f, 0.2f);
        RectTransform bgRect = bgObj.GetComponent<RectTransform>();
        bgRect.anchorMin = new Vector2(0f, 0.4f);
        bgRect.anchorMax = new Vector2(1f, 0.6f);
        bgRect.offsetMin = Vector2.zero;
        bgRect.offsetMax = Vector2.zero;

        // Fill area
        GameObject fillAreaObj = new GameObject("FillArea");
        fillAreaObj.transform.SetParent(sliderObj.transform);
        RectTransform fillAreaRect = fillAreaObj.AddComponent<RectTransform>();
        fillAreaRect.anchorMin = new Vector2(0f, 0.4f);
        fillAreaRect.anchorMax = new Vector2(1f, 0.6f);
        fillAreaRect.offsetMin = Vector2.zero;
        fillAreaRect.offsetMax = Vector2.zero;

        GameObject fillObj = new GameObject("Fill");
        fillObj.transform.SetParent(fillAreaObj.transform);
        Image fillImage = fillObj.AddComponent<Image>();
        fillImage.color = new Color(0.8f, 0.3f, 0.3f);
        RectTransform fillRect = fillObj.GetComponent<RectTransform>();
        fillRect.anchorMin = Vector2.zero;
        fillRect.anchorMax = Vector2.one;
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;

        spookSlider.fillRect = fillRect;

        // Handle
        GameObject handleAreaObj = new GameObject("HandleSlideArea");
        handleAreaObj.transform.SetParent(sliderObj.transform);
        RectTransform handleAreaRect = handleAreaObj.AddComponent<RectTransform>();
        handleAreaRect.anchorMin = Vector2.zero;
        handleAreaRect.anchorMax = Vector2.one;
        handleAreaRect.offsetMin = Vector2.zero;
        handleAreaRect.offsetMax = Vector2.zero;

        GameObject handleObj = new GameObject("Handle");
        handleObj.transform.SetParent(handleAreaObj.transform);
        Image handleImage = handleObj.AddComponent<Image>();
        handleImage.color = Color.white;
        RectTransform handleRect = handleObj.GetComponent<RectTransform>();
        handleRect.sizeDelta = new Vector2(20f, 20f);

        spookSlider.handleRect = handleRect;
        spookSlider.targetGraphic = handleImage;

        return sliderObj;
    }

    /// <summary>
    /// Called when slider value changes.
    /// </summary>
    private void OnSliderChanged(float value)
    {
        int level = Mathf.RoundToInt(value);

        if (EventManager.Instance != null)
        {
            EventManager.Instance.SetSpookLevel(level);
        }

        if (spookValueText != null)
        {
            spookValueText.text = level.ToString();
        }

        Debug.Log($"[SpookLevelDebugUI] Spook level set to {level}");
    }

    /// <summary>
    /// Updates the debug information display.
    /// </summary>
    private void UpdateDebugInfo()
    {
        if (debugInfoText == null) return;

        System.Text.StringBuilder sb = new System.Text.StringBuilder();

        // Spook Level
        int spookLevel = EventManager.Instance?.SpookLevel ?? 0;
        sb.AppendLine($"Spook Level: {spookLevel}/5");

        // Active Spirit
        string activeSpirit = LLMManager.Instance?.ActiveSpirit ?? "None";
        sb.AppendLine($"Active Spirit: {activeSpirit}");

        // Current Emotion
        string emotion = RitualLoop.Instance?.GetCurrentEmotion() ?? "neutral";
        float intensity = RitualLoop.Instance?.GetEmotionIntensity() ?? 0f;
        sb.AppendLine($"Emotion: {emotion} ({intensity:F2})");

        // Fog Density
        float fogDensity = RenderSettings.fogDensity;
        sb.AppendLine($"Fog Density: {fogDensity:F3}");

        // Chat Visible
        bool chatVisible = UIChat.Instance?.IsVisible() ?? false;
        sb.AppendLine($"Chat UI: {(chatVisible ? "Visible" : "Hidden")}");

        // FPS
        float fps = 1f / Time.unscaledDeltaTime;
        sb.AppendLine($"FPS: {fps:F0}");

        // Player Position
        GameObject player = GameObject.FindGameObjectWithTag("Player");
        if (player != null)
        {
            Vector3 pos = player.transform.position;
            sb.AppendLine($"Player: ({pos.x:F1}, {pos.y:F1}, {pos.z:F1})");
        }

        // LLM Status
        bool isStreaming = LLMStreamManager.Instance?.IsStreaming() ?? false;
        sb.AppendLine($"LLM: {(isStreaming ? "Streaming" : "Idle")}");

        debugInfoText.text = sb.ToString();

        // Update slider to match current level
        if (spookSlider != null && spookSlider.value != spookLevel)
        {
            spookSlider.SetValueWithoutNotify(spookLevel);
        }
    }

    /// <summary>
    /// Toggles debug UI visibility.
    /// </summary>
    public void ToggleVisibility()
    {
        SetVisible(!isVisible);
    }

    /// <summary>
    /// Sets debug UI visibility.
    /// </summary>
    public void SetVisible(bool visible)
    {
        isVisible = visible;

        if (debugPanel != null)
        {
            debugPanel.SetActive(visible);
        }

        // Unlock cursor when debug UI is visible
        if (CursorManager.Instance != null)
        {
            if (visible)
            {
                CursorManager.Instance.RequestUnlock();
            }
            else
            {
                CursorManager.Instance.ReleaseUnlock();
            }
        }

        Debug.Log($"[SpookLevelDebugUI] Debug UI {(visible ? "shown" : "hidden")}");
    }

    /// <summary>
    /// Gets whether debug UI is visible.
    /// </summary>
    public bool IsVisible()
    {
        return isVisible;
    }

    /// <summary>
    /// Manually sets the spook level via slider.
    /// </summary>
    public void SetSpookLevel(int level)
    {
        if (spookSlider != null)
        {
            spookSlider.value = level;
        }
    }
}
