// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M7

using UnityEngine;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Manages the chat UI for player-spirit communication.
/// Handles input, message display, and visibility toggling.
/// </summary>
public class UIChat : MonoBehaviour
{
    public static UIChat Instance { get; private set; }

    [Header("UI Components")]
    [SerializeField] private TMP_InputField inputField;
    [SerializeField] private TMP_Text chatLog;
    [SerializeField] private ScrollRect scrollRect;
    [SerializeField] private CanvasGroup canvasGroup;
    [SerializeField] private Button sendButton;

    [Header("Settings")]
    [SerializeField] private KeyCode toggleKey = KeyCode.Escape;
    [SerializeField] private int maxLogLength = 5000;

    [Header("Colors")]
    [SerializeField] private string userColor = "#6666ff";
    [SerializeField] private string spiritColor = "#99ff66";
    [SerializeField] private string streamColor = "#ff9966";
    [SerializeField] private string systemColor = "#888888";

    // State
    private bool isVisible = false;
    private string lastUserMessage = "";

    private void Awake()
    {
        // Singleton pattern
        if (Instance == null)
        {
            Instance = this;
        }
        else
        {
            Destroy(gameObject);
            return;
        }
    }

    private void Start()
    {
        // Initialize UI state
        if (canvasGroup != null)
        {
            canvasGroup.alpha = 0f;
            canvasGroup.interactable = false;
            canvasGroup.blocksRaycasts = false;
        }

        // Setup input field
        if (inputField != null)
        {
            inputField.onSubmit.AddListener(OnInputSubmit);
        }

        // Setup send button
        if (sendButton != null)
        {
            sendButton.onClick.AddListener(SendMessage);
        }

        // Initialize chat log
        if (chatLog != null)
        {
            chatLog.text = $"<color={systemColor}>[The spirits await your words...]</color>";
        }

        // Hide cursor initially
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
    }

    private void Update()
    {
        // Toggle chat visibility
        if (Input.GetKeyDown(toggleKey))
        {
            ToggleChat();
        }
    }

    /// <summary>
    /// Toggles the chat UI visibility.
    /// </summary>
    public void ToggleChat()
    {
        isVisible = !isVisible;

        if (canvasGroup != null)
        {
            canvasGroup.alpha = isVisible ? 1f : 0f;
            canvasGroup.interactable = isVisible;
            canvasGroup.blocksRaycasts = isVisible;
        }

        // Manage cursor
        Cursor.visible = isVisible;
        Cursor.lockState = isVisible ? CursorLockMode.None : CursorLockMode.Locked;

        // Focus input field when visible
        if (isVisible && inputField != null)
        {
            inputField.ActivateInputField();
            inputField.Select();
        }

        Debug.Log($"[UIChat] Chat visibility: {isVisible}");
    }

    /// <summary>
    /// Shows the chat UI.
    /// </summary>
    public void Show()
    {
        if (!isVisible)
        {
            ToggleChat();
        }
    }

    /// <summary>
    /// Hides the chat UI.
    /// </summary>
    public void Hide()
    {
        if (isVisible)
        {
            ToggleChat();
        }
    }

    /// <summary>
    /// Called when user submits input via Enter key.
    /// </summary>
    private void OnInputSubmit(string text)
    {
        SendMessage();
    }

    /// <summary>
    /// Sends the current input as a message.
    /// </summary>
    public void SendMessage()
    {
        if (inputField == null) return;

        string message = inputField.text.Trim();
        if (string.IsNullOrEmpty(message)) return;

        // Store and display user message
        lastUserMessage = message;
        AppendUser(message);

        // Clear input
        inputField.text = "";
        inputField.ActivateInputField();

        // Trigger spirit response
        if (LLMManager.Instance != null)
        {
            string activeSpirit = LLMManager.Instance.ActiveSpirit;
            if (string.IsNullOrEmpty(activeSpirit))
            {
                activeSpirit = "Raven"; // Default spirit
            }
            LLMManager.Instance.SummonSpirit(activeSpirit);
        }
        else
        {
            AppendSystem("*The spirit connection is severed...*");
        }
    }

    /// <summary>
    /// Appends a user message to the chat log.
    /// </summary>
    /// <param name="message">The user's message</param>
    public void AppendUser(string message)
    {
        Append($"<color={userColor}>You:</color> {message}");
    }

    /// <summary>
    /// Appends a spirit response to the chat log.
    /// </summary>
    /// <param name="message">The spirit's response</param>
    public void AppendResponse(string message)
    {
        string spiritName = LLMManager.Instance?.ActiveSpirit ?? "Spirit";
        Append($"<color={spiritColor}>{spiritName}:</color> {message}");
    }

    /// <summary>
    /// Appends a partial/streaming response chunk.
    /// </summary>
    /// <param name="chunk">The text chunk to append</param>
    public void AppendPartial(string chunk)
    {
        if (chatLog == null) return;

        // For streaming, append directly without newline
        chatLog.text += $"<color={streamColor}>{chunk}</color>";
        TruncateLogIfNeeded();
        ScrollToBottom();
    }

    /// <summary>
    /// Appends a system message to the chat log.
    /// </summary>
    /// <param name="message">The system message</param>
    public void AppendSystem(string message)
    {
        Append($"<color={systemColor}>{message}</color>");
    }

    /// <summary>
    /// Core method to append text to the chat log.
    /// </summary>
    private void Append(string formattedMessage)
    {
        if (chatLog == null) return;

        chatLog.text += "\n" + formattedMessage;
        TruncateLogIfNeeded();
        ScrollToBottom();
    }

    /// <summary>
    /// Truncates the log if it exceeds max length.
    /// </summary>
    private void TruncateLogIfNeeded()
    {
        if (chatLog.text.Length > maxLogLength)
        {
            // Find first newline after overflow
            int cutPoint = chatLog.text.Length - maxLogLength;
            int newlineIndex = chatLog.text.IndexOf('\n', cutPoint);
            if (newlineIndex > 0)
            {
                chatLog.text = chatLog.text.Substring(newlineIndex + 1);
            }
        }
    }

    /// <summary>
    /// Scrolls the chat log to the bottom.
    /// </summary>
    private void ScrollToBottom()
    {
        if (scrollRect != null)
        {
            Canvas.ForceUpdateCanvases();
            scrollRect.verticalNormalizedPosition = 0f;
        }
    }

    /// <summary>
    /// Gets the last message sent by the user.
    /// </summary>
    public string GetLastUserMessage()
    {
        return lastUserMessage;
    }

    /// <summary>
    /// Clears the chat log.
    /// </summary>
    public void ClearLog()
    {
        if (chatLog != null)
        {
            chatLog.text = $"<color={systemColor}>[The slate is wiped clean...]</color>";
        }
    }

    /// <summary>
    /// Checks if the chat is currently visible.
    /// </summary>
    public bool IsVisible()
    {
        return isVisible;
    }
}
