// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M7

using System.Collections.Generic;
using System.Text;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;
using TMPro;

/// <summary>
/// Manages the chat UI for player-spirit communication.
/// Handles input, message display, and visibility toggling.
/// </summary>
public class UIChat : SceneSingletonBase<UIChat>
{

    [Header("UI Components")]
    [SerializeField] private TMP_InputField inputField;
    [SerializeField] private TMP_Text chatLog;
    [SerializeField] private ScrollRect scrollRect;
    [SerializeField] private CanvasGroup canvasGroup;
    [SerializeField] private Button sendButton;

    [Header("Settings")]
    [SerializeField] private KeyCode toggleKey = KeyCode.Escape;
    [SerializeField] private int maxLogLength = 5000;

    [Header("Colors")]
    [SerializeField] private string userColor = "#6666ff";
    [SerializeField] private string spiritColor = "#99ff66";
    [SerializeField] private string streamColor = "#ff9966";
    [SerializeField] private string systemColor = "#888888";

    // State
    private bool isVisible = false;
    private bool isLocked = false;
    private string lastUserMessage = "";

    // The log is kept as finished entries plus the reply currently streaming in,
    // and re-rendered from them, so truncation never cuts through markup.
    private readonly List<string> entries = new List<string>();
    private int entriesLength = 0;
    private readonly StringBuilder streamBuffer = new StringBuilder();
    private string streamLabel = null; // non-null while a reply is streaming

    protected override void Awake()
    {
        base.Awake();
        if (Instance != this) return;

        // The chat silently does nothing without these; say so (regenerate with CursedPortal > Setup Main Scene)
        if (inputField == null) Debug.LogError("[UIChat] inputField is not assigned.");
        if (chatLog == null) Debug.LogError("[UIChat] chatLog is not assigned.");
        if (canvasGroup == null) Debug.LogError("[UIChat] canvasGroup is not assigned; the chat can't be shown or hidden.");
    }

    private void Start()
    {
        // Initialize UI state
        if (canvasGroup != null)
        {
            canvasGroup.alpha = 0f;
            canvasGroup.interactable = false;
            canvasGroup.blocksRaycasts = false;
        }

        // Setup input field (Enter must submit, not insert a newline)
        if (inputField != null)
        {
            if (inputField.lineType == TMP_InputField.LineType.MultiLineNewline)
            {
                inputField.lineType = TMP_InputField.LineType.MultiLineSubmit;
            }
            inputField.onSubmit.AddListener(OnInputSubmit);
        }

        // Setup send button
        if (sendButton != null)
        {
            sendButton.onClick.AddListener(SendMessage);
        }

        if (EventSystem.current == null)
        {
            Debug.LogError("[UIChat] No EventSystem in the scene; the chat input can't receive keystrokes.");
        }

        // Initialize chat log
        AddEntry($"<color={systemColor}>[The spirits await your words...]</color>");

        // Hide cursor initially
        ApplyCursor(false);
    }

    private void Update()
    {
        // Toggle chat visibility
        if (!isLocked && Input.GetKeyDown(toggleKey))
        {
            ToggleChat();
        }
    }

    /// <summary>
    /// Toggles the chat UI visibility.
    /// </summary>
    public void ToggleChat()
    {
        if (isLocked && !isVisible) return;

        isVisible = !isVisible;

        if (canvasGroup != null)
        {
            canvasGroup.alpha = isVisible ? 1f : 0f;
            canvasGroup.interactable = isVisible;
            canvasGroup.blocksRaycasts = isVisible;
        }

        // Manage cursor
        ApplyCursor(isVisible);

        if (inputField != null)
        {
            if (isVisible)
            {
                // Focus input field when visible
                inputField.ActivateInputField();
                inputField.Select();
            }
            else
            {
                // A hidden but still focused field would keep swallowing keystrokes (WASD, Enter)
                inputField.DeactivateInputField();
                if (EventSystem.current != null)
                {
                    EventSystem.current.SetSelectedGameObject(null);
                }
            }
        }

        Debug.Log($"[UIChat] Chat visibility: {isVisible}");
    }

    /// <summary>
    /// Shows the chat UI.
    /// </summary>
    public void Show()
    {
        if (!isVisible)
        {
            ToggleChat();
        }
    }

    /// <summary>
    /// Hides the chat UI.
    /// </summary>
    public void Hide()
    {
        if (isVisible)
        {
            ToggleChat();
        }
    }

    /// <summary>
    /// Prevents the chat from being opened (e.g. during the portal transition).
    /// </summary>
    public void SetLocked(bool locked)
    {
        isLocked = locked;
        if (locked)
        {
            Hide();
        }
    }

    /// <summary>
    /// Called when user submits input via Enter key.
    /// </summary>
    private void OnInputSubmit(string text)
    {
        SendMessage();
    }

    /// <summary>
    /// Sends the current input as a message.
    /// </summary>
    public void SendMessage()
    {
        if (inputField == null || !isVisible) return;

        string message = inputField.text.Trim();
        if (string.IsNullOrEmpty(message))
        {
            // Submitting deactivates the field; keep it focused for the next attempt
            inputField.ActivateInputField();
            return;
        }

        // Store and display user message
        lastUserMessage = message;
        AppendUser(message);

        // Clear input
        inputField.text = "";
        inputField.ActivateInputField();

        // Trigger spirit response
        if (LLMManager.Instance != null)
        {
            string activeSpirit = LLMManager.Instance.ActiveSpirit;
            if (string.IsNullOrEmpty(activeSpirit))
            {
                activeSpirit = "Raven"; // Default spirit
            }
            LLMManager.Instance.SummonSpirit(activeSpirit, message);
        }
        else
        {
            AppendSystem("*The spirit connection is severed...*");
        }
    }

    /// <summary>
    /// Appends a user message to the chat log.
    /// </summary>
    /// <param name="message">The user's message</param>
    public void AppendUser(string message)
    {
        EndStream();
        AddEntry($"<color={userColor}>You:</color> {Escape(message)}");
    }

    /// <summary>
    /// Appends a spirit response to the chat log.
    /// </summary>
    /// <param name="message">The spirit's response</param>
    public void AppendResponse(string message)
    {
        EndStream();
        AddEntry($"<color={spiritColor}>{CurrentSpiritName()}:</color> {Escape(message)}");
    }

    /// <summary>
    /// Appends a partial/streaming response chunk to the reply currently streaming in.
    /// </summary>
    /// <param name="chunk">The text chunk to append</param>
    public void AppendPartial(string chunk)
    {
        if (streamLabel == null)
        {
            streamLabel = $"<color={spiritColor}>{CurrentSpiritName()}:</color> ";
            streamBuffer.Clear();
        }

        streamBuffer.Append(chunk);
        Render();
    }

    /// <summary>
    /// Commits the reply that was streaming in as a regular log entry.
    /// </summary>
    public void EndStream()
    {
        if (streamLabel == null) return;

        string finished = StreamEntry();
        streamLabel = null;
        streamBuffer.Clear();
        AddEntry(finished);
    }

    /// <summary>
    /// Appends a system message to the chat log.
    /// </summary>
    /// <param name="message">The system message</param>
    public void AppendSystem(string message)
    {
        EndStream();
        AddEntry($"<color={systemColor}>{Escape(message.Trim())}</color>");
    }

    /// <summary>
    /// Adds a finished entry, dropping the oldest entries beyond the length limit.
    /// </summary>
    private void AddEntry(string formattedEntry)
    {
        entries.Add(formattedEntry);
        entriesLength += formattedEntry.Length + 1;

        while (entriesLength > maxLogLength && entries.Count > 1)
        {
            entriesLength -= entries[0].Length + 1;
            entries.RemoveAt(0);
        }

        Render();
    }

    private string StreamEntry()
    {
        return $"{streamLabel}<color={streamColor}>{Escape(streamBuffer.ToString())}</color>";
    }

    /// <summary>
    /// Rebuilds the visible log from the entries and the in-progress reply.
    /// </summary>
    private void Render()
    {
        if (chatLog == null) return;

        string text = string.Join("\n", entries);
        if (streamLabel != null)
        {
            text += (entries.Count > 0 ? "\n" : "") + StreamEntry();
        }
        chatLog.text = text;
        ScrollToBottom();
    }

    /// <summary>
    /// Shows player and model text literally, so stray tags like &lt;s&gt; can't restyle the whole log.
    /// </summary>
    private static string Escape(string text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        return "<noparse>" + text.Replace("</noparse>", "</ noparse>") + "</noparse>";
    }

    private static string CurrentSpiritName()
    {
        string spiritName = LLMManager.Instance != null ? LLMManager.Instance.ActiveSpirit : null;
        return string.IsNullOrEmpty(spiritName) ? "Spirit" : spiritName;
    }

    /// <summary>
    /// Unlocks the cursor while the chat is open, through CursorManager when present so its state stays in sync.
    /// </summary>
    private void ApplyCursor(bool chatOpen)
    {
        if (CursorManager.Instance != null)
        {
            if (chatOpen) CursorManager.Instance.RequestUnlock();
            else CursorManager.Instance.ReleaseUnlock();
            return;
        }

        Cursor.visible = chatOpen;
        Cursor.lockState = chatOpen ? CursorLockMode.None : CursorLockMode.Locked;
    }

    /// <summary>
    /// Scrolls the chat log to the bottom.
    /// </summary>
    private void ScrollToBottom()
    {
        if (scrollRect != null)
        {
            Canvas.ForceUpdateCanvases();
            scrollRect.verticalNormalizedPosition = 0f;
        }
    }

    /// <summary>
    /// Gets the last message sent by the user.
    /// </summary>
    public string GetLastUserMessage()
    {
        return lastUserMessage;
    }

    /// <summary>
    /// Clears the chat log.
    /// </summary>
    public void ClearLog()
    {
        entries.Clear();
        entriesLength = 0;
        streamLabel = null;
        streamBuffer.Clear();
        AddEntry($"<color={systemColor}>[The slate is wiped clean...]</color>");
    }

    /// <summary>
    /// Checks if the chat is currently visible.
    /// </summary>
    public bool IsVisible()
    {
        return isVisible;
    }
}
