// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M21

using UnityEngine;
using UnityEngine.UI;
using TMPro;
using System.Collections;

/// <summary>
/// Handles the epilogue text display in the OtherDimension scene.
/// Features typewriter effect and conclusion prompts.
/// </summary>
public class UIEpilogue : SceneSingletonBase<UIEpilogue>
{
    [Header("UI Components")]
    [SerializeField] private TMP_Text epilogueText;
    [SerializeField] private TMP_Text promptText;
    [SerializeField] private CanvasGroup canvasGroup;
    [SerializeField] private Image backgroundImage;

    [Header("Typewriter Settings")]
    [SerializeField] private float charDelay = 0.05f;
    [SerializeField] private float punctuationDelay = 0.2f;
    [SerializeField] private AudioClip typeSound;

    [Header("Final Quote")]
    [SerializeField] private string finalQuote = "\"We are but echoes, bound by the words we weave.\"";

    [Header("Prompt Settings")]
    [SerializeField] private string awakenPrompt = "[E] to Awaken";
    [SerializeField] private float promptDelay = 2f;

    // State
    private bool isDisplaying = false;
    private bool displayComplete = false;
    private Coroutine displayCoroutine;

    private void Start()
    {
        // Initialize UI
        if (epilogueText != null)
        {
            epilogueText.text = "";
        }

        if (promptText != null)
        {
            promptText.text = "";
            promptText.gameObject.SetActive(false);
        }

        if (canvasGroup != null)
        {
            canvasGroup.alpha = 0f;
        }
    }

    private void Update()
    {
        // Check for awaken input after display complete
        if (displayComplete && Input.GetKeyDown(KeyCode.E))
        {
            OnAwaken();
        }
    }

    /// <summary>
    /// Displays the epilogue text with typewriter effect.
    /// </summary>
    /// <param name="text">The epilogue text from LLM</param>
    public void Display(string text)
    {
        if (isDisplaying)
        {
            // Cancel previous display
            if (displayCoroutine != null)
            {
                StopCoroutine(displayCoroutine);
            }
        }

        displayCoroutine = StartCoroutine(DisplayCoroutine(text));
    }

    /// <summary>
    /// Coroutine for typewriter display effect.
    /// </summary>
    private IEnumerator DisplayCoroutine(string text)
    {
        isDisplaying = true;
        displayComplete = false;

        // Fade in canvas
        yield return StartCoroutine(FadeCanvas(0f, 1f, 1f));

        // Clear text
        if (epilogueText != null)
        {
            epilogueText.text = "";
        }

        // Typewriter effect
        foreach (char c in text)
        {
            if (epilogueText != null)
            {
                epilogueText.text += c;
            }

            // Play type sound
            if (typeSound != null && AudioManager.Instance != null)
            {
                AudioManager.Instance.PlaySFX(typeSound, Random.Range(0.9f, 1.1f));
            }

            // Variable delay based on character
            if (c == '.' || c == '!' || c == '?')
            {
                yield return new WaitForSeconds(punctuationDelay);
            }
            else if (c == ',' || c == ';' || c == ':')
            {
                yield return new WaitForSeconds(punctuationDelay * 0.5f);
            }
            else
            {
                yield return new WaitForSeconds(charDelay);
            }
        }

        // Pause before final quote
        yield return new WaitForSeconds(1f);

        // Add final quote
        if (epilogueText != null && !string.IsNullOrEmpty(finalQuote))
        {
            epilogueText.text += "\n\n";

            foreach (char c in finalQuote)
            {
                epilogueText.text += c;

                if (c == '.' || c == '!' || c == '?' || c == '"')
                {
                    yield return new WaitForSeconds(punctuationDelay);
                }
                else
                {
                    yield return new WaitForSeconds(charDelay * 1.5f); // Slower for emphasis
                }
            }
        }

        // Wait before showing prompt
        yield return new WaitForSeconds(promptDelay);

        // Show awaken prompt
        if (promptText != null)
        {
            promptText.gameObject.SetActive(true);
            promptText.text = awakenPrompt;

            // Pulse animation
            StartCoroutine(PulsePrompt());
        }

        isDisplaying = false;
        displayComplete = true;

        Debug.Log("[UIEpilogue] Display complete, awaiting player input");
    }

    /// <summary>
    /// Pulses the prompt text for visibility.
    /// </summary>
    private IEnumerator PulsePrompt()
    {
        if (promptText == null) yield break;

        while (displayComplete)
        {
            // Fade out
            float elapsed = 0f;
            float duration = 0.8f;

            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                float alpha = Mathf.Lerp(1f, 0.3f, elapsed / duration);
                promptText.alpha = alpha;
                yield return null;
            }

            // Fade in
            elapsed = 0f;
            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                float alpha = Mathf.Lerp(0.3f, 1f, elapsed / duration);
                promptText.alpha = alpha;
                yield return null;
            }
        }
    }

    /// <summary>
    /// Called when player presses E to awaken/exit.
    /// </summary>
    private void OnAwaken()
    {
        Debug.Log("[UIEpilogue] Player awakening...");

        displayComplete = false;

        // Save any remaining memory
        if (LLMManager.Instance != null && !string.IsNullOrEmpty(LLMManager.Instance.ActiveSpirit))
        {
            // Final memory save handled by SpiritMemory
        }

        // Fade out and quit
        StartCoroutine(AwakenSequence());
    }

    /// <summary>
    /// Awaken/exit sequence.
    /// </summary>
    private IEnumerator AwakenSequence()
    {
        // Fade out audio
        if (AudioManager.Instance != null)
        {
            AudioManager.Instance.FadeOutAll(2f);
        }

        // Fade to black
        yield return StartCoroutine(FadeCanvas(1f, 0f, 2f));

        // Additional fade if background exists
        if (backgroundImage != null)
        {
            float elapsed = 0f;
            float duration = 1f;

            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                backgroundImage.color = Color.Lerp(backgroundImage.color, Color.black, elapsed / duration);
                yield return null;
            }
        }

        yield return new WaitForSeconds(1f);

        // Quit application
        Debug.Log("[UIEpilogue] Exiting application...");

#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
    }

    /// <summary>
    /// Fades the canvas group alpha.
    /// </summary>
    private IEnumerator FadeCanvas(float from, float to, float duration)
    {
        if (canvasGroup == null) yield break;

        float elapsed = 0f;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            canvasGroup.alpha = Mathf.Lerp(from, to, elapsed / duration);
            yield return null;
        }

        canvasGroup.alpha = to;
    }

    /// <summary>
    /// Skips the typewriter effect and shows full text immediately.
    /// </summary>
    public void SkipToEnd(string fullText)
    {
        if (displayCoroutine != null)
        {
            StopCoroutine(displayCoroutine);
        }

        if (epilogueText != null)
        {
            epilogueText.text = fullText + "\n\n" + finalQuote;
        }

        if (promptText != null)
        {
            promptText.gameObject.SetActive(true);
            promptText.text = awakenPrompt;
        }

        if (canvasGroup != null)
        {
            canvasGroup.alpha = 1f;
        }

        isDisplaying = false;
        displayComplete = true;
    }

    /// <summary>
    /// Shows the awakening prompt.
    /// Called by FinaleManager when epilogue is complete.
    /// </summary>
    public void ShowPrompt()
    {
        if (promptText != null)
        {
            promptText.gameObject.SetActive(true);
            promptText.text = awakenPrompt;
            StartCoroutine(PulsePrompt());
        }
        displayComplete = true;
    }

    /// <summary>
    /// Shows a final message during awakening.
    /// </summary>
    public void ShowFinalMessage(string message)
    {
        if (epilogueText != null)
        {
            epilogueText.text = message;
        }

        if (promptText != null)
        {
            promptText.gameObject.SetActive(false);
        }
    }

    /// <summary>
    /// Checks if display is complete.
    /// </summary>
    public bool IsDisplayComplete()
    {
        return displayComplete;
    }

    /// <summary>
    /// Checks if currently displaying.
    /// </summary>
    public bool IsDisplaying()
    {
        return isDisplaying;
    }
}
