// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M18-M24 - OtherDimension Scene Setup

#if UNITY_EDITOR
using TMPro;
using UnityEngine;
using UnityEditor;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using UnityEngine.UI;

/// <summary>
/// Generates the OtherDimension finale scene and saves it as Assets/Scenes/OtherDimension.unity
/// (registered in Build Settings): platform, spirit core, player camera, FinaleManager and the epilogue UI.
/// The persistent managers arrive from the parlor, so none are placed here (duplicates would destroy
/// whatever shares their GameObject). Played on its own, the finale shows the fallback epilogue.
/// Menu: CursedPortal > Create OtherDimension Scene
/// </summary>
public static class OtherDimensionSetup
{
    private const string FinaleProfilePath = "Assets/Settings/OtherDimension_VolumeProfile.asset";
    private static readonly Vector3 SpawnPosition = new Vector3(0f, 1.48f, -3f); // standing on the platform top (y 0.5)

    [MenuItem("CursedPortal/Create OtherDimension Scene", false, 101)]
    public static void CreateOtherDimensionScene()
    {
        if (!CursedPortalEditorUtil.EnsureTMPResources()) return;
        if (!CursedPortalEditorUtil.BeginNewScene(CursedPortalEditorUtil.FinaleScenePath)) return;

        SetupURP.EnsurePipelineAssigned();

        Debug.Log("[OtherDimensionSetup] Creating OtherDimension scene...");

        Transform playerSpawn = CreatePlayerSpawn();
        CreatePlayerRig();
        CreatePlatform();
        DimensionalLight spiritCore = CreateSpiritCore(out EpilogueNarrator narrator);
        CreateEnvironment();
        CreateLighting();
        CreatePostProcessing();
        UIEpilogue epilogueUI = CreateUIElements();
        SceneSetup.CreateScreenEffects(false);
        CursedPortalEditorUtil.CreateEventSystem();
        CreateFinaleManager(narrator, epilogueUI, spiritCore, playerSpawn);

        CursedPortalEditorUtil.SaveSceneAndRegister(CursedPortalEditorUtil.FinaleScenePath);

        string message = $"Saved {CursedPortalEditorUtil.FinaleScenePath} and added it to Build Settings.\n\n" +
                         "Play from the CursedPortal scene: the portal brings you here at spook level 5.";
        Debug.Log("[OtherDimensionSetup] " + message);
        if (!Application.isBatchMode)
        {
            EditorUtility.DisplayDialog("OtherDimension Setup", message, "OK");
        }
    }

    private static Transform CreatePlayerSpawn()
    {
        GameObject playerSpawn = new GameObject("PlayerSpawn");
        playerSpawn.transform.SetPositionAndRotation(SpawnPosition, Quaternion.identity); // facing the spirit core (+Z)
        playerSpawn.AddComponent<PlayerSpawnMarker>();
        Debug.Log("[OtherDimensionSetup] Created PlayerSpawn");
        return playerSpawn.transform;
    }

    /// <summary>
    /// A look-only player (no movement, so nobody walks off the floating platform), authored at the
    /// spawn pose because CameraController caches its yaw in Start.
    /// </summary>
    private static void CreatePlayerRig()
    {
        GameObject playerRig = new GameObject("PlayerRig");
        playerRig.tag = "Player";
        playerRig.transform.SetPositionAndRotation(SpawnPosition, Quaternion.identity);

        Camera cam = SceneSetup.CreateCameraRig(playerRig.transform);
        cam.backgroundColor = new Color(0.02f, 0.01f, 0.04f);
        Debug.Log("[OtherDimensionSetup] Created PlayerRig");
    }

    private static void CreatePlatform()
    {
        GameObject platform = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
        platform.name = "Platform";
        platform.transform.position = Vector3.zero;
        platform.transform.localScale = new Vector3(10f, 0.5f, 10f);
        platform.GetComponent<Renderer>().sharedMaterial =
            SceneSetup.CreateLitMaterial("Platform", new Color(0.2f, 0.15f, 0.25f), 0.7f, false);

        // The primitive's CapsuleCollider would become a 5 m sphere under this scale; use the real shape
        Object.DestroyImmediate(platform.GetComponent<Collider>());
        platform.AddComponent<MeshCollider>();

        // Edge glow ring (Unity has no torus primitive; a slightly wider, thin cylinder reads as a glowing rim)
        GameObject edgeGlow = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
        edgeGlow.name = "EdgeGlow";
        edgeGlow.transform.SetParent(platform.transform, false);
        edgeGlow.transform.localPosition = new Vector3(0f, 0.6f, 0f);
        edgeGlow.transform.localScale = new Vector3(1.05f, 0.1f, 1.05f);
        edgeGlow.GetComponent<Renderer>().sharedMaterial =
            SceneSetup.CreateUnlitMaterial("EdgeGlow", new Color(0.5f, 0.2f, 0.8f));
        Object.DestroyImmediate(edgeGlow.GetComponent<Collider>());

        Debug.Log("[OtherDimensionSetup] Created Platform");
    }

    private static DimensionalLight CreateSpiritCore(out EpilogueNarrator narrator)
    {
        GameObject spiritCore = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        spiritCore.name = "SpiritCore";
        spiritCore.transform.position = new Vector3(0f, 3f, 2f);
        spiritCore.transform.localScale = Vector3.one * 0.8f;
        spiritCore.GetComponent<Renderer>().sharedMaterial =
            SceneSetup.CreateUnlitMaterial("SpiritCore", new Color(0.8f, 0.4f, 1f));
        Object.DestroyImmediate(spiritCore.GetComponent<Collider>());

        GameObject coreLight = new GameObject("CoreLight");
        coreLight.transform.SetParent(spiritCore.transform, false);
        Light light = coreLight.AddComponent<Light>();
        light.type = LightType.Point;
        light.color = new Color(0.8f, 0.4f, 1f);
        light.intensity = 3f;
        light.range = 15f;

        DimensionalLight dimensional = spiritCore.AddComponent<DimensionalLight>();
        CursedPortalEditorUtil.SetRef(dimensional, "targetLight", light);
        SerializedObject so = new SerializedObject(dimensional);
        so.FindProperty("baseIntensity").floatValue = 3f; // DimensionalLight drives the light from these
        so.FindProperty("baseRange").floatValue = 15f;
        so.ApplyModifiedPropertiesWithoutUndo();

        narrator = spiritCore.AddComponent<EpilogueNarrator>();
        CursedPortalEditorUtil.SetRef(narrator, "spiritLight", dimensional);

        CreateOrbits(spiritCore.transform);
        Debug.Log("[OtherDimensionSetup] Created SpiritCore");
        return dimensional;
    }

    private static void CreateOrbits(Transform parent)
    {
        Color[] colors = { new Color(1f, 0.3f, 0.3f), new Color(0.3f, 0.3f, 1f), new Color(0.3f, 1f, 0.5f) };
        for (int i = 0; i < 3; i++)
        {
            GameObject wisp = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            wisp.name = $"Wisp_{i}";
            wisp.transform.SetParent(parent, false);
            wisp.transform.localScale = Vector3.one * 0.15f;

            float angle = i * 120f * Mathf.Deg2Rad;
            wisp.transform.localPosition = new Vector3(Mathf.Cos(angle) * 1.5f, 0f, Mathf.Sin(angle) * 1.5f);

            Object.DestroyImmediate(wisp.GetComponent<Collider>());
            wisp.GetComponent<Renderer>().sharedMaterial = SceneSetup.CreateUnlitMaterial($"Wisp_{i}", colors[i]);
            wisp.AddComponent<OrbitalMotion>();
        }
    }

    private static void CreateEnvironment()
    {
        GameObject environment = new GameObject("Environment");
        Material particleMat = SceneSetup.ParticleMaterial();

        ParticleSystem mist = SceneSetup.CreateParticles(environment.transform, "MistParticles", new Vector3(0f, 0.5f, 0f),
            particleMat, lifetime: 8f, speed: 0.2f, size: 3f, color: new Color(0.3f, 0.2f, 0.4f, 0.3f),
            maxParticles: 100, rate: 10f, playOnAwake: true);
        ParticleSystem.ShapeModule mistShape = mist.shape;
        mistShape.shapeType = ParticleSystemShapeType.Circle;
        mistShape.radius = 8f;
        mistShape.rotation = new Vector3(-90f, 0f, 0f); // circle in the horizontal plane

        ParticleSystem voidParticles = SceneSetup.CreateParticles(environment.transform, "VoidParticles", new Vector3(0f, 10f, 0f),
            particleMat, lifetime: 10f, speed: 0.5f, size: 0.1f, color: new Color(0.8f, 0.5f, 1f, 0.5f),
            maxParticles: 200, rate: 20f, playOnAwake: true);
        ParticleSystem.MainModule voidMain = voidParticles.main;
        voidMain.gravityModifier = 0.1f;
        ParticleSystem.ShapeModule voidShape = voidParticles.shape;
        voidShape.shapeType = ParticleSystemShapeType.Box;
        voidShape.scale = new Vector3(15f, 1f, 15f);

        Debug.Log("[OtherDimensionSetup] Created Environment");
    }

    /// <summary>
    /// Epilogue panel (TMP text, CanvasGroup, background) and the awaken prompt, wired to UIEpilogue.
    /// </summary>
    private static UIEpilogue CreateUIElements()
    {
        // Above ScreenEffects (50) so the final message stays readable over the fade to white
        Canvas canvas = CursedPortalEditorUtil.CreateCanvas("UIEpilogueCanvas", 100);
        UIEpilogue epilogue = canvas.gameObject.AddComponent<UIEpilogue>();

        RectTransform panel = CursedPortalEditorUtil.CreateRect("EpiloguePanel", canvas.transform,
            new Vector2(0.1f, 0.1f), new Vector2(0.9f, 0.4f));
        Image background = panel.gameObject.AddComponent<Image>();
        background.color = new Color(0f, 0f, 0f, 0.7f);
        background.raycastTarget = false;
        CanvasGroup group = panel.gameObject.AddComponent<CanvasGroup>();
        group.alpha = 0f;

        TextMeshProUGUI text = CursedPortalEditorUtil.CreateText("EpilogueText", panel, "", 30f,
            TextAlignmentOptions.Center, new Color(0.9f, 0.8f, 1f), Vector2.zero, Vector2.one);
        text.margin = new Vector4(30f, 20f, 30f, 20f);

        // Outside the panel's CanvasGroup so it can show while the panel is faded
        TextMeshProUGUI prompt = CursedPortalEditorUtil.CreateText("PromptText", canvas.transform, "[E] to Awaken", 26f,
            TextAlignmentOptions.Center, new Color(0.7f, 0.7f, 0.9f), new Vector2(0.3f, 0.03f), new Vector2(0.7f, 0.09f));

        CursedPortalEditorUtil.SetRef(epilogue, "epilogueText", text);
        CursedPortalEditorUtil.SetRef(epilogue, "promptText", prompt);
        CursedPortalEditorUtil.SetRef(epilogue, "canvasGroup", group);
        CursedPortalEditorUtil.SetRef(epilogue, "backgroundImage", background);

        Debug.Log("[OtherDimensionSetup] Created UI Elements");
        return epilogue;
    }

    private static void CreateLighting()
    {
        GameObject lighting = new GameObject("Lighting");

        GameObject dirLightObj = new GameObject("DirectionalLight");
        dirLightObj.transform.SetParent(lighting.transform);
        dirLightObj.transform.rotation = Quaternion.Euler(50f, -30f, 0f);

        Light dirLight = dirLightObj.AddComponent<Light>();
        dirLight.type = LightType.Directional;
        dirLight.color = new Color(0.3f, 0.2f, 0.4f);
        dirLight.intensity = 0.3f;

        for (int i = 0; i < 4; i++)
        {
            float angle = i * 90f * Mathf.Deg2Rad;
            Vector3 pos = new Vector3(Mathf.Cos(angle) * 12f, 2f, Mathf.Sin(angle) * 12f);

            GameObject rimLightObj = new GameObject($"RimLight_{i}");
            rimLightObj.transform.SetParent(lighting.transform);
            rimLightObj.transform.position = pos;

            Light rimLight = rimLightObj.AddComponent<Light>();
            rimLight.type = LightType.Point;
            rimLight.color = new Color(0.4f, 0.2f, 0.6f);
            rimLight.intensity = 1f;
            rimLight.range = 10f;
        }

        RenderSettings.skybox = null;
        RenderSettings.ambientMode = AmbientMode.Flat;
        RenderSettings.ambientLight = new Color(0.1f, 0.05f, 0.15f);
        RenderSettings.fog = true;
        RenderSettings.fogMode = FogMode.Exponential;
        RenderSettings.fogColor = new Color(0.05f, 0.02f, 0.1f);
        RenderSettings.fogDensity = 0.05f;

        Debug.Log("[OtherDimensionSetup] Created Lighting");
    }

    private static void CreatePostProcessing()
    {
        GameObject ppVolume = new GameObject("PostProcessVolume");

        Volume volume = ppVolume.AddComponent<Volume>();
        volume.isGlobal = true;
        volume.priority = 1f;

        // A saved profile asset assigned as sharedProfile; Volume.profile is a runtime copy that isn't saved
        VolumeProfile profile = AssetDatabase.LoadAssetAtPath<VolumeProfile>(FinaleProfilePath);
        if (profile == null)
        {
            CursedPortalEditorUtil.EnsureFolder("Assets/Settings");
            profile = ScriptableObject.CreateInstance<VolumeProfile>();
            AssetDatabase.CreateAsset(profile, FinaleProfilePath);

            Vignette vignette = SceneSetup.AddProfileComponent<Vignette>(profile);
            vignette.intensity.Override(0.5f);
            vignette.color.Override(new Color(0.2f, 0f, 0.3f));

            ColorAdjustments colorAdj = SceneSetup.AddProfileComponent<ColorAdjustments>(profile);
            colorAdj.saturation.Override(-30f);
            colorAdj.contrast.Override(20f);
            colorAdj.colorFilter.Override(new Color(0.8f, 0.7f, 1f));

            Bloom bloom = SceneSetup.AddProfileComponent<Bloom>(profile);
            bloom.threshold.Override(0.8f);
            bloom.intensity.Override(2f);
            bloom.tint.Override(new Color(0.8f, 0.5f, 1f));

            EditorUtility.SetDirty(profile);
            AssetDatabase.SaveAssets();
        }
        volume.sharedProfile = profile;

        Debug.Log("[OtherDimensionSetup] Created Post-Processing Volume");
    }

    private static void CreateFinaleManager(EpilogueNarrator narrator, UIEpilogue epilogueUI,
        DimensionalLight spiritCore, Transform playerSpawn)
    {
        GameObject finaleObj = new GameObject("FinaleManager");
        AudioSource ambient = finaleObj.AddComponent<AudioSource>();
        ambient.loop = true;
        ambient.playOnAwake = false;
        ambient.spatialBlend = 0f;

        FinaleManager finale = finaleObj.AddComponent<FinaleManager>();
        CursedPortalEditorUtil.SetRef(finale, "epilogueNarrator", narrator);
        CursedPortalEditorUtil.SetRef(finale, "uiEpilogue", epilogueUI);
        CursedPortalEditorUtil.SetRef(finale, "spiritCore", spiritCore);
        CursedPortalEditorUtil.SetRef(finale, "playerSpawn", playerSpawn);
        CursedPortalEditorUtil.SetRef(finale, "ambientSource", ambient);

        Debug.Log("[OtherDimensionSetup] Created FinaleManager");
    }
}
#endif
