// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M25

#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.IO;

/// <summary>
/// Editor utility to automatically generate prefabs for the Cursed Portal project.
/// Accessible via menu: CursedPortal > Build Prefabs
/// </summary>
public static class PrefabBuilder
{
    private const string PREFAB_ROOT = "Assets/Prefabs/";
    private const string MANAGERS_PATH = PREFAB_ROOT + "Managers/";
    private const string PROPS_PATH = PREFAB_ROOT + "Props/";

    [MenuItem("CursedPortal/Build Prefabs", false, 10)]
    public static void BuildAll()
    {
        Debug.Log("[PrefabBuilder] Starting prefab generation...");

        // Ensure directories exist
        EnsureDirectoryExists(MANAGERS_PATH);
        EnsureDirectoryExists(PROPS_PATH);

        // Build prefabs
        BuildManagerPrefab();
        BuildPropPrefab("CrystalBall", "Raven", PrimitiveType.Sphere, new Vector3(0.5f, 0.5f, 0.5f));
        BuildPropPrefab("Mirror", "Narrator", PrimitiveType.Quad, new Vector3(2f, 3f, 0.1f));
        BuildPropPrefab("Booth", "Usher", PrimitiveType.Cube, new Vector3(2f, 2.5f, 2f));
        BuildPropPrefab("Table", "Raven", PrimitiveType.Cube, new Vector3(2f, 0.8f, 1f));

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log("[PrefabBuilder] All prefabs generated successfully!");
        EditorUtility.DisplayDialog("Prefab Builder", "All Cursed Portal prefabs have been generated!", "OK");
    }

    [MenuItem("CursedPortal/Build Managers Prefab Only", false, 11)]
    public static void BuildManagersOnly()
    {
        EnsureDirectoryExists(MANAGERS_PATH);
        BuildManagerPrefab();
        AssetDatabase.SaveAssets();
        Debug.Log("[PrefabBuilder] Managers prefab generated!");
    }

    [MenuItem("CursedPortal/Build Props Prefabs Only", false, 12)]
    public static void BuildPropsOnly()
    {
        EnsureDirectoryExists(PROPS_PATH);
        BuildPropPrefab("CrystalBall", "Raven", PrimitiveType.Sphere, new Vector3(0.5f, 0.5f, 0.5f));
        BuildPropPrefab("Mirror", "Narrator", PrimitiveType.Quad, new Vector3(2f, 3f, 0.1f));
        BuildPropPrefab("Booth", "Usher", PrimitiveType.Cube, new Vector3(2f, 2.5f, 2f));
        BuildPropPrefab("Table", "Raven", PrimitiveType.Cube, new Vector3(2f, 0.8f, 1f));
        AssetDatabase.SaveAssets();
        Debug.Log("[PrefabBuilder] Props prefabs generated!");
    }

    /// <summary>
    /// Builds the Managers prefab containing all singleton managers.
    /// </summary>
    private static void BuildManagerPrefab()
    {
        GameObject managersGO = new GameObject("Managers");

        // Add all manager components
        managersGO.AddComponent<LLMManager>();
        managersGO.AddComponent<LLMStreamManager>();
        managersGO.AddComponent<EventManager>();
        managersGO.AddComponent<RitualLoop>();
        managersGO.AddComponent<PortalSequence>();

        // Create child for Audio
        GameObject audioGO = new GameObject("AudioManager");
        audioGO.transform.SetParent(managersGO.transform);
        audioGO.AddComponent<AudioManager>();

        // Create child for VFX
        GameObject vfxGO = new GameObject("VFXManager");
        vfxGO.transform.SetParent(managersGO.transform);
        vfxGO.AddComponent<VFXManager>();

        // Create child for PostFX
        GameObject postfxGO = new GameObject("PostFXController");
        postfxGO.transform.SetParent(managersGO.transform);
        postfxGO.AddComponent<PostFXController>();

        // Save as prefab
        string prefabPath = MANAGERS_PATH + "Managers.prefab";
        PrefabUtility.SaveAsPrefabAsset(managersGO, prefabPath);
        Object.DestroyImmediate(managersGO);

        Debug.Log($"[PrefabBuilder] Created: {prefabPath}");
    }

    /// <summary>
    /// Builds an interactable prop prefab.
    /// </summary>
    private static void BuildPropPrefab(string name, string spiritKey, PrimitiveType primitiveType, Vector3 scale)
    {
        // Create primitive
        GameObject propGO = GameObject.CreatePrimitive(primitiveType);
        propGO.name = name;
        propGO.transform.localScale = scale;

        // Set layer (create "Interactable" layer if needed)
        // propGO.layer = LayerMask.NameToLayer("Interactable");

        // Add InteractableSpirit component
        InteractableSpirit spirit = propGO.AddComponent<InteractableSpirit>();

        // Configure via serialized field (requires reflection or manual setup in editor)
        // For now, just log that it needs manual configuration
        Debug.Log($"[PrefabBuilder] {name}: Set spiritKey to '{spiritKey}' in Inspector");

        // Add point light for glow effect
        GameObject lightGO = new GameObject("GlowLight");
        lightGO.transform.SetParent(propGO.transform);
        lightGO.transform.localPosition = Vector3.up * 0.5f;
        Light light = lightGO.AddComponent<Light>();
        light.type = LightType.Point;
        light.range = 3f;
        light.intensity = 0.5f;
        light.color = new Color(0.5f, 0.3f, 0.8f); // Purple glow
        light.enabled = false; // Disabled by default, enabled on highlight

        // Save as prefab
        string prefabPath = PROPS_PATH + name + ".prefab";
        PrefabUtility.SaveAsPrefabAsset(propGO, prefabPath);
        Object.DestroyImmediate(propGO);

        Debug.Log($"[PrefabBuilder] Created: {prefabPath}");
    }

    /// <summary>
    /// Ensures a directory exists, creating it if necessary.
    /// </summary>
    private static void EnsureDirectoryExists(string path)
    {
        if (!Directory.Exists(path))
        {
            Directory.CreateDirectory(path);
            AssetDatabase.Refresh();
        }
    }
}
#endif
