// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M25

#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using System.IO;

/// <summary>
/// Editor utility to automatically generate prefabs for the Cursed Portal project.
/// Accessible via menu: CursedPortal > Build Prefabs
/// </summary>
public static class PrefabBuilder
{
    private const string PREFAB_ROOT = "Assets/Prefabs/";
    private const string MANAGERS_PATH = PREFAB_ROOT + "Managers/";
    private const string PROPS_PATH = PREFAB_ROOT + "Props/";

    [MenuItem("CursedPortal/Build Prefabs", false, 10)]
    public static void BuildAll()
    {
        Debug.Log("[PrefabBuilder] Starting prefab generation...");

        // Ensure directories exist
        EnsureDirectoryExists(MANAGERS_PATH);
        EnsureDirectoryExists(PROPS_PATH);

        // Build prefabs
        BuildManagerPrefab();
        BuildAllPropPrefabs();

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log("[PrefabBuilder] All prefabs generated successfully!");
        if (!Application.isBatchMode)
        {
            EditorUtility.DisplayDialog("Prefab Builder", "All Cursed Portal prefabs have been generated!", "OK");
        }
    }

    [MenuItem("CursedPortal/Build Managers Prefab Only", false, 11)]
    public static void BuildManagersOnly()
    {
        EnsureDirectoryExists(MANAGERS_PATH);
        BuildManagerPrefab();
        AssetDatabase.SaveAssets();
        Debug.Log("[PrefabBuilder] Managers prefab generated!");
    }

    [MenuItem("CursedPortal/Build Props Prefabs Only", false, 12)]
    public static void BuildPropsOnly()
    {
        EnsureDirectoryExists(PROPS_PATH);
        BuildAllPropPrefabs();
        AssetDatabase.SaveAssets();
        Debug.Log("[PrefabBuilder] Props prefabs generated!");
    }

    private static void BuildAllPropPrefabs()
    {
        // Mirror is a thin box rather than a Quad (one-sided, and its collider is a flat mesh)
        BuildPropPrefab("CrystalBall", "Raven", PrimitiveType.Sphere, new Vector3(0.35f, 0.35f, 0.35f));
        BuildPropPrefab("Mirror", "Narrator", PrimitiveType.Cube, new Vector3(0.05f, 2f, 1.2f));
        BuildPropPrefab("Booth", "Usher", PrimitiveType.Cube, new Vector3(1.4f, 2.2f, 1.4f));
    }

    /// <summary>
    /// Builds the Managers prefab containing all persistent (DontDestroyOnLoad) managers on one root.
    /// Place it only in the parlor scene: a second copy in another scene destroys itself on load.
    /// </summary>
    private static void BuildManagerPrefab()
    {
        GameObject managersGO = new GameObject("Managers");

        // Add all manager components (the same set SceneSetup uses)
        managersGO.AddComponent<GameManager>();
        managersGO.AddComponent<EventManager>();
        managersGO.AddComponent<RitualLoop>();
        managersGO.AddComponent<LLMManager>();
        managersGO.AddComponent<LLMStreamManager>();
        managersGO.AddComponent<CursorManager>();
        managersGO.AddComponent<PortalSequence>();
        managersGO.AddComponent<AudioManager>();
        managersGO.AddComponent<VFXManager>();
        managersGO.AddComponent<PostFXController>();

        // Save as prefab
        string prefabPath = MANAGERS_PATH + "Managers.prefab";
        PrefabUtility.SaveAsPrefabAsset(managersGO, prefabPath);
        Object.DestroyImmediate(managersGO);

        Debug.Log($"[PrefabBuilder] Created: {prefabPath}");
    }

    /// <summary>
    /// Builds an interactable prop prefab.
    /// </summary>
    private static void BuildPropPrefab(string name, string spiritKey, PrimitiveType primitiveType, Vector3 scale)
    {
        // Create primitive
        GameObject propGO = GameObject.CreatePrimitive(primitiveType);
        propGO.name = name;
        propGO.transform.localScale = scale;

        // Set layer (create "Interactable" layer if needed)
        // propGO.layer = LayerMask.NameToLayer("Interactable");

        // Emission-enabled material so the highlight (which sets _EmissionColor) is visible
        propGO.GetComponent<Renderer>().sharedMaterial =
            SceneSetup.CreateLitMaterial($"Prop_{name}", new Color(0.3f, 0.22f, 0.35f), 0.6f, true);

        // Add point light for glow effect
        GameObject lightGO = new GameObject("GlowLight");
        lightGO.transform.SetParent(propGO.transform, false);
        lightGO.transform.localPosition = Vector3.up * 0.5f;
        Light light = lightGO.AddComponent<Light>();
        light.type = LightType.Point;
        light.range = 3f;
        light.intensity = 1.5f;
        light.color = new Color(0.5f, 0.3f, 0.8f); // Purple glow
        light.enabled = false; // Disabled by default, enabled on highlight

        // Add InteractableSpirit component, bound to its spirit and glow light
        InteractableSpirit spirit = propGO.AddComponent<InteractableSpirit>();
        CursedPortalEditorUtil.SetString(spirit, "spiritKey", spiritKey);
        CursedPortalEditorUtil.SetRef(spirit, "glowLight", light);

        // Save as prefab
        string prefabPath = PROPS_PATH + name + ".prefab";
        PrefabUtility.SaveAsPrefabAsset(propGO, prefabPath);
        Object.DestroyImmediate(propGO);

        Debug.Log($"[PrefabBuilder] Created: {prefabPath}");
    }

    /// <summary>
    /// Ensures a directory exists, creating it if necessary.
    /// </summary>
    private static void EnsureDirectoryExists(string path)
    {
        if (!Directory.Exists(path))
        {
            Directory.CreateDirectory(path);
            AssetDatabase.Refresh();
        }
    }
}
#endif
