// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M25 - Editor Tools

#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Editor tool to automatically set up the CursedPortal scene with all required objects.
/// Menu: CursedPortal > Setup Scene
/// </summary>
public static class SceneSetup
{
    [MenuItem("CursedPortal/Setup Main Scene", false, 100)]
    public static void SetupMainScene()
    {
        Debug.Log("[SceneSetup] Setting up CursedPortal scene...");

        // Create root objects
        CreateManagers();
        CreatePlayerRig();
        CreateRoom();
        CreateEnvironment();
        CreateUI();

        Debug.Log("[SceneSetup] Scene setup complete! Save the scene.");
        EditorUtility.DisplayDialog("Scene Setup", "CursedPortal scene has been set up.\nRemember to save the scene!", "OK");
    }

    [MenuItem("CursedPortal/Setup Finale Scene", false, 101)]
    public static void SetupFinaleScene()
    {
        Debug.Log("[SceneSetup] Setting up OtherDimension scene...");

        CreateManagers();
        CreateFinalePlayerRig();
        CreateFinalePlatform();
        CreateSpiritCore();
        CreateFinaleUI();

        Debug.Log("[SceneSetup] Finale scene setup complete!");
        EditorUtility.DisplayDialog("Scene Setup", "OtherDimension scene has been set up.\nRemember to save the scene!", "OK");
    }

    private static void CreateManagers()
    {
        if (Object.FindObjectOfType<GameManager>() != null)
        {
            Debug.Log("[SceneSetup] Managers already exist, skipping...");
            return;
        }

        GameObject managers = new GameObject("Managers");
        managers.AddComponent<GameManager>();
        managers.AddComponent<EventManager>();
        managers.AddComponent<RitualLoop>();
        managers.AddComponent<LLMManager>();
        managers.AddComponent<LLMStreamManager>();
        managers.AddComponent<PortalSequence>();
        managers.AddComponent<CursorManager>();

        // Audio child
        GameObject audio = new GameObject("Audio");
        audio.transform.SetParent(managers.transform);
        audio.AddComponent<AudioManager>();
        audio.AddComponent<VoiceSynth>();

        // VFX child
        GameObject vfx = new GameObject("VFX");
        vfx.transform.SetParent(managers.transform);
        vfx.AddComponent<VFXManager>();
        vfx.AddComponent<PostFXController>();

        Debug.Log("[SceneSetup] Created Managers");
    }

    private static void CreatePlayerRig()
    {
        GameObject playerRig = new GameObject("PlayerRig");
        playerRig.transform.position = new Vector3(0f, 1.8f, -8f);
        playerRig.tag = "Player";

        // Add CharacterController
        CharacterController cc = playerRig.AddComponent<CharacterController>();
        cc.height = 1.8f;
        cc.radius = 0.3f;
        cc.center = new Vector3(0f, -0.9f, 0f);

        // Add FirstPersonController
        playerRig.AddComponent<FirstPersonController>();

        // Create camera
        GameObject cameraObj = new GameObject("MainCamera");
        cameraObj.transform.SetParent(playerRig.transform);
        cameraObj.transform.localPosition = Vector3.zero;
        cameraObj.tag = "MainCamera";

        Camera cam = cameraObj.AddComponent<Camera>();
        cam.fieldOfView = 70f;
        cam.nearClipPlane = 0.1f;

        cameraObj.AddComponent<CameraController>();
        cameraObj.AddComponent<InteractionManager>();
        cameraObj.AddComponent<AudioListener>();

        Debug.Log("[SceneSetup] Created PlayerRig");
    }

    private static void CreateRoom()
    {
        GameObject roomRoot = new GameObject("RoomRoot");

        // Floor
        GameObject floor = GameObject.CreatePrimitive(PrimitiveType.Cube);
        floor.name = "Floor";
        floor.transform.SetParent(roomRoot.transform);
        floor.transform.localScale = new Vector3(10f, 0.1f, 10f);
        floor.transform.position = new Vector3(0f, -0.05f, 0f);

        // Ceiling
        GameObject ceiling = GameObject.CreatePrimitive(PrimitiveType.Cube);
        ceiling.name = "Ceiling";
        ceiling.transform.SetParent(roomRoot.transform);
        ceiling.transform.localScale = new Vector3(10f, 0.1f, 10f);
        ceiling.transform.position = new Vector3(0f, 5.05f, 0f);

        // Walls
        CreateWall(roomRoot.transform, "WallNorth", new Vector3(0f, 2.5f, 5f), new Vector3(10f, 5f, 0.1f));
        CreateWall(roomRoot.transform, "WallSouth", new Vector3(0f, 2.5f, -5f), new Vector3(10f, 5f, 0.1f));
        CreateWall(roomRoot.transform, "WallEast", new Vector3(5f, 2.5f, 0f), new Vector3(0.1f, 5f, 10f));
        CreateWall(roomRoot.transform, "WallWest", new Vector3(-5f, 2.5f, 0f), new Vector3(0.1f, 5f, 10f));

        // Props
        CreateProp(roomRoot.transform, "Table", new Vector3(0f, 0.4f, 0f), "Raven");
        CreateProp(roomRoot.transform, "CrystalBall", new Vector3(0f, 1f, 0f), "Raven");
        CreateProp(roomRoot.transform, "Mirror", new Vector3(-4.9f, 2f, 0f), "Narrator");
        CreateProp(roomRoot.transform, "Booth", new Vector3(3f, 0f, 3f), "Usher");

        Debug.Log("[SceneSetup] Created Room");
    }

    private static void CreateWall(Transform parent, string name, Vector3 position, Vector3 scale)
    {
        GameObject wall = GameObject.CreatePrimitive(PrimitiveType.Cube);
        wall.name = name;
        wall.transform.SetParent(parent);
        wall.transform.position = position;
        wall.transform.localScale = scale;
    }

    private static void CreateProp(Transform parent, string name, Vector3 position, string spiritKey)
    {
        PrimitiveType type = name == "CrystalBall" ? PrimitiveType.Sphere : PrimitiveType.Cube;
        GameObject prop = GameObject.CreatePrimitive(type);
        prop.name = name;
        prop.transform.SetParent(parent);
        prop.transform.position = position;

        if (name == "CrystalBall")
            prop.transform.localScale = Vector3.one * 0.4f;
        else if (name == "Mirror")
        {
            prop.transform.localScale = new Vector3(0.1f, 2f, 1.5f);
            prop.transform.rotation = Quaternion.Euler(0f, 90f, 0f);
        }

        InteractableSpirit spirit = prop.AddComponent<InteractableSpirit>();
        // Note: spiritKey needs to be set in inspector
        Debug.Log($"[SceneSetup] Created prop {name} - set spiritKey to '{spiritKey}' in Inspector");
    }

    private static void CreateEnvironment()
    {
        GameObject environment = new GameObject("Environment");

        // Directional light
        GameObject lightObj = new GameObject("DirectionalLight");
        lightObj.transform.SetParent(environment.transform);
        lightObj.transform.rotation = Quaternion.Euler(50f, -30f, 0f);
        Light light = lightObj.AddComponent<Light>();
        light.type = LightType.Directional;
        light.intensity = 0.2f;
        light.color = new Color(0.6f, 0.5f, 0.8f);

        // Global Volume
        GameObject volumeObj = new GameObject("GlobalVolume");
        volumeObj.transform.SetParent(environment.transform);
        Volume volume = volumeObj.AddComponent<Volume>();
        volume.isGlobal = true;

        Debug.Log("[SceneSetup] Created Environment - Add Volume Profile manually");
    }

    private static void CreateUI()
    {
        // Chat UI
        GameObject chatCanvas = new GameObject("ChatCanvas");
        Canvas canvas = chatCanvas.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        chatCanvas.AddComponent<UnityEngine.UI.CanvasScaler>();
        chatCanvas.AddComponent<UnityEngine.UI.GraphicRaycaster>();
        chatCanvas.AddComponent<UIChat>();

        // Debug UI
        GameObject debugCanvas = new GameObject("DebugCanvas");
        Canvas debugC = debugCanvas.AddComponent<Canvas>();
        debugC.renderMode = RenderMode.ScreenSpaceOverlay;
        debugCanvas.AddComponent<UnityEngine.UI.CanvasScaler>();
        debugCanvas.AddComponent<DebugUI>();

        Debug.Log("[SceneSetup] Created UI - Add UI elements manually");
    }

    private static void CreateFinalePlayerRig()
    {
        GameObject playerRig = new GameObject("PlayerRig");
        playerRig.transform.position = new Vector3(0f, 1.8f, 0f);
        playerRig.tag = "Player";

        CharacterController cc = playerRig.AddComponent<CharacterController>();
        cc.height = 1.8f;
        playerRig.AddComponent<FirstPersonController>();

        GameObject cameraObj = new GameObject("MainCamera");
        cameraObj.transform.SetParent(playerRig.transform);
        cameraObj.transform.localPosition = Vector3.zero;
        cameraObj.tag = "MainCamera";
        cameraObj.AddComponent<Camera>().fieldOfView = 70f;
        cameraObj.AddComponent<CameraController>();
        cameraObj.AddComponent<AudioListener>();
    }

    private static void CreateFinalePlatform()
    {
        GameObject platform = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
        platform.name = "Platform";
        platform.transform.position = Vector3.zero;
        platform.transform.localScale = new Vector3(8f, 0.2f, 8f);
    }

    private static void CreateSpiritCore()
    {
        GameObject core = GameObject.CreatePrimitive(PrimitiveType.Sphere);
        core.name = "SpiritCore";
        core.transform.position = new Vector3(0f, 3f, 2f);
        core.transform.localScale = Vector3.one * 0.5f;

        Light light = core.AddComponent<Light>();
        light.type = LightType.Point;
        light.range = 10f;
        light.intensity = 2f;
        light.color = Color.magenta;

        core.AddComponent<DimensionalLight>();
        core.AddComponent<EpilogueNarrator>();
    }

    private static void CreateFinaleUI()
    {
        GameObject canvas = new GameObject("EpilogueCanvas");
        Canvas c = canvas.AddComponent<Canvas>();
        c.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.AddComponent<UnityEngine.UI.CanvasScaler>();
        canvas.AddComponent<UIEpilogue>();
    }
}
#endif
