// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M25

#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Editor utility to automatically wire scene objects and verify setup.
/// Accessible via menu: CursedPortal > Wire Scene Objects
/// </summary>
public static class SceneWiringTool
{
    [MenuItem("CursedPortal/Wire Scene Objects", false, 20)]
    public static void WireScene()
    {
        Debug.Log("[SceneWiringTool] Wiring scene objects...");

        int issuesFixed = 0;
        int warningsFound = 0;

        // Find and verify managers
        var eventMgr = Object.FindObjectOfType<EventManager>();
        var audioMgr = Object.FindObjectOfType<AudioManager>();
        var vfxMgr = Object.FindObjectOfType<VFXManager>();
        var postFX = Object.FindObjectOfType<PostFXController>();
        var llmMgr = Object.FindObjectOfType<LLMManager>();
        var ritualLoop = Object.FindObjectOfType<RitualLoop>();

        // Check for missing managers
        if (eventMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] EventManager not found in scene!");
            warningsFound++;
        }
        if (audioMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] AudioManager not found in scene!");
            warningsFound++;
        }
        if (vfxMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] VFXManager not found in scene!");
            warningsFound++;
        }
        if (postFX == null)
        {
            Debug.LogWarning("[SceneWiringTool] PostFXController not found in scene!");
            warningsFound++;
        }
        if (llmMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] LLMManager not found in scene!");
            warningsFound++;
        }

        // Wire PostFXController to Volume
        if (postFX != null)
        {
            Volume volume = Object.FindObjectOfType<Volume>();
            if (volume != null)
            {
                SerializedObject so = new SerializedObject(postFX);
                SerializedProperty volumeProp = so.FindProperty("volume");
                if (volumeProp != null && volumeProp.objectReferenceValue == null)
                {
                    volumeProp.objectReferenceValue = volume;
                    so.ApplyModifiedProperties();
                    Debug.Log("[SceneWiringTool] Wired PostFXController to Volume");
                    issuesFixed++;
                }
            }
            else
            {
                Debug.LogWarning("[SceneWiringTool] No Volume found for PostFXController!");
                warningsFound++;
            }
        }

        // Verify interactables have proper setup
        var interactables = Object.FindObjectsOfType<InteractableSpirit>();
        foreach (var interactable in interactables)
        {
            // Check for collider
            if (interactable.GetComponent<Collider>() == null)
            {
                Debug.LogWarning($"[SceneWiringTool] {interactable.gameObject.name} has no Collider!");
                warningsFound++;
            }
        }

        // Verify camera setup
        Camera mainCam = Camera.main;
        if (mainCam == null)
        {
            Debug.LogWarning("[SceneWiringTool] No MainCamera found! Tag a camera as 'MainCamera'.");
            warningsFound++;
        }
        else
        {
            // Check for InteractionManager
            if (mainCam.GetComponent<InteractionManager>() == null &&
                mainCam.GetComponentInParent<InteractionManager>() == null)
            {
                Debug.LogWarning("[SceneWiringTool] InteractionManager not found on camera or parent!");
                warningsFound++;
            }
        }

        // Check UI
        var uiChat = Object.FindObjectOfType<UIChat>();
        if (uiChat == null)
        {
            Debug.LogWarning("[SceneWiringTool] UIChat not found in scene!");
            warningsFound++;
        }

        // Summary
        string message = $"Scene wiring complete!\n\nIssues fixed: {issuesFixed}\nWarnings: {warningsFound}";

        if (warningsFound > 0)
        {
            message += "\n\nCheck Console for details.";
        }

        Debug.Log($"[SceneWiringTool] Complete - Fixed: {issuesFixed}, Warnings: {warningsFound}");
        EditorUtility.DisplayDialog("Scene Wiring Tool", message, "OK");
    }

    [MenuItem("CursedPortal/Validate Scene Setup", false, 21)]
    public static void ValidateScene()
    {
        Debug.Log("[SceneWiringTool] Validating scene setup...");

        bool isValid = true;
        System.Text.StringBuilder report = new System.Text.StringBuilder();
        report.AppendLine("=== Scene Validation Report ===\n");

        // Check managers
        report.AppendLine("MANAGERS:");
        isValid &= CheckComponent<EventManager>("EventManager", report);
        isValid &= CheckComponent<AudioManager>("AudioManager", report);
        isValid &= CheckComponent<VFXManager>("VFXManager", report);
        isValid &= CheckComponent<PostFXController>("PostFXController", report);
        isValid &= CheckComponent<LLMManager>("LLMManager", report);
        isValid &= CheckComponent<RitualLoop>("RitualLoop", report);
        isValid &= CheckComponent<PortalSequence>("PortalSequence", report);

        // Check UI
        report.AppendLine("\nUI:");
        isValid &= CheckComponent<UIChat>("UIChat", report);

        // Check interactables
        report.AppendLine("\nINTERACTABLES:");
        var interactables = Object.FindObjectsOfType<InteractableSpirit>();
        report.AppendLine($"  Found {interactables.Length} InteractableSpirit(s)");
        if (interactables.Length == 0)
        {
            report.AppendLine("  [WARNING] No interactable props found!");
            isValid = false;
        }

        // Check camera
        report.AppendLine("\nCAMERA:");
        if (Camera.main != null)
        {
            report.AppendLine("  [OK] MainCamera found");
        }
        else
        {
            report.AppendLine("  [FAIL] No MainCamera!");
            isValid = false;
        }

        // Check interaction manager
        isValid &= CheckComponent<InteractionManager>("InteractionManager", report);

        // Check lighting
        report.AppendLine("\nLIGHTING:");
        var lights = Object.FindObjectsOfType<Light>();
        report.AppendLine($"  Found {lights.Length} light(s)");

        // Check post-processing volume
        report.AppendLine("\nPOST-PROCESSING:");
        var volume = Object.FindObjectOfType<Volume>();
        if (volume != null)
        {
            report.AppendLine("  [OK] Volume found");
        }
        else
        {
            report.AppendLine("  [WARNING] No Volume found!");
        }

        // Summary
        report.AppendLine("\n=== RESULT ===");
        report.AppendLine(isValid ? "Scene is properly configured!" : "Scene has issues - see warnings above.");

        Debug.Log(report.ToString());

        EditorUtility.DisplayDialog("Scene Validation",
            isValid ? "Scene is properly configured!" : "Scene has issues. Check Console for details.",
            "OK");
    }

    private static bool CheckComponent<T>(string name, System.Text.StringBuilder report) where T : Component
    {
        T component = Object.FindObjectOfType<T>();
        if (component != null)
        {
            report.AppendLine($"  [OK] {name}");
            return true;
        }
        else
        {
            report.AppendLine($"  [FAIL] {name} not found!");
            return false;
        }
    }

    [MenuItem("CursedPortal/Create Interactable Layer", false, 30)]
    public static void CreateInteractableLayer()
    {
        // This would require modifying TagManager asset
        Debug.Log("[SceneWiringTool] To create Interactable layer:");
        Debug.Log("1. Go to Edit > Project Settings > Tags and Layers");
        Debug.Log("2. Add 'Interactable' to User Layer 6");
        Debug.Log("3. Set all prop prefabs to this layer");

        EditorUtility.DisplayDialog("Create Layer",
            "Please manually create the 'Interactable' layer:\n\n" +
            "1. Edit > Project Settings > Tags and Layers\n" +
            "2. Add 'Interactable' to User Layer 6\n" +
            "3. Set prop prefabs to this layer",
            "OK");
    }
}
#endif
