// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M25

#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Editor utility to automatically wire scene objects and verify setup.
/// Accessible via menu: CursedPortal > Wire Scene Objects
/// </summary>
public static class SceneWiringTool
{
    [MenuItem("CursedPortal/Wire Scene Objects", false, 20)]
    public static void WireScene()
    {
        Debug.Log("[SceneWiringTool] Wiring scene objects...");

        int issuesFixed = 0;
        int warningsFound = 0;

        // Find and verify managers
        var eventMgr = Object.FindFirstObjectByType<EventManager>();
        var audioMgr = Object.FindFirstObjectByType<AudioManager>();
        var vfxMgr = Object.FindFirstObjectByType<VFXManager>();
        var postFX = Object.FindFirstObjectByType<PostFXController>();
        var llmMgr = Object.FindFirstObjectByType<LLMManager>();
        var ritualLoop = Object.FindFirstObjectByType<RitualLoop>();

        // Check for missing managers
        if (eventMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] EventManager not found in scene!");
            warningsFound++;
        }
        if (audioMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] AudioManager not found in scene!");
            warningsFound++;
        }
        if (vfxMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] VFXManager not found in scene!");
            warningsFound++;
        }
        if (postFX == null)
        {
            Debug.LogWarning("[SceneWiringTool] PostFXController not found in scene!");
            warningsFound++;
        }
        if (llmMgr == null)
        {
            Debug.LogWarning("[SceneWiringTool] LLMManager not found in scene!");
            warningsFound++;
        }

        // Wire PostFXController to Volume
        if (postFX != null)
        {
            Volume volume = Object.FindFirstObjectByType<Volume>();
            if (volume != null)
            {
                SerializedObject so = new SerializedObject(postFX);
                SerializedProperty volumeProp = so.FindProperty("volume");
                if (volumeProp != null && volumeProp.objectReferenceValue == null)
                {
                    volumeProp.objectReferenceValue = volume;
                    so.ApplyModifiedProperties();
                    Debug.Log("[SceneWiringTool] Wired PostFXController to Volume");
                    issuesFixed++;
                }
            }
            else
            {
                Debug.LogWarning("[SceneWiringTool] No Volume found for PostFXController!");
                warningsFound++;
            }
        }

        // Verify interactables have proper setup
        var interactables = Object.FindObjectsByType<InteractableSpirit>(FindObjectsSortMode.None);
        foreach (var interactable in interactables)
        {
            // Check for collider
            if (interactable.GetComponent<Collider>() == null)
            {
                Debug.LogWarning($"[SceneWiringTool] {interactable.gameObject.name} has no Collider!");
                warningsFound++;
            }
        }

        // Verify camera setup
        Camera mainCam = Camera.main;
        if (mainCam == null)
        {
            Debug.LogWarning("[SceneWiringTool] No MainCamera found! Tag a camera as 'MainCamera'.");
            warningsFound++;
        }
        else
        {
            // Check for InteractionManager
            if (mainCam.GetComponent<InteractionManager>() == null &&
                mainCam.GetComponentInParent<InteractionManager>() == null)
            {
                Debug.LogWarning("[SceneWiringTool] InteractionManager not found on camera or parent!");
                warningsFound++;
            }
        }

        // Check UI
        var uiChat = Object.FindFirstObjectByType<UIChat>();
        if (uiChat == null)
        {
            Debug.LogWarning("[SceneWiringTool] UIChat not found in scene!");
            warningsFound++;
        }

        // Summary
        string message = $"Scene wiring complete!\n\nIssues fixed: {issuesFixed}\nWarnings: {warningsFound}";

        if (warningsFound > 0)
        {
            message += "\n\nCheck Console for details.";
        }

        Debug.Log($"[SceneWiringTool] Complete - Fixed: {issuesFixed}, Warnings: {warningsFound}");
        EditorUtility.DisplayDialog("Scene Wiring Tool", message, "OK");
    }

    [MenuItem("CursedPortal/Validate Scene Setup", false, 21)]
    public static void ValidateScene()
    {
        Debug.Log("[SceneWiringTool] Validating scene setup...");

        bool isValid = true;
        System.Text.StringBuilder report = new System.Text.StringBuilder();
        report.AppendLine("=== Scene Validation Report ===\n");

        // Check managers
        report.AppendLine("MANAGERS:");
        isValid &= CheckComponent<EventManager>("EventManager", report);
        isValid &= CheckComponent<AudioManager>("AudioManager", report);
        isValid &= CheckComponent<VFXManager>("VFXManager", report);
        isValid &= CheckComponent<PostFXController>("PostFXController", report);
        isValid &= CheckComponent<LLMManager>("LLMManager", report);
        isValid &= CheckComponent<RitualLoop>("RitualLoop", report);
        isValid &= CheckComponent<PortalSequence>("PortalSequence", report);

        // Check UI
        report.AppendLine("\nUI:");
        isValid &= CheckComponent<UIChat>("UIChat", report);
        isValid &= CheckComponent<UnityEngine.EventSystems.EventSystem>("EventSystem", report);
        UIChat chat = Object.FindFirstObjectByType<UIChat>();
        if (chat != null)
        {
            isValid &= CheckReferences(chat, report, "inputField", "chatLog", "scrollRect", "canvasGroup");
        }

        // Check interactables
        report.AppendLine("\nINTERACTABLES:");
        var interactables = Object.FindObjectsByType<InteractableSpirit>(FindObjectsSortMode.None);
        report.AppendLine($"  Found {interactables.Length} InteractableSpirit(s)");
        foreach (var interactable in interactables)
        {
            report.AppendLine($"    {interactable.gameObject.name} -> {interactable.GetSpiritKey()}");
        }
        if (interactables.Length == 0)
        {
            report.AppendLine("  [WARNING] No interactable props found!");
            isValid = false;
        }

        // Check camera
        report.AppendLine("\nCAMERA:");
        if (Camera.main != null)
        {
            report.AppendLine("  [OK] MainCamera found");
        }
        else
        {
            report.AppendLine("  [FAIL] No MainCamera!");
            isValid = false;
        }

        // Check interaction manager
        isValid &= CheckComponent<InteractionManager>("InteractionManager", report);

        // Check lighting
        report.AppendLine("\nLIGHTING:");
        var lights = Object.FindObjectsByType<Light>(FindObjectsSortMode.None);
        report.AppendLine($"  Found {lights.Length} light(s)");

        // Check post-processing volume
        report.AppendLine("\nPOST-PROCESSING:");
        if (GraphicsSettings.defaultRenderPipeline == null)
        {
            report.AppendLine("  [FAIL] No render pipeline asset: run CursedPortal > Configure URP Render Pipeline");
            isValid = false;
        }
        var volume = Object.FindFirstObjectByType<Volume>();
        if (volume != null)
        {
            report.AppendLine(volume.sharedProfile != null
                ? "  [OK] Volume found"
                : "  [WARNING] Volume has no profile asset");
        }
        else
        {
            report.AppendLine("  [WARNING] No Volume found!");
        }

        // Check build settings
        report.AppendLine("\nBUILD SETTINGS:");
        if (Application.CanStreamedLevelBeLoaded("OtherDimension") ||
            System.Array.Exists(EditorBuildSettings.scenes, s => s.enabled && s.path.EndsWith("/OtherDimension.unity") && System.IO.File.Exists(s.path)))
        {
            report.AppendLine("  [OK] OtherDimension scene registered");
        }
        else
        {
            report.AppendLine("  [FAIL] OtherDimension scene missing: run CursedPortal > Create OtherDimension Scene");
            isValid = false;
        }

        // Summary
        report.AppendLine("\n=== RESULT ===");
        report.AppendLine(isValid ? "Scene is properly configured!" : "Scene has issues - see warnings above.");

        Debug.Log(report.ToString());

        EditorUtility.DisplayDialog("Scene Validation",
            isValid ? "Scene is properly configured!" : "Scene has issues. Check Console for details.",
            "OK");
    }

    private static bool CheckReferences(Object target, System.Text.StringBuilder report, params string[] fields)
    {
        bool ok = true;
        SerializedObject so = new SerializedObject(target);
        foreach (string field in fields)
        {
            SerializedProperty prop = so.FindProperty(field);
            if (prop == null || prop.objectReferenceValue == null)
            {
                report.AppendLine($"  [FAIL] {target.GetType().Name}.{field} is not assigned");
                ok = false;
            }
        }
        return ok;
    }

    private static bool CheckComponent<T>(string name, System.Text.StringBuilder report) where T : Component
    {
        T component = Object.FindFirstObjectByType<T>();
        if (component != null)
        {
            report.AppendLine($"  [OK] {name}");
            return true;
        }
        else
        {
            report.AppendLine($"  [FAIL] {name} not found!");
            return false;
        }
    }

    [MenuItem("CursedPortal/Create Interactable Layer", false, 30)]
    public static void CreateInteractableLayer()
    {
        // The layer is already defined in ProjectSettings/TagManager.asset (User Layer 8)
        int layer = LayerMask.NameToLayer("Interactable");
        string message = layer >= 0
            ? $"The 'Interactable' layer exists (User Layer {layer}).\n\nAssign it to props and set " +
              "InteractionManager's Interactable Mask to it if you want the interaction ray to ignore other objects."
            : "Add 'Interactable' in Edit > Project Settings > Tags and Layers, then assign it to props.";
        Debug.Log("[SceneWiringTool] " + message);
        EditorUtility.DisplayDialog("Interactable Layer", message, "OK");
    }
}
#endif
