// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M14

using System.Text.RegularExpressions;
using UnityEngine;

/// <summary>
/// Analyzes LLM output text for emotional tone.
/// Used to drive environmental responses (fog, lights, audio).
/// </summary>
public static class EmotionParser
{
    // Emotion categories
    public const string TERROR = "terror";
    public const string UNEASE = "unease";
    public const string NEUTRAL = "neutral";

    // Regex patterns for emotion detection
    // Note: "heart" moved to poeHorrorPattern as it's specific to Tell-Tale Heart
    private static readonly Regex terrorPattern = new Regex(
        @"\b(terror|fear|dread|mad|scream|death|die|dying|blood|horror|shriek|agony|torment|demon|hell|damned|cursed|haunted|possessed)\b",
        RegexOptions.IgnoreCase | RegexOptions.Compiled
    );

    private static readonly Regex uneasePattern = new Regex(
        @"\b(sad|lament|mourn|decay|nevermore|sorrow|grief|weep|tear|lost|shadow|dark|gloom|despair|melancholy|woe|tomb|grave|dust|ash|forgotten|fade|wither)\b",
        RegexOptions.IgnoreCase | RegexOptions.Compiled
    );

    // Special Poe-specific patterns (includes "heart" for Tell-Tale Heart, "beating" for the heartbeat)
    private static readonly Regex poeHorrorPattern = new Regex(
        @"\b(raven|usher|tell-tale|heart|beating|floorboard|madman|buried|alive|premature|crypt|catacomb|pendulum|pit|masque|red death)\b",
        RegexOptions.IgnoreCase | RegexOptions.Compiled
    );

    /// <summary>
    /// Detects the primary emotion in the given text.
    /// </summary>
    /// <param name="text">The text to analyze</param>
    /// <returns>Emotion category: "terror", "unease", or "neutral"</returns>
    public static string Detect(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return NEUTRAL;
        }

        // Count matches for each category
        int terrorScore = CountMatches(terrorPattern, text);
        int uneaseScore = CountMatches(uneasePattern, text);

        // Boost score for Poe-specific horror terms
        int poeScore = CountMatches(poeHorrorPattern, text);
        terrorScore += poeScore / 2;

        // Determine emotion based on scores
        if (terrorScore > uneaseScore && terrorScore > 0)
        {
            return TERROR;
        }
        else if (uneaseScore > 0)
        {
            return UNEASE;
        }

        return NEUTRAL;
    }

    /// <summary>
    /// Gets a detailed emotion analysis with scores.
    /// </summary>
    /// <param name="text">The text to analyze</param>
    /// <returns>EmotionAnalysis struct with scores</returns>
    public static EmotionAnalysis AnalyzeDetailed(string text)
    {
        if (string.IsNullOrEmpty(text))
        {
            return new EmotionAnalysis { primaryEmotion = NEUTRAL };
        }

        int terrorScore = CountMatches(terrorPattern, text);
        int uneaseScore = CountMatches(uneasePattern, text);
        int poeScore = CountMatches(poeHorrorPattern, text);

        string primary;
        if (terrorScore > uneaseScore && terrorScore > 0)
        {
            primary = TERROR;
        }
        else if (uneaseScore > 0)
        {
            primary = UNEASE;
        }
        else
        {
            primary = NEUTRAL;
        }

        return new EmotionAnalysis
        {
            primaryEmotion = primary,
            terrorScore = terrorScore,
            uneaseScore = uneaseScore,
            poeScore = poeScore,
            intensity = CalculateIntensity(terrorScore, uneaseScore, poeScore)
        };
    }

    /// <summary>
    /// Counts regex matches in text.
    /// </summary>
    private static int CountMatches(Regex pattern, string text)
    {
        return pattern.Matches(text).Count;
    }

    /// <summary>
    /// Calculates overall emotional intensity (0-1 scale).
    /// </summary>
    private static float CalculateIntensity(int terror, int unease, int poe)
    {
        int total = terror + unease + poe;

        // Scale based on typical response length (~50-100 words)
        float intensity = Mathf.Clamp01(total / 5f);

        return intensity;
    }

    /// <summary>
    /// Checks if text contains any Poe-specific references.
    /// </summary>
    public static bool ContainsPoeReferences(string text)
    {
        return poeHorrorPattern.IsMatch(text);
    }

    /// <summary>
    /// Gets keywords found in the text for debugging.
    /// </summary>
    public static string[] GetDetectedKeywords(string text)
    {
        if (string.IsNullOrEmpty(text)) return new string[0];

        var keywords = new System.Collections.Generic.List<string>();

        foreach (Match match in terrorPattern.Matches(text))
        {
            if (!keywords.Contains(match.Value.ToLower()))
                keywords.Add(match.Value.ToLower());
        }

        foreach (Match match in uneasePattern.Matches(text))
        {
            if (!keywords.Contains(match.Value.ToLower()))
                keywords.Add(match.Value.ToLower());
        }

        foreach (Match match in poeHorrorPattern.Matches(text))
        {
            if (!keywords.Contains(match.Value.ToLower()))
                keywords.Add(match.Value.ToLower());
        }

        return keywords.ToArray();
    }
}

/// <summary>
/// Detailed emotion analysis result.
/// </summary>
[System.Serializable]
public struct EmotionAnalysis
{
    public string primaryEmotion;
    public int terrorScore;
    public int uneaseScore;
    public int poeScore;
    public float intensity;

    public override string ToString()
    {
        return $"Emotion: {primaryEmotion} (Terror:{terrorScore}, Unease:{uneaseScore}, Poe:{poeScore}, Intensity:{intensity:F2})";
    }
}
