// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M3

using UnityEngine;
using UnityEngine.Networking;
using System.IO;
using System.Collections;

/// <summary>
/// Central manager for LLM-based Poe spirit interactions.
/// Handles spirit summoning, context building, and response processing.
/// </summary>
public class LLMManager : SingletonBase<LLMManager>
{

    public enum LLMBackend { LlamaCpp, Ollama }

    [Header("LLM Configuration")]
    [SerializeField] private LLMBackend backend = LLMBackend.Ollama;
    [SerializeField] private string llmEndpoint = "http://localhost:11434/api/generate";
    [SerializeField] private string ollamaModel = "llama3.2:3b";
    [SerializeField] private int maxContextLength = 4000;
    [SerializeField] private float temperature = 0.8f;
    [SerializeField] private int maxTokens = 256;

    // Current state (properties are not serialized, so no inspector header)
    public string ActiveSpirit { get; private set; }
    public string ActiveStory { get; private set; }

    // Spirit profile data structure
    [System.Serializable]
    public class SpiritProfile
    {
        public string story;
        public string prompt;
    }

    [System.Serializable]
    private class SpiritProfiles
    {
        public SpiritProfile Raven;
        public SpiritProfile Narrator;
        public SpiritProfile Usher;
    }

    // Cached profiles
    private SpiritProfiles profiles;
    private bool profilesLoaded = false;

    // Cached story texts to avoid blocking I/O during gameplay
    private System.Collections.Generic.Dictionary<string, string> cachedStories =
        new System.Collections.Generic.Dictionary<string, string>();

    // On WebGL and Android, StreamingAssets is a URL and must be read with UnityWebRequest
    private static bool StreamingAssetsIsUrl => Application.streamingAssetsPath.Contains("://");

    private void Start()
    {
        // Load profiles and pre-load story files without blocking gameplay
        StartCoroutine(LoadSpiritData());
    }

    /// <summary>
    /// Loads spirit profiles and story texts from StreamingAssets on every platform.
    /// </summary>
    private IEnumerator LoadSpiritData()
    {
        if (!profilesLoaded)
        {
            string json = null;
            yield return ReadStreamingAsset(Path.Combine("SpiritProfiles", "poe_spirits.json"), text => json = text);
            ApplyProfilesJson(json);
        }

        string[] storyFiles = { "raven.txt", "tell-tale-heart.txt", "usher.txt" };
        foreach (string storyFile in storyFiles)
        {
            if (cachedStories.ContainsKey(storyFile)) continue;

            string fileContent = null;
            yield return ReadStreamingAsset(Path.Combine("PoeStories", storyFile), text => fileContent = text);

            if (fileContent != null)
            {
                cachedStories[storyFile] = PrepareStoryExcerpt(storyFile, fileContent);
                Debug.Log($"[LLMManager] Pre-loaded story: {storyFile}");
            }
        }

        Debug.Log($"[LLMManager] Story preloading complete. Cached {cachedStories.Count} stories.");
    }

    /// <summary>
    /// Reads a text file under StreamingAssets (null if missing or unreadable).
    /// </summary>
    private static IEnumerator ReadStreamingAsset(string relativePath, System.Action<string> onLoaded)
    {
        string path = Path.Combine(Application.streamingAssetsPath, relativePath);

        if (!StreamingAssetsIsUrl)
        {
            string text = null;
            try
            {
                if (File.Exists(path)) text = File.ReadAllText(path);
                else Debug.LogWarning($"[LLMManager] File not found: {path}");
            }
            catch (System.Exception e)
            {
                Debug.LogWarning($"[LLMManager] Failed to read {path}: {e.Message}");
            }
            onLoaded(text);
            yield break;
        }

        using (UnityWebRequest request = UnityWebRequest.Get(path))
        {
            yield return request.SendWebRequest();
            if (request.result == UnityWebRequest.Result.Success)
            {
                onLoaded(request.downloadHandler.text);
            }
            else
            {
                Debug.LogWarning($"[LLMManager] Failed to load {path}: {request.error}");
                onLoaded(null);
            }
        }
    }

    /// <summary>
    /// Parses the spirit profiles JSON.
    /// </summary>
    private void ApplyProfilesJson(string json)
    {
        if (string.IsNullOrEmpty(json))
        {
            Debug.LogError("[LLMManager] Spirit profiles could not be loaded from StreamingAssets/SpiritProfiles/poe_spirits.json");
            return;
        }

        try
        {
            profiles = JsonUtility.FromJson<SpiritProfiles>(json);
            profilesLoaded = profiles != null;
            Debug.Log("[LLMManager] Spirit profiles loaded successfully.");
        }
        catch (System.Exception e)
        {
            Debug.LogError($"[LLMManager] Failed to parse poe_spirits.json: {e.Message}");
        }
    }

    /// <summary>
    /// Loads spirit profiles synchronously (desktop only; other platforms wait for LoadSpiritData).
    /// </summary>
    private void LoadSpiritProfiles()
    {
        if (StreamingAssetsIsUrl) return;

        string jsonPath = Path.Combine(Application.streamingAssetsPath, "SpiritProfiles", "poe_spirits.json");
        if (File.Exists(jsonPath))
        {
            ApplyProfilesJson(File.ReadAllText(jsonPath));
        }
        else
        {
            Debug.LogError($"[LLMManager] Spirit profiles not found at: {jsonPath}");
        }
    }

    /// <summary>
    /// Strips Project Gutenberg boilerplate and truncates a story to the context budget.
    /// Placeholder files (as shipped in the repo) yield an empty excerpt.
    /// </summary>
    private string PrepareStoryExcerpt(string storyFile, string text)
    {
        if (text.TrimStart().StartsWith("[PLACEHOLDER"))
        {
            Debug.LogWarning($"[LLMManager] {storyFile} is still a placeholder; download the full text from Project Gutenberg (see the link inside the file).");
            return "";
        }

        // Keep only the story between Gutenberg's "*** START OF ..." and "*** END OF ..." markers
        int start = text.IndexOf("*** START OF", System.StringComparison.OrdinalIgnoreCase);
        if (start >= 0)
        {
            int lineEnd = text.IndexOf('\n', start);
            text = lineEnd >= 0 ? text.Substring(lineEnd + 1) : text;
        }
        int end = text.IndexOf("*** END OF", System.StringComparison.OrdinalIgnoreCase);
        if (end >= 0)
        {
            text = text.Substring(0, end);
        }

        text = text.Trim();
        return text.Substring(0, Mathf.Min(text.Length, maxContextLength));
    }

    /// <summary>
    /// Gets a spirit profile by key name.
    /// </summary>
    private SpiritProfile GetProfile(string spiritKey)
    {
        if (!profilesLoaded)
        {
            LoadSpiritProfiles();
        }

        return spiritKey switch
        {
            "Raven" => profiles?.Raven,
            "Narrator" => profiles?.Narrator,
            "Usher" => profiles?.Usher,
            _ => profiles?.Raven // Default to Raven
        };
    }

    /// <summary>
    /// Summons a spirit and initiates conversation.
    /// </summary>
    /// <param name="spiritKey">The spirit to summon (Raven, Narrator, Usher)</param>
    /// <param name="userMessage">What the player said; null when the spirit is summoned by a prop or zone</param>
    public void SummonSpirit(string spiritKey, string userMessage = null)
    {
        SpiritProfile profile = GetProfile(spiritKey);
        if (profile == null)
        {
            Debug.LogError($"[LLMManager] Spirit profile not found: {spiritKey}");
            if (UIChat.Instance != null)
            {
                UIChat.Instance.AppendSystem("*The spirits have not yet gathered... (spirit profiles not loaded)*");
            }
            return;
        }

        ActiveSpirit = spiritKey;
        ActiveStory = profile.story;

        Debug.Log($"[LLMManager] Summoning spirit: {spiritKey}");

        // Build context with story and system prompt
        string context = BuildContext(profile);

        // A summon without words (prop, trigger zone, debug key) opens with a greeting
        if (string.IsNullOrWhiteSpace(userMessage))
        {
            userMessage = "Who are you?";
        }

        // Start streaming response
        if (LLMStreamManager.Instance != null)
        {
            LLMStreamManager.Instance.StartStream(context, userMessage);
        }
        else
        {
            // Fallback to non-streaming
            StartCoroutine(SendChatRequest(context, userMessage));
        }
    }

    /// <summary>
    /// Builds the full context prompt for the LLM.
    /// </summary>
    private string BuildContext(SpiritProfile profile)
    {
        // Load story text
        string storyText = LoadStoryText(profile.story);

        // Load memory if available (truncated to last 3 exchanges to avoid context overflow)
        SpiritMemory memory = SpiritMemory.Load(ActiveSpirit);
        string memoryContext = "";
        if (memory != null && memory.totalInteractions > 0)
        {
            string summary = memory.GetContextSummary(3);
            if (!string.IsNullOrEmpty(summary))
            {
                memoryContext = "\n\nPrevious encounters: " + summary;
            }
        }

        // Build full prompt (the story section is omitted while the story file is a placeholder)
        string storyContext = string.IsNullOrEmpty(storyText) ? "" : $"Story context (excerpt):\n{storyText}\n";
        string fullPrompt = $"{profile.prompt}\n\n" +
                           storyContext +
                           $"{memoryContext}\n\n" +
                           "Respond in character, eerily and poetically. Keep responses under 100 words.";

        return fullPrompt;
    }

    /// <summary>
    /// Loads story text from cache or StreamingAssets.
    /// Uses cached version if available to avoid blocking I/O.
    /// </summary>
    private string LoadStoryText(string storyFile)
    {
        // Check cache first
        if (cachedStories.TryGetValue(storyFile, out string cachedText))
        {
            return cachedText;
        }

        // Fallback to synchronous load if not cached yet (desktop only; elsewhere the preload fills the cache)
        string storyPath = Path.Combine(Application.streamingAssetsPath, "PoeStories", storyFile);

        if (!StreamingAssetsIsUrl && File.Exists(storyPath))
        {
            string excerpt = PrepareStoryExcerpt(storyFile, File.ReadAllText(storyPath));

            // Cache for future use
            cachedStories[storyFile] = excerpt;

            return excerpt;
        }
        else
        {
            Debug.LogWarning($"[LLMManager] Story file not found: {storyPath}");
            return "The story fades from memory, yet the spirit remains...";
        }
    }

    /// <summary>
    /// Sends a chat request to the LLM (non-streaming fallback).
    /// </summary>
    private IEnumerator SendChatRequest(string systemPrompt, string userMessage)
    {
        string fullPrompt = $"{systemPrompt}\n\nUser: {userMessage}\n\nSpirit:";

        // Build request body based on backend
        string requestBody;
        if (backend == LLMBackend.Ollama)
        {
            requestBody = JsonUtility.ToJson(new OllamaRequest
            {
                model = ollamaModel,
                prompt = fullPrompt,
                stream = false,
                options = new OllamaOptions { temperature = temperature, num_predict = maxTokens }
            });
        }
        else
        {
            requestBody = JsonUtility.ToJson(new LLMRequest
            {
                prompt = fullPrompt,
                temperature = temperature,
                n_predict = maxTokens,
                stop = new string[] { "User:", "\nUser" }
            });
        }

        using (UnityEngine.Networking.UnityWebRequest request = new UnityEngine.Networking.UnityWebRequest(llmEndpoint, "POST"))
        {
            byte[] bodyRaw = System.Text.Encoding.UTF8.GetBytes(requestBody);
            request.uploadHandler = new UnityEngine.Networking.UploadHandlerRaw(bodyRaw);
            request.downloadHandler = new UnityEngine.Networking.DownloadHandlerBuffer();
            request.SetRequestHeader("Content-Type", "application/json");
            request.timeout = 60; // Add timeout

            yield return request.SendWebRequest();

            if (request.result == UnityEngine.Networking.UnityWebRequest.Result.Success)
            {
                string response = request.downloadHandler.text;
                string responseContent = ParseLLMResponse(response);

                if (UIChat.Instance != null)
                {
                    UIChat.Instance.AppendResponse(responseContent);
                }

                // Parse emotion and react
                string emotion = EmotionParser.Detect(responseContent);
                if (EventManager.Instance != null)
                {
                    EventManager.Instance.ReactToEmotion(emotion);
                }

                // Save to memory
                SaveToMemory(userMessage, responseContent);
            }
            else
            {
                Debug.LogError($"[LLMManager] LLM request failed: {request.error}");
                if (UIChat.Instance != null)
                {
                    UIChat.Instance.AppendResponse("*The spirit's voice fades into static...*");
                }
            }
        }
    }

    /// <summary>
    /// Safely parses LLM response with robust null checking.
    /// </summary>
    private string ParseLLMResponse(string response)
    {
        if (string.IsNullOrEmpty(response))
        {
            return "*The spirit speaks in tongues incomprehensible...*";
        }

        try
        {
            LLMResponse llmResponse = JsonUtility.FromJson<LLMResponse>(response);

            // Check if parsing succeeded and content exists
            if (llmResponse != null && !string.IsNullOrEmpty(llmResponse.content))
            {
                return llmResponse.content;
            }

            // Try alternate response format (some LLMs use "text" or "response")
            LLMResponseAlt altResponse = JsonUtility.FromJson<LLMResponseAlt>(response);
            if (altResponse != null)
            {
                if (!string.IsNullOrEmpty(altResponse.text))
                    return altResponse.text;
                if (!string.IsNullOrEmpty(altResponse.response))
                    return altResponse.response;
            }
        }
        catch (System.Exception e)
        {
            Debug.LogWarning($"[LLMManager] Failed to parse LLM response as JSON: {e.Message}");
        }

        // If response looks like plain text (not JSON), use it directly
        string trimmed = response.Trim();
        if (!trimmed.StartsWith("{") && !trimmed.StartsWith("["))
        {
            return trimmed;
        }

        return "*The spirit speaks in tongues incomprehensible...*";
    }

    /// <summary>
    /// Saves the conversation exchange to spirit memory.
    /// </summary>
    public void SaveToMemory(string userMessage, string spiritResponse)
    {
        if (string.IsNullOrEmpty(ActiveSpirit)) return;

        SpiritMemory memory = SpiritMemory.Load(ActiveSpirit);
        memory.AddExchange(userMessage, spiritResponse);
        SpiritMemory.Save(memory);
    }

    /// <summary>
    /// Gets a random spirit key for variety.
    /// </summary>
    public string GetRandomSpiritKey()
    {
        string[] spirits = { "Raven", "Narrator", "Usher" };
        return spirits[Random.Range(0, spirits.Length)];
    }

    private void OnApplicationQuit()
    {
        // Ensure memory is saved
        if (!string.IsNullOrEmpty(ActiveSpirit))
        {
            Debug.Log("[LLMManager] Saving spirit memory on quit...");
        }
    }

    // Request/Response structures for JSON serialization

    // llama.cpp format
    [System.Serializable]
    private class LLMRequest
    {
        public string prompt;
        public float temperature;
        public int n_predict;
        public string[] stop;
    }

    // Ollama format
    [System.Serializable]
    private class OllamaRequest
    {
        public string model;
        public string prompt;
        public bool stream;
        public OllamaOptions options;
    }

    [System.Serializable]
    private class OllamaOptions
    {
        public float temperature;
        public int num_predict;
    }

    [System.Serializable]
    private class LLMResponse
    {
        public string content;
    }

    // Ollama and alternate response formats
    [System.Serializable]
    private class LLMResponseAlt
    {
        public string text;
        public string response; // Ollama uses "response" field
    }

    /// <summary>
    /// Gets the configured backend type.
    /// </summary>
    public LLMBackend Backend => backend;

    /// <summary>
    /// Gets the configured Ollama model name.
    /// </summary>
    public string OllamaModel => ollamaModel;

    /// <summary>
    /// Gets the configured LLM endpoint URL.
    /// </summary>
    public string Endpoint => llmEndpoint;

}
