// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M15 - Procedural Ambient Composer

using UnityEngine;

/// <summary>
/// Controls layered ambient audio that evolves with spook level.
/// Manages multiple audio layers (drone, ticks, whispers) that blend dynamically.
/// </summary>
public class AmbienceController : SceneSingletonBase<AmbienceController>
{
    [System.Serializable]
    public class AmbienceLayer
    {
        public string name;
        public AudioSource source;
        public AudioClip clip;
        [Range(0f, 1f)] public float baseVolume = 0.5f;
        [Range(0f, 1f)] public float maxVolume = 1f;
        public int activationSpookLevel = 0;
        public bool useLowPassFilter = false;
        public float baseLowPassCutoff = 22000f;
        public float minLowPassCutoff = 1000f;
    }

    [Header("Ambient Layers")]
    [SerializeField] private AmbienceLayer[] layers;

    [Header("Global Settings")]
    [SerializeField] private float fadeSpeed = 2f;
    [SerializeField] private float masterVolume = 1f;

    [Header("Random Events")]
    [SerializeField] private bool enableRandomEvents = true;
    [SerializeField] private float minEventInterval = 10f;
    [SerializeField] private float maxEventInterval = 30f;
    [SerializeField] private AudioClip[] randomEventClips;
    [SerializeField] private AudioSource eventSource;

    // State
    private int currentSpookLevel = 0;
    private float[] targetVolumes;
    private float nextEventTime;

    private void Start()
    {
        InitializeLayers();

        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged += OnSpookLevelChanged;
        }

        ScheduleNextEvent();
    }

    /// <summary>
    /// Initializes all ambient layers.
    /// </summary>
    private void InitializeLayers()
    {
        if (layers == null) return;

        targetVolumes = new float[layers.Length];

        for (int i = 0; i < layers.Length; i++)
        {
            AmbienceLayer layer = layers[i];

            if (layer.source == null)
            {
                GameObject sourceObj = new GameObject($"AmbienceLayer_{layer.name}");
                sourceObj.transform.SetParent(transform);
                layer.source = sourceObj.AddComponent<AudioSource>();
            }

            layer.source.clip = layer.clip;
            layer.source.loop = true;
            layer.source.playOnAwake = false;
            layer.source.volume = 0f;
            layer.source.spatialBlend = 0f;

            if (layer.useLowPassFilter)
            {
                AudioLowPassFilter filter = layer.source.gameObject.AddComponent<AudioLowPassFilter>();
                filter.cutoffFrequency = layer.baseLowPassCutoff;
            }

            // Start playing if active at level 0
            if (layer.activationSpookLevel == 0)
            {
                layer.source.Play();
                targetVolumes[i] = layer.baseVolume;
            }
        }
    }

    private void Update()
    {
        UpdateLayerVolumes();
        UpdateRandomEvents();
    }

    /// <summary>
    /// Smoothly transitions layer volumes.
    /// </summary>
    private void UpdateLayerVolumes()
    {
        if (layers == null) return;

        for (int i = 0; i < layers.Length; i++)
        {
            AmbienceLayer layer = layers[i];
            if (layer.source == null) continue;

            float current = layer.source.volume;
            float target = targetVolumes[i] * masterVolume;

            layer.source.volume = Mathf.Lerp(current, target, fadeSpeed * Time.deltaTime);

            // Update low pass filter based on spook level
            if (layer.useLowPassFilter)
            {
                AudioLowPassFilter filter = layer.source.GetComponent<AudioLowPassFilter>();
                if (filter != null)
                {
                    float t = (float)currentSpookLevel / 5f;
                    filter.cutoffFrequency = Mathf.Lerp(layer.baseLowPassCutoff, layer.minLowPassCutoff, t);
                }
            }
        }
    }

    /// <summary>
    /// Handles random ambient events (creaks, distant sounds, etc).
    /// </summary>
    private void UpdateRandomEvents()
    {
        if (!enableRandomEvents) return;
        if (randomEventClips == null || randomEventClips.Length == 0) return;

        if (Time.time >= nextEventTime)
        {
            PlayRandomEvent();
            ScheduleNextEvent();
        }
    }

    private void ScheduleNextEvent()
    {
        // Events more frequent at higher spook levels
        float intervalMultiplier = 1f - (currentSpookLevel * 0.1f);
        float interval = Random.Range(minEventInterval, maxEventInterval) * intervalMultiplier;
        nextEventTime = Time.time + interval;
    }

    private void PlayRandomEvent()
    {
        if (eventSource == null || randomEventClips.Length == 0) return;

        AudioClip clip = randomEventClips[Random.Range(0, randomEventClips.Length)];
        if (clip == null) return;

        float volume = 0.3f + (currentSpookLevel * 0.1f);
        float pitch = Random.Range(0.8f, 1.2f);
        float pan = Random.Range(-0.5f, 0.5f);

        eventSource.pitch = pitch;
        eventSource.panStereo = pan;
        eventSource.PlayOneShot(clip, volume);

        Debug.Log($"[AmbienceController] Random event: {clip.name}");
    }

    /// <summary>
    /// Called when spook level changes.
    /// </summary>
    private void OnSpookLevelChanged(int level)
    {
        currentSpookLevel = level;
        UpdateTargetVolumes();
    }

    /// <summary>
    /// Updates target volumes based on spook level.
    /// </summary>
    private void UpdateTargetVolumes()
    {
        if (layers == null) return;

        for (int i = 0; i < layers.Length; i++)
        {
            AmbienceLayer layer = layers[i];

            if (currentSpookLevel >= layer.activationSpookLevel)
            {
                // Activate layer
                if (!layer.source.isPlaying)
                {
                    layer.source.Play();
                }

                // Scale volume with spook level
                float t = (float)(currentSpookLevel - layer.activationSpookLevel) / 5f;
                targetVolumes[i] = Mathf.Lerp(layer.baseVolume, layer.maxVolume, t);
            }
            else
            {
                // Deactivate layer
                targetVolumes[i] = 0f;
            }
        }
    }

    /// <summary>
    /// Triggers a momentary audio dropout (silence for impact).
    /// </summary>
    public void TriggerDropout(float duration = 0.5f)
    {
        StartCoroutine(DropoutCoroutine(duration));
    }

    private System.Collections.IEnumerator DropoutCoroutine(float duration)
    {
        float originalMaster = masterVolume;
        masterVolume = 0f;

        yield return new WaitForSeconds(duration);

        masterVolume = originalMaster;
    }

    /// <summary>
    /// Sets master volume.
    /// </summary>
    public void SetMasterVolume(float volume)
    {
        masterVolume = Mathf.Clamp01(volume);
    }

    /// <summary>
    /// Fades all ambience out.
    /// </summary>
    public void FadeOut(float duration)
    {
        StartCoroutine(FadeOutCoroutine(duration));
    }

    private System.Collections.IEnumerator FadeOutCoroutine(float duration)
    {
        float startVolume = masterVolume;
        float elapsed = 0f;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            masterVolume = Mathf.Lerp(startVolume, 0f, elapsed / duration);
            yield return null;
        }

        masterVolume = 0f;
    }

    protected override void OnDestroy()
    {
        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged -= OnSpookLevelChanged;
        }
        base.OnDestroy();
    }
}
