// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M5 - Spook Effects

using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Creates a heartbeat audio-visual effect that intensifies with spook level.
/// Combines audio pulse with screen vignette pulse.
/// </summary>
public class HeartbeatEffect : MonoBehaviour
{
    public static HeartbeatEffect Instance { get; private set; }

    [Header("Audio")]
    [SerializeField] private AudioSource heartbeatSource;
    [SerializeField] private AudioClip heartbeatClip;
    [SerializeField] private float baseVolume = 0.3f;
    [SerializeField] private float maxVolume = 1f;

    [Header("Timing")]
    [SerializeField] private float baseBPM = 60f;
    [SerializeField] private float maxBPM = 140f;
    [SerializeField] private float bpmPerSpookLevel = 15f;

    [Header("Visual Pulse")]
    [SerializeField] private bool useVisualPulse = true;
    [SerializeField] private Image vignetteOverlay;
    [SerializeField] private float pulseIntensity = 0.2f;
    [SerializeField] private Color pulseColor = new Color(0.3f, 0f, 0f, 0.3f);

    [Header("Activation")]
    [SerializeField] private int activationSpookLevel = 2;
    [SerializeField] private bool alwaysActive = false;

    // State
    private bool isActive = false;
    private float currentBPM;
    private float beatTimer = 0f;
    private float beatInterval;
    private int currentSpookLevel = 0;

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }
        else
        {
            Destroy(gameObject);
            return;
        }
    }

    private void Start()
    {
        // Setup audio source
        if (heartbeatSource == null)
        {
            heartbeatSource = gameObject.AddComponent<AudioSource>();
        }
        heartbeatSource.clip = heartbeatClip;
        heartbeatSource.loop = false;
        heartbeatSource.playOnAwake = false;
        heartbeatSource.volume = baseVolume;

        // Setup vignette
        if (vignetteOverlay != null)
        {
            vignetteOverlay.color = Color.clear;
        }

        currentBPM = baseBPM;
        beatInterval = 60f / currentBPM;

        // Subscribe to events
        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged += OnSpookLevelChanged;
        }

        if (alwaysActive)
        {
            Activate();
        }
    }

    private void Update()
    {
        if (!isActive) return;

        beatTimer += Time.deltaTime;

        if (beatTimer >= beatInterval)
        {
            beatTimer = 0f;
            TriggerBeat();
        }

        // Update visual pulse decay
        if (useVisualPulse && vignetteOverlay != null)
        {
            Color current = vignetteOverlay.color;
            current.a = Mathf.Lerp(current.a, 0f, 5f * Time.deltaTime);
            vignetteOverlay.color = current;
        }
    }

    /// <summary>
    /// Triggers a single heartbeat.
    /// </summary>
    private void TriggerBeat()
    {
        // Play sound
        if (heartbeatSource != null && heartbeatClip != null)
        {
            heartbeatSource.pitch = 0.9f + (currentSpookLevel * 0.05f);
            heartbeatSource.PlayOneShot(heartbeatClip);
        }

        // Visual pulse
        if (useVisualPulse && vignetteOverlay != null)
        {
            float intensity = pulseIntensity * (1f + currentSpookLevel * 0.2f);
            Color pulse = pulseColor;
            pulse.a = intensity;
            vignetteOverlay.color = pulse;
        }

        // Camera shake on high BPM
        if (currentBPM > 100f && CameraShake.Instance != null)
        {
            CameraShake.Instance.AddTrauma(0.05f);
        }
    }

    /// <summary>
    /// Called when spook level changes.
    /// </summary>
    private void OnSpookLevelChanged(int level)
    {
        currentSpookLevel = level;

        // Activate at threshold
        if (level >= activationSpookLevel && !isActive)
        {
            Activate();
        }
        else if (level < activationSpookLevel && isActive && !alwaysActive)
        {
            Deactivate();
        }

        // Update BPM and volume
        if (isActive)
        {
            UpdateHeartbeatParams();
        }
    }

    /// <summary>
    /// Updates heartbeat parameters based on spook level.
    /// </summary>
    private void UpdateHeartbeatParams()
    {
        // Calculate BPM
        currentBPM = baseBPM + (currentSpookLevel * bpmPerSpookLevel);
        currentBPM = Mathf.Clamp(currentBPM, baseBPM, maxBPM);
        beatInterval = 60f / currentBPM;

        // Calculate volume
        float volumeT = (float)currentSpookLevel / 5f;
        heartbeatSource.volume = Mathf.Lerp(baseVolume, maxVolume, volumeT);

        Debug.Log($"[HeartbeatEffect] BPM: {currentBPM}, Volume: {heartbeatSource.volume}");
    }

    /// <summary>
    /// Activates the heartbeat effect.
    /// </summary>
    public void Activate()
    {
        if (isActive) return;

        isActive = true;
        beatTimer = 0f;
        UpdateHeartbeatParams();
        Debug.Log("[HeartbeatEffect] Activated");
    }

    /// <summary>
    /// Deactivates the heartbeat effect.
    /// </summary>
    public void Deactivate()
    {
        isActive = false;

        if (vignetteOverlay != null)
        {
            vignetteOverlay.color = Color.clear;
        }

        Debug.Log("[HeartbeatEffect] Deactivated");
    }

    /// <summary>
    /// Forces a heartbeat (for scripted moments).
    /// </summary>
    public void ForceBeat()
    {
        TriggerBeat();
    }

    /// <summary>
    /// Sets the BPM directly (for scripted sequences).
    /// </summary>
    public void SetBPM(float bpm)
    {
        currentBPM = Mathf.Clamp(bpm, 40f, 200f);
        beatInterval = 60f / currentBPM;
    }

    /// <summary>
    /// Gets whether the heartbeat is active.
    /// </summary>
    public bool IsActive() => isActive;

    /// <summary>
    /// Gets current BPM.
    /// </summary>
    public float GetCurrentBPM() => currentBPM;

    private void OnDestroy()
    {
        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged -= OnSpookLevelChanged;
        }
    }
}
