// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M13

using UnityEngine;

/// <summary>
/// Controls the portal distortion shader properties based on emotion and spook level.
/// Attach to objects with portal distortion material (mirror, crystal ball rim, etc).
/// </summary>
public class PortalDistort : SceneSingletonBase<PortalDistort>
{
    [Header("Material Reference")]
    [SerializeField] private Material portalMaterial;

    [Header("Shader Properties")]
    [SerializeField] private string distortionProperty = "_DistortionStrength";
    [SerializeField] private string hueShiftProperty = "_HueShift";
    [SerializeField] private string pulseRateProperty = "_PulseRate";
    [SerializeField] private string emissionProperty = "_EmissionIntensity";

    [Header("Base Values")]
    [SerializeField] private float baseDistortion = 0.5f;
    [SerializeField] private float baseHueShift = 0f;
    [SerializeField] private float basePulseRate = 1f;
    [SerializeField] private float baseEmission = 0.5f;

    [Header("Emotion Multipliers")]
    [SerializeField] private float terrorDistortion = 2f;
    [SerializeField] private float uneaseDistortion = 1f;
    [SerializeField] private float neutralDistortion = 0.5f;

    [Header("Animation")]
    [SerializeField] private float transitionSpeed = 3f;

    // Current state
    private float targetDistortion;
    private float targetHueShift;
    private float currentDistortion;
    private float currentHueShift;
    private string currentEmotion = EmotionParser.NEUTRAL;

    private void Start()
    {
        // Get material from renderer if not assigned
        if (portalMaterial == null)
        {
            Renderer rend = GetComponent<Renderer>();
            if (rend != null)
            {
                portalMaterial = rend.material;
            }
        }

        if (portalMaterial == null)
        {
            Debug.LogWarning("[PortalDistort] No material assigned!");
            return;
        }

        // Initialize values
        targetDistortion = baseDistortion;
        targetHueShift = baseHueShift;
        currentDistortion = baseDistortion;
        currentHueShift = baseHueShift;

        ApplyMaterialValues();
    }

    private void Update()
    {
        // Smooth transition to target values
        currentDistortion = Mathf.Lerp(currentDistortion, targetDistortion, transitionSpeed * Time.deltaTime);
        currentHueShift = Mathf.Lerp(currentHueShift, targetHueShift, transitionSpeed * Time.deltaTime);

        // Add subtle animation
        float animatedDistortion = currentDistortion + Mathf.Sin(Time.time * basePulseRate) * 0.1f;
        float animatedHue = currentHueShift + Mathf.Sin(Time.time * 0.5f) * 0.05f;

        ApplyMaterialValues(animatedDistortion, animatedHue);
    }

    /// <summary>
    /// Sets the distortion based on detected emotion.
    /// </summary>
    /// <param name="emotion">The emotion category</param>
    public void SetEmotion(string emotion)
    {
        currentEmotion = emotion;

        switch (emotion)
        {
            case EmotionParser.TERROR:
                targetDistortion = terrorDistortion;
                targetHueShift = Random.Range(-0.2f, 0.3f);
                break;

            case EmotionParser.UNEASE:
                targetDistortion = uneaseDistortion;
                targetHueShift = Random.Range(-0.1f, 0.1f);
                break;

            case EmotionParser.NEUTRAL:
            default:
                targetDistortion = neutralDistortion;
                targetHueShift = 0f;
                break;
        }

        Debug.Log($"[PortalDistort] Emotion set: {emotion}, Distortion: {targetDistortion}");
    }

    /// <summary>
    /// Sets distortion based on spook level.
    /// </summary>
    /// <param name="level">Spook level (0-5)</param>
    public void SetSpookLevel(int level)
    {
        float t = (float)level / 5f;
        targetDistortion = Mathf.Lerp(baseDistortion, terrorDistortion, t);

        // Increase pulse rate with level
        if (portalMaterial != null && portalMaterial.HasProperty(pulseRateProperty))
        {
            portalMaterial.SetFloat(pulseRateProperty, basePulseRate + (level * 0.5f));
        }

        // Increase emission with level
        if (portalMaterial != null && portalMaterial.HasProperty(emissionProperty))
        {
            portalMaterial.SetFloat(emissionProperty, baseEmission + (level * 0.2f));
        }
    }

    /// <summary>
    /// Triggers a brief distortion spike.
    /// </summary>
    /// <param name="intensity">Spike intensity</param>
    /// <param name="duration">Spike duration</param>
    public void TriggerSpike(float intensity = 2f, float duration = 0.3f)
    {
        StartCoroutine(SpikeCoroutine(intensity, duration));
    }

    private System.Collections.IEnumerator SpikeCoroutine(float intensity, float duration)
    {
        float originalTarget = targetDistortion;
        targetDistortion = intensity;

        yield return new WaitForSeconds(duration);

        targetDistortion = originalTarget;
    }

    /// <summary>
    /// Applies current values to the material.
    /// </summary>
    private void ApplyMaterialValues()
    {
        ApplyMaterialValues(currentDistortion, currentHueShift);
    }

    private void ApplyMaterialValues(float distortion, float hueShift)
    {
        if (portalMaterial == null) return;

        if (portalMaterial.HasProperty(distortionProperty))
        {
            portalMaterial.SetFloat(distortionProperty, distortion);
        }

        if (portalMaterial.HasProperty(hueShiftProperty))
        {
            portalMaterial.SetFloat(hueShiftProperty, hueShift);
        }
    }

    /// <summary>
    /// Gets the current distortion value.
    /// </summary>
    public float GetDistortion()
    {
        return currentDistortion;
    }

    /// <summary>
    /// Gets the current emotion.
    /// </summary>
    public string GetCurrentEmotion()
    {
        return currentEmotion;
    }

    /// <summary>
    /// Resets to base values.
    /// </summary>
    public void Reset()
    {
        targetDistortion = baseDistortion;
        targetHueShift = baseHueShift;
        currentEmotion = EmotionParser.NEUTRAL;
    }

}
