// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M6

using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

/// <summary>
/// Controls URP post-processing effects based on spook level.
/// Manages vignette, color adjustments, chromatic aberration, and lens distortion.
/// </summary>
public class PostFXController : SingletonBase<PostFXController>
{

    [Header("Volume Reference")]
    [SerializeField] private Volume volume;

    [Header("Vignette Settings")]
    [SerializeField] private float vignetteMin = 0.1f;
    [SerializeField] private float vignetteMax = 0.6f;

    [Header("Color Settings")]
    [SerializeField] private float saturationMin = -50f;
    [SerializeField] private float saturationMax = -100f;
    [SerializeField] private float contrastMin = 0f;
    [SerializeField] private float contrastMax = 20f;

    [Header("Effect Thresholds")]
    [SerializeField] private int chromaticAberrationLevel = 3; // Enable at this level
    [SerializeField] private int lensDistortionLevel = 4; // Enable at this level

    [Header("Lens Distortion Settings")]
    [SerializeField] private float lensDistortionIntensity = -0.3f;

    // Post-processing components
    private Vignette vignette;
    private ColorAdjustments colorAdjustments;
    private ChromaticAberration chromaticAberration;
    private LensDistortion lensDistortion;
    private Bloom bloom;
    private Coroutine pulseCoroutine;
    private Coroutine glitchCoroutine;

    // Initialization state
    private bool initialized = false;
    private int currentLevel = 0;

    private void Start()
    {
        Initialize();
    }

    /// <summary>
    /// Initializes post-processing components from the volume profile.
    /// </summary>
    private void Initialize()
    {
        if (volume == null)
        {
            // Try to find volume in scene
            volume = FindFirstObjectByType<Volume>();
            if (volume == null)
            {
                Debug.LogError("[PostFXController] No Volume found! Post-processing effects disabled.");
                return;
            }
        }

        if (volume.sharedProfile == null)
        {
            Debug.LogWarning("[PostFXController] Volume has no profile asset; using a runtime profile.");
        }

        // volume.profile is this Volume's own runtime copy (never null), so editing it is safe
        VolumeProfile profile = volume.profile;

        // Get the components, adding any the profile lacks so every effect works
        if (!profile.TryGet(out vignette)) vignette = profile.Add<Vignette>();
        if (!profile.TryGet(out colorAdjustments)) colorAdjustments = profile.Add<ColorAdjustments>();
        if (!profile.TryGet(out chromaticAberration)) chromaticAberration = profile.Add<ChromaticAberration>();
        if (!profile.TryGet(out lensDistortion)) lensDistortion = profile.Add<LensDistortion>();
        profile.TryGet(out bloom);

        initialized = true;
        Debug.Log("[PostFXController] Initialized successfully.");

        // Apply initial level
        SetLevel(0);
    }

    /// <summary>
    /// Sets post-processing effects based on spook level.
    /// </summary>
    /// <param name="level">Spook level (0-5)</param>
    public void SetLevel(int level)
    {
        // Re-bind when the Volume we used was destroyed by a scene change
        if (!initialized || volume == null)
        {
            initialized = false;
            volume = null;
            Initialize();
            if (!initialized) return;
        }

        currentLevel = level;
        float t = (float)level / 5f; // Normalized 0-1

        // Vignette: Increase intensity with level
        if (vignette != null)
        {
            vignette.intensity.Override(Mathf.Lerp(vignetteMin, vignetteMax, t));
        }

        // Color Adjustments: Desaturate and increase contrast
        if (colorAdjustments != null)
        {
            colorAdjustments.saturation.Override(Mathf.Lerp(saturationMin, saturationMax, t));
            colorAdjustments.contrast.Override(Mathf.Lerp(contrastMin, contrastMax, t));

            // Add red tint at max level
            if (level >= 5)
            {
                colorAdjustments.colorFilter.Override(new Color(1f, 0.8f, 0.8f));
            }
            else
            {
                colorAdjustments.colorFilter.Override(Color.white);
            }
        }

        // Chromatic Aberration: Enable at threshold level
        if (chromaticAberration != null)
        {
            chromaticAberration.active = level >= chromaticAberrationLevel;
            if (chromaticAberration.active)
            {
                float chromaIntensity = (level - chromaticAberrationLevel + 1) * 0.3f;
                chromaticAberration.intensity.Override(Mathf.Clamp(chromaIntensity, 0f, 1f));
            }
        }

        // Lens Distortion: Enable at threshold level
        if (lensDistortion != null)
        {
            lensDistortion.active = level >= lensDistortionLevel;
            if (lensDistortion.active)
            {
                float distortIntensity = (level - lensDistortionLevel + 1) * lensDistortionIntensity;
                lensDistortion.intensity.Override(distortIntensity);
            }
        }

        Debug.Log($"[PostFXController] Level set to {level} (t={t:F2})");
    }

    /// <summary>
    /// Pulses the vignette for dramatic effect.
    /// </summary>
    /// <param name="intensity">Pulse intensity (0-1)</param>
    /// <param name="duration">Pulse duration</param>
    public void PulseVignette(float intensity, float duration)
    {
        if (vignette != null)
        {
            // One pulse at a time; a second one would capture a mid-pulse value as its rest value
            if (pulseCoroutine != null)
            {
                StopCoroutine(pulseCoroutine);
            }
            pulseCoroutine = StartCoroutine(PulseVignetteCoroutine(intensity, duration));
        }
    }

    private System.Collections.IEnumerator PulseVignetteCoroutine(float targetIntensity, float duration)
    {
        float halfDuration = duration / 2f;

        // Pulse up (from the current level's resting vignette, so level changes mid-pulse are honoured)
        float elapsed = 0f;
        while (elapsed < halfDuration)
        {
            elapsed += Time.deltaTime;
            vignette.intensity.Override(Mathf.Lerp(RestingVignette(), targetIntensity, elapsed / halfDuration));
            yield return null;
        }

        // Pulse down
        elapsed = 0f;
        while (elapsed < halfDuration)
        {
            elapsed += Time.deltaTime;
            vignette.intensity.Override(Mathf.Lerp(targetIntensity, RestingVignette(), elapsed / halfDuration));
            yield return null;
        }

        vignette.intensity.Override(RestingVignette());
        pulseCoroutine = null;
    }

    private float RestingVignette()
    {
        return Mathf.Lerp(vignetteMin, vignetteMax, currentLevel / 5f);
    }

    /// <summary>
    /// Triggers a glitch effect (for mirror interactions).
    /// </summary>
    public void TriggerGlitch(float duration = 0.5f)
    {
        if (!initialized) return;

        if (glitchCoroutine != null)
        {
            StopCoroutine(glitchCoroutine);
        }
        glitchCoroutine = StartCoroutine(GlitchCoroutine(duration));
    }

    private System.Collections.IEnumerator GlitchCoroutine(float duration)
    {
        // Enable chromatic aberration and lens distortion temporarily
        if (chromaticAberration != null)
        {
            chromaticAberration.active = true;
            chromaticAberration.intensity.Override(1f);
        }
        if (lensDistortion != null)
        {
            lensDistortion.active = true;
            lensDistortion.intensity.Override(-0.5f);
        }

        yield return new WaitForSeconds(duration);

        // Restore the effects for the current level (it may have changed during the glitch)
        glitchCoroutine = null;
        SetLevel(currentLevel);
    }

    /// <summary>
    /// Resets all post-processing to baseline.
    /// </summary>
    public void ResetEffects()
    {
        SetLevel(0);
        Debug.Log("[PostFXController] Effects reset to baseline");
    }

    /// <summary>
    /// Gets the current spook level being applied.
    /// </summary>
    public int GetCurrentLevel()
    {
        return currentLevel;
    }

}
