// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M5

using UnityEngine;

/// <summary>
/// Manages visual effects including fog, particles, and ghost manifestations.
/// Coordinates with EventManager for spook-level-based VFX changes.
/// </summary>
public class VFXManager : MonoBehaviour
{
    public static VFXManager Instance { get; private set; }

    [Header("Particle Systems")]
    [SerializeField] private ParticleSystem fogParticles;
    [SerializeField] private ParticleSystem ghostParticles;
    [SerializeField] private ParticleSystem portalBurstParticles;
    [SerializeField] private ParticleSystem orbGlowParticles;

    [Header("Fog Settings")]
    [SerializeField] private float baseFogDensity = 0.01f;
    [SerializeField] private float fogDensityPerLevel = 0.04f;
    [SerializeField] private Color baseFogColor = new Color(0.1f, 0.05f, 0.15f); // Dark purple
    [SerializeField] private Color maxFogColor = new Color(0.3f, 0.05f, 0.05f); // Dark red

    [Header("Particle Settings")]
    [SerializeField] private int baseFogParticleCount = 10;
    [SerializeField] private int fogParticlesPerLevel = 20;
    [SerializeField] private int ghostEmitCount = 5;
    [SerializeField] private int portalBurstCount = 50;

    // Current state
    private int currentLevel = 0;

    private void Awake()
    {
        // Singleton pattern with persistence
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
            return;
        }
    }

    private void Start()
    {
        // Initialize fog settings
        if (RenderSettings.fog == false)
        {
            RenderSettings.fog = true;
        }
        RenderSettings.fogMode = FogMode.ExponentialSquared;
        RenderSettings.fogDensity = baseFogDensity;
        RenderSettings.fogColor = baseFogColor;

        // Apply initial level
        UpdateFog(0);
    }

    /// <summary>
    /// Updates fog density and particle emission based on spook level.
    /// </summary>
    /// <param name="level">Spook level (0-5)</param>
    public void UpdateFog(int level)
    {
        currentLevel = level;

        // Update Unity fog settings
        float targetDensity = baseFogDensity + (level * fogDensityPerLevel);
        RenderSettings.fogDensity = targetDensity;

        // Lerp fog color from base to red at max level
        float t = (float)level / 5f;
        RenderSettings.fogColor = Color.Lerp(baseFogColor, maxFogColor, t);

        // Update fog particle system
        if (fogParticles != null)
        {
            var emission = fogParticles.emission;
            emission.rateOverTime = baseFogParticleCount + (level * fogParticlesPerLevel);

            var main = fogParticles.main;
            main.startColor = RenderSettings.fogColor;

            if (!fogParticles.isPlaying)
            {
                fogParticles.Play();
            }
        }

        Debug.Log($"[VFXManager] Fog updated - Level: {level}, Density: {targetDensity:F3}");
    }

    /// <summary>
    /// Sets fog density directly (for fine-tuned control).
    /// </summary>
    /// <param name="density">Fog density value</param>
    public void SetFogDensity(float density)
    {
        RenderSettings.fogDensity = Mathf.Clamp(density, 0f, 0.5f);
    }

    /// <summary>
    /// Adds a temporary fog burst for dramatic effect.
    /// </summary>
    /// <param name="additionalDensity">Additional density to add</param>
    public void AddFogBurst(float additionalDensity)
    {
        StartCoroutine(FogBurstCoroutine(additionalDensity, 2f));
    }

    private System.Collections.IEnumerator FogBurstCoroutine(float additionalDensity, float duration)
    {
        float originalDensity = RenderSettings.fogDensity;
        RenderSettings.fogDensity += additionalDensity;

        yield return new WaitForSeconds(duration);

        // Lerp back to original
        float elapsed = 0f;
        float lerpDuration = 1f;
        float burstDensity = RenderSettings.fogDensity;

        while (elapsed < lerpDuration)
        {
            elapsed += Time.deltaTime;
            RenderSettings.fogDensity = Mathf.Lerp(burstDensity, originalDensity, elapsed / lerpDuration);
            yield return null;
        }
    }

    /// <summary>
    /// Enables ghost particle emission (phantom silhouettes).
    /// </summary>
    public void EnableGhosts()
    {
        if (ghostParticles != null)
        {
            ghostParticles.Emit(ghostEmitCount);
            Debug.Log($"[VFXManager] Ghost particles emitted: {ghostEmitCount}");
        }
        else
        {
            Debug.LogWarning("[VFXManager] Ghost particle system not assigned!");
        }
    }

    /// <summary>
    /// Triggers the portal burst effect (dimension breach).
    /// </summary>
    public void TriggerPortal()
    {
        if (portalBurstParticles != null)
        {
            portalBurstParticles.Emit(portalBurstCount);
            Debug.Log($"[VFXManager] Portal burst triggered: {portalBurstCount} particles");
        }

        // Also trigger maximum fog
        RenderSettings.fogDensity = 0.3f;
        RenderSettings.fogColor = maxFogColor;
    }

    /// <summary>
    /// Enables the orb glow effect (crystal ball activation).
    /// </summary>
    public void EnableOrbGlow()
    {
        if (orbGlowParticles != null)
        {
            if (!orbGlowParticles.isPlaying)
            {
                orbGlowParticles.Play();
            }
            Debug.Log("[VFXManager] Orb glow enabled");
        }
    }

    /// <summary>
    /// Disables the orb glow effect.
    /// </summary>
    public void DisableOrbGlow()
    {
        if (orbGlowParticles != null)
        {
            orbGlowParticles.Stop();
        }
    }

    /// <summary>
    /// Gets the current fog density.
    /// </summary>
    public float GetCurrentFogDensity()
    {
        return RenderSettings.fogDensity;
    }

    /// <summary>
    /// Resets all VFX to baseline state.
    /// </summary>
    public void ResetVFX()
    {
        UpdateFog(0);
        DisableOrbGlow();

        if (ghostParticles != null)
        {
            ghostParticles.Clear();
        }

        Debug.Log("[VFXManager] VFX reset to baseline");
    }

    /// <summary>
    /// Fades fog to zero over duration (for scene transitions).
    /// </summary>
    public void FadeOutFog(float duration)
    {
        StartCoroutine(FadeOutFogCoroutine(duration));
    }

    private System.Collections.IEnumerator FadeOutFogCoroutine(float duration)
    {
        float startDensity = RenderSettings.fogDensity;
        float elapsed = 0f;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            RenderSettings.fogDensity = Mathf.Lerp(startDensity, 0f, elapsed / duration);
            yield return null;
        }
    }

    private void OnDestroy()
    {
        // Reset fog on destroy
        if (Instance == this)
        {
            RenderSettings.fogDensity = baseFogDensity;
            RenderSettings.fogColor = baseFogColor;
        }
    }
}
