// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M1 - Player Systems

using UnityEngine;

/// <summary>
/// Manages cursor visibility and lock state.
/// Centralizes cursor control to prevent conflicts between systems.
/// </summary>
public class CursorManager : MonoBehaviour
{
    public static CursorManager Instance { get; private set; }

    [Header("Settings")]
    [SerializeField] private bool startLocked = true;

    // State tracking
    private bool isCursorLocked = false;
    private int lockRequestCount = 0;

    private void Awake()
    {
        // Singleton with persistence
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
            return;
        }
    }

    private void Start()
    {
        if (startLocked)
        {
            LockCursor();
        }
        else
        {
            UnlockCursor();
        }
    }

    private void Update()
    {
        // Emergency unlock with Alt key (for development)
        if (Input.GetKeyDown(KeyCode.LeftAlt) || Input.GetKeyDown(KeyCode.RightAlt))
        {
            ToggleCursor();
        }
    }

    /// <summary>
    /// Locks the cursor (invisible, confined to center).
    /// </summary>
    public void LockCursor()
    {
        isCursorLocked = true;
        ApplyCursorState();
        Debug.Log("[CursorManager] Cursor locked");
    }

    /// <summary>
    /// Unlocks the cursor (visible, free movement).
    /// </summary>
    public void UnlockCursor()
    {
        isCursorLocked = false;
        ApplyCursorState();
        Debug.Log("[CursorManager] Cursor unlocked");
    }

    /// <summary>
    /// Toggles cursor lock state.
    /// </summary>
    public void ToggleCursor()
    {
        if (isCursorLocked)
        {
            UnlockCursor();
        }
        else
        {
            LockCursor();
        }
    }

    /// <summary>
    /// Requests cursor unlock (increments request counter).
    /// Used by UI systems that need cursor control.
    /// </summary>
    public void RequestUnlock()
    {
        lockRequestCount++;
        if (lockRequestCount > 0)
        {
            UnlockCursor();
        }
    }

    /// <summary>
    /// Releases cursor unlock request (decrements counter).
    /// Relocks when all requests released.
    /// </summary>
    public void ReleaseUnlock()
    {
        lockRequestCount--;
        lockRequestCount = Mathf.Max(0, lockRequestCount);

        if (lockRequestCount == 0)
        {
            LockCursor();
        }
    }

    /// <summary>
    /// Applies the cursor state to Unity.
    /// </summary>
    private void ApplyCursorState()
    {
        if (isCursorLocked)
        {
            Cursor.visible = false;
            Cursor.lockState = CursorLockMode.Locked;
        }
        else
        {
            Cursor.visible = true;
            Cursor.lockState = CursorLockMode.None;
        }
    }

    /// <summary>
    /// Checks if cursor is currently locked.
    /// </summary>
    public bool IsCursorLocked()
    {
        return isCursorLocked;
    }

    /// <summary>
    /// Forces cursor state refresh.
    /// </summary>
    public void RefreshCursorState()
    {
        ApplyCursorState();
    }

    private void OnApplicationFocus(bool hasFocus)
    {
        // Reapply cursor state when window regains focus
        if (hasFocus)
        {
            ApplyCursorState();
        }
    }
}
