// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M1 - Player Systems

using UnityEngine;

/// <summary>
/// First-person player controller for the Cursed Portal.
/// Handles WASD movement with smooth acceleration and deceleration.
/// </summary>
[RequireComponent(typeof(CharacterController))]
public class FirstPersonController : SceneSingletonBase<FirstPersonController>
{
    [Header("Movement Settings")]
    [SerializeField] private float walkSpeed = 4f;
    [SerializeField] private float sprintSpeed = 7f;
    [SerializeField] private float acceleration = 10f;
    [SerializeField] private float deceleration = 10f;

    [Header("Gravity")]
    [SerializeField] private float gravity = -9.81f;

    [Header("Input Keys")]
    [SerializeField] private KeyCode sprintKey = KeyCode.LeftShift;

    [Header("State")]
    [SerializeField] private bool canMove = true;

    // Components
    private CharacterController controller;
    private CameraController cameraController;

    // Movement state
    private Vector3 velocity;
    private Vector3 currentMovement;
    private bool isGrounded;
    private bool isSprinting;

    // Input
    private float horizontalInput;
    private float verticalInput;

    protected override void Awake()
    {
        base.Awake();
        if (Instance == this)
        {
            controller = GetComponent<CharacterController>();
            cameraController = GetComponentInChildren<CameraController>();
        }
    }

    private void Start()
    {
        // Lock cursor for first-person control
        CursorManager.Instance?.LockCursor();
    }

    private void Update()
    {
        if (!canMove) return;

        CheckGround();
        HandleInput();
        HandleMovement();
        ApplyGravity();
    }

    /// <summary>
    /// Checks if player is grounded.
    /// </summary>
    private void CheckGround()
    {
        // The controller's own result from the last Move; a sphere check here would hit the player's own capsule
        isGrounded = controller.isGrounded;

        // Reset vertical velocity when grounded
        if (isGrounded && velocity.y < 0)
        {
            velocity.y = -2f; // Small downward force to keep grounded
        }
    }

    /// <summary>
    /// Handles player input.
    /// </summary>
    private void HandleInput()
    {
        // Don't process movement input if chat is open or the portal is taking the player
        if ((UIChat.Instance != null && UIChat.Instance.IsVisible()) ||
            (PortalSequence.Instance != null && PortalSequence.Instance.IsTransitioning()))
        {
            horizontalInput = 0f;
            verticalInput = 0f;
            return;
        }

        horizontalInput = Input.GetAxisRaw("Horizontal");
        verticalInput = Input.GetAxisRaw("Vertical");
        isSprinting = Input.GetKey(sprintKey);
    }

    /// <summary>
    /// Handles player movement.
    /// </summary>
    private void HandleMovement()
    {
        // Calculate movement direction relative to camera
        Vector3 forward = transform.forward;
        Vector3 right = transform.right;

        // Keep movement horizontal
        forward.y = 0f;
        right.y = 0f;
        forward.Normalize();
        right.Normalize();

        // Calculate target velocity
        Vector3 targetDirection = (forward * verticalInput + right * horizontalInput).normalized;
        float targetSpeed = isSprinting ? sprintSpeed : walkSpeed;
        Vector3 targetVelocity = targetDirection * targetSpeed;

        // Smooth acceleration/deceleration
        if (targetDirection.magnitude > 0.1f)
        {
            currentMovement = Vector3.Lerp(currentMovement, targetVelocity, acceleration * Time.deltaTime);
        }
        else
        {
            currentMovement = Vector3.Lerp(currentMovement, Vector3.zero, deceleration * Time.deltaTime);
        }

        // Apply movement
        controller.Move(currentMovement * Time.deltaTime);
    }

    /// <summary>
    /// Applies gravity to the player.
    /// </summary>
    private void ApplyGravity()
    {
        velocity.y += gravity * Time.deltaTime;
        controller.Move(velocity * Time.deltaTime);
    }

    /// <summary>
    /// Enables or disables player movement.
    /// </summary>
    public void SetCanMove(bool value)
    {
        canMove = value;

        if (!canMove)
        {
            currentMovement = Vector3.zero;
        }
    }

    /// <summary>
    /// Teleports the player to a position.
    /// </summary>
    public void TeleportTo(Vector3 position)
    {
        controller.enabled = false;
        transform.position = position;
        controller.enabled = true;
    }

    /// <summary>
    /// Gets the current movement speed.
    /// </summary>
    public float GetCurrentSpeed()
    {
        return currentMovement.magnitude;
    }

    /// <summary>
    /// Checks if player is currently moving.
    /// </summary>
    public bool IsMoving()
    {
        // Actual velocity after collisions (walking into a wall is not moving)
        Vector3 horizontal = controller != null ? controller.velocity : Vector3.zero;
        horizontal.y = 0f;
        return horizontal.magnitude > 0.1f;
    }

    /// <summary>
    /// Checks if player is grounded.
    /// </summary>
    public bool IsGrounded()
    {
        return isGrounded;
    }

    private void OnDrawGizmosSelected()
    {
        // Draw the feet position, colored by grounded state
        Gizmos.color = isGrounded ? Color.green : Color.red;
        CharacterController cc = controller != null ? controller : GetComponent<CharacterController>();
        if (cc != null)
        {
            Vector3 feet = transform.TransformPoint(cc.center) + Vector3.down * (cc.height / 2f);
            Gizmos.DrawWireSphere(feet, cc.radius);
        }
    }
}
