// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M5 - Player Audio

using UnityEngine;

/// <summary>
/// Plays footstep sounds based on player movement.
/// Adds to immersion and can intensify with spook level.
/// </summary>
public class FootstepSystem : MonoBehaviour
{
    public static FootstepSystem Instance { get; private set; }

    [Header("Audio")]
    [SerializeField] private AudioSource footstepSource;
    [SerializeField] private AudioClip[] footstepClips;
    [SerializeField] private AudioClip[] runningClips;

    [Header("Timing")]
    [SerializeField] private float walkStepInterval = 0.5f;
    [SerializeField] private float runStepInterval = 0.3f;

    [Header("Audio Settings")]
    [SerializeField] private float baseVolume = 0.3f;
    [SerializeField] private float basePitch = 1f;
    [SerializeField] private float pitchVariation = 0.1f;

    [Header("Spook Modifiers")]
    [SerializeField] private bool respondToSpook = true;
    [SerializeField] private float spookVolumeReduction = 0.05f;
    [SerializeField] private float spookPitchReduction = 0.02f;

    // State
    private float stepTimer = 0f;
    private int lastClipIndex = -1;
    private int currentSpookLevel = 0;
    private bool isMoving = false;
    private bool isRunning = false;

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
        }
    }

    private void Start()
    {
        if (footstepSource == null)
        {
            footstepSource = gameObject.AddComponent<AudioSource>();
            footstepSource.playOnAwake = false;
            footstepSource.spatialBlend = 0f;
        }

        if (respondToSpook && EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged += OnSpookLevelChanged;
        }
    }

    private void Update()
    {
        // Check player movement
        if (FirstPersonController.Instance != null)
        {
            isMoving = FirstPersonController.Instance.IsMoving();
            isRunning = Input.GetKey(KeyCode.LeftShift) && isMoving;

            if (!FirstPersonController.Instance.IsGrounded())
            {
                isMoving = false;
            }
        }

        if (!isMoving)
        {
            stepTimer = 0f;
            return;
        }

        // Update step timer
        float interval = isRunning ? runStepInterval : walkStepInterval;
        stepTimer += Time.deltaTime;

        if (stepTimer >= interval)
        {
            stepTimer = 0f;
            PlayFootstep();
        }
    }

    /// <summary>
    /// Plays a footstep sound.
    /// </summary>
    private void PlayFootstep()
    {
        AudioClip[] clips = isRunning ? runningClips : footstepClips;

        if (clips == null || clips.Length == 0)
        {
            clips = footstepClips;
        }

        if (clips == null || clips.Length == 0)
        {
            return;
        }

        // Select random clip (avoid repeating)
        int clipIndex;
        if (clips.Length > 1)
        {
            do
            {
                clipIndex = Random.Range(0, clips.Length);
            } while (clipIndex == lastClipIndex);
        }
        else
        {
            clipIndex = 0;
        }
        lastClipIndex = clipIndex;

        AudioClip clip = clips[clipIndex];
        if (clip == null) return;

        // Calculate volume and pitch with spook modifiers
        float volume = baseVolume - (currentSpookLevel * spookVolumeReduction);
        float pitch = basePitch - (currentSpookLevel * spookPitchReduction);

        // Add variation
        pitch += Random.Range(-pitchVariation, pitchVariation);

        // Slightly louder when running
        if (isRunning)
        {
            volume *= 1.3f;
        }

        volume = Mathf.Clamp(volume, 0.1f, 1f);
        pitch = Mathf.Clamp(pitch, 0.7f, 1.3f);

        footstepSource.pitch = pitch;
        footstepSource.PlayOneShot(clip, volume);
    }

    /// <summary>
    /// Called when spook level changes.
    /// </summary>
    private void OnSpookLevelChanged(int level)
    {
        currentSpookLevel = level;

        // At high spook, footsteps become more muffled/distant
        // This is handled in PlayFootstep via modifiers
    }

    /// <summary>
    /// Plays a single forced footstep (for scripted moments).
    /// </summary>
    public void ForceFootstep()
    {
        PlayFootstep();
    }

    /// <summary>
    /// Sets the step interval.
    /// </summary>
    public void SetStepInterval(float walk, float run)
    {
        walkStepInterval = walk;
        runStepInterval = run;
    }

    /// <summary>
    /// Mutes footsteps temporarily.
    /// </summary>
    public void Mute(bool muted)
    {
        footstepSource.mute = muted;
    }

    private void OnDestroy()
    {
        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged -= OnSpookLevelChanged;
        }
    }
}
