// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M8 - Booth Prop

using UnityEngine;

/// <summary>
/// Booth/Alcove prop - summons Roderick Usher.
/// Features fog increase, decay atmosphere, and confined dread.
/// Triggers when player enters the booth area.
/// </summary>
public class BoothProp : MonoBehaviour, IInteractable
{
    [Header("Spirit Settings")]
    [SerializeField] private string spiritKey = "Usher";
    [SerializeField] private int spookIncrement = 1;

    [Header("Zone Trigger")]
    [SerializeField] private bool useZoneTrigger = true;
    [SerializeField] private BoxCollider zoneCollider;
    [SerializeField] private float zoneTriggerDelay = 1.5f;

    [Header("Visual Effects")]
    [SerializeField] private Light[] boothLights;
    [SerializeField] private ParticleSystem dustParticles;
    [SerializeField] private ParticleSystem fogParticles;
    [SerializeField] private float fogIncreaseAmount = 0.03f;

    [Header("Audio")]
    [SerializeField] private AudioSource ambientSource;
    [SerializeField] private AudioClip creakClip;
    [SerializeField] private AudioClip breathingClip;
    [SerializeField] private AudioClip voiceClip;

    [Header("Atmosphere")]
    [SerializeField] private Color normalLightColor = new Color(0.8f, 0.6f, 0.4f);
    [SerializeField] private Color activeLightColor = new Color(0.4f, 0.3f, 0.5f);
    [SerializeField] private float lightDimAmount = 0.5f;

    // State
    private bool isHighlighted = false;
    private bool playerInZone = false;
    private bool hasTriggered = false;
    private float zoneTimer = 0f;
    private float originalFogDensity;

    private void Start()
    {
        // Setup zone collider
        if (zoneCollider == null)
        {
            zoneCollider = GetComponent<BoxCollider>();
        }
        if (zoneCollider != null)
        {
            zoneCollider.isTrigger = true;
        }

        // Setup lights
        foreach (Light light in boothLights)
        {
            if (light != null)
            {
                light.color = normalLightColor;
            }
        }

        // Store original fog
        originalFogDensity = RenderSettings.fogDensity;
    }

    private void Update()
    {
        UpdateZoneTrigger();
        UpdateAtmosphere();
    }

    /// <summary>
    /// Handles zone trigger timing.
    /// </summary>
    private void UpdateZoneTrigger()
    {
        if (!useZoneTrigger || hasTriggered) return;

        if (playerInZone)
        {
            zoneTimer += Time.deltaTime;

            // Gradual atmosphere change while waiting
            float t = zoneTimer / zoneTriggerDelay;
            UpdateLightColors(t);

            // Increase fog slightly
            RenderSettings.fogDensity = Mathf.Lerp(originalFogDensity,
                originalFogDensity + fogIncreaseAmount, t);

            if (zoneTimer >= zoneTriggerDelay)
            {
                TriggerUsher();
            }
        }
        else
        {
            zoneTimer = Mathf.Max(0f, zoneTimer - Time.deltaTime * 0.5f);
            float t = zoneTimer / zoneTriggerDelay;
            UpdateLightColors(t);
        }
    }

    /// <summary>
    /// Updates light colors based on activation progress.
    /// </summary>
    private void UpdateLightColors(float t)
    {
        foreach (Light light in boothLights)
        {
            if (light != null)
            {
                light.color = Color.Lerp(normalLightColor, activeLightColor, t);
                light.intensity = Mathf.Lerp(1f, lightDimAmount, t);
            }
        }
    }

    /// <summary>
    /// Updates ambient atmosphere effects.
    /// </summary>
    private void UpdateAtmosphere()
    {
        // Subtle dust movement
        if (dustParticles != null && playerInZone)
        {
            var emission = dustParticles.emission;
            emission.rateOverTime = 20f + (zoneTimer * 10f);
        }
    }

    /// <summary>
    /// Triggers the Usher summoning sequence.
    /// </summary>
    private void TriggerUsher()
    {
        hasTriggered = true;
        Debug.Log("[BoothProp] Zone trigger - Summoning Usher");

        StartCoroutine(UsherSequence());
    }

    private System.Collections.IEnumerator UsherSequence()
    {
        // Creak sound
        if (AudioManager.Instance != null && creakClip != null)
        {
            AudioManager.Instance.PlaySFX(creakClip);
        }

        yield return new WaitForSeconds(0.5f);

        // Fog burst
        if (VFXManager.Instance != null)
        {
            VFXManager.Instance.AddFogBurst(fogIncreaseAmount);
        }

        // Start breathing ambience
        if (ambientSource != null && breathingClip != null)
        {
            ambientSource.clip = breathingClip;
            ambientSource.loop = true;
            ambientSource.volume = 0.3f;
            ambientSource.Play();
        }

        // Camera shake (subtle, like the house settling)
        if (CameraShake.Instance != null)
        {
            CameraShake.Instance.Shake(0.15f, 1f);
        }

        // Dim all booth lights
        foreach (Light light in boothLights)
        {
            if (light != null)
            {
                light.intensity = 0.2f;
            }
        }

        yield return new WaitForSeconds(0.5f);

        // Voice clip
        if (AudioManager.Instance != null && voiceClip != null)
        {
            AudioManager.Instance.PlaySFX(voiceClip);
        }

        // Summon spirit
        if (LLMManager.Instance != null)
        {
            LLMManager.Instance.SummonSpirit(spiritKey);
        }

        // Increment spook
        if (EventManager.Instance != null)
        {
            EventManager.Instance.IncrementSpook(spookIncrement);
        }

        // Show chat
        if (UIChat.Instance != null && !UIChat.Instance.IsVisible())
        {
            UIChat.Instance.Show();
        }

        // Reset after delay
        yield return new WaitForSeconds(15f);
        ResetBooth();
    }

    /// <summary>
    /// Resets the booth to initial state.
    /// </summary>
    private void ResetBooth()
    {
        hasTriggered = false;
        zoneTimer = 0f;

        foreach (Light light in boothLights)
        {
            if (light != null)
            {
                light.color = normalLightColor;
                light.intensity = 1f;
            }
        }

        if (ambientSource != null)
        {
            ambientSource.Stop();
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            playerInZone = true;
            Debug.Log("[BoothProp] Player entered booth zone");
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            playerInZone = false;
            Debug.Log("[BoothProp] Player exited booth zone");
        }
    }

    public void OnInteract()
    {
        // Direct interaction also triggers
        if (!hasTriggered)
        {
            TriggerUsher();
        }
    }

    public void OnHighlightEnter()
    {
        isHighlighted = true;
    }

    public void OnHighlightExit()
    {
        isHighlighted = false;
    }
}
