// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M8 - Booth Prop

using UnityEngine;

/// <summary>
/// Booth/Alcove prop - summons Roderick Usher.
/// Features fog increase, decay atmosphere, and confined dread.
/// Triggers when player enters the booth area.
/// </summary>
public class BoothProp : MonoBehaviour, IInteractable
{
    [Header("Spirit Settings")]
    [SerializeField] private string spiritKey = "Usher";
    [SerializeField] private int spookIncrement = 1;

    [Header("Zone Trigger")]
    [SerializeField] private bool useZoneTrigger = true;
    [SerializeField] private BoxCollider zoneCollider;
    [SerializeField] private float zoneTriggerDelay = 1.5f;

    [Header("Visual Effects")]
    [SerializeField] private Light[] boothLights;
    [SerializeField] private ParticleSystem dustParticles;
    [SerializeField] private ParticleSystem fogParticles;
    [SerializeField] private float fogIncreaseAmount = 0.03f;

    [Header("Audio")]
    [SerializeField] private AudioSource ambientSource;
    [SerializeField] private AudioClip creakClip;
    [SerializeField] private AudioClip breathingClip;
    [SerializeField] private AudioClip voiceClip;

    [Header("Atmosphere")]
    [SerializeField] private Color normalLightColor = new Color(0.8f, 0.6f, 0.4f);
    [SerializeField] private Color activeLightColor = new Color(0.4f, 0.3f, 0.5f);
    [SerializeField] private float lightDimAmount = 0.5f;

    // State
    private bool isHighlighted = false;
    private bool playerInZone = false;
    private bool hasTriggered = false;
    private float zoneTimer = 0f;
    private bool rearmOnExit = false;

    private void Start()
    {
        // Setup zone collider: a dedicated trigger next to the booth's solid collider. Turning the
        // booth's own collider into a trigger would make it walk-through and impossible to target with E.
        if (zoneCollider == null)
        {
            BoxCollider solid = GetComponent<BoxCollider>();
            zoneCollider = gameObject.AddComponent<BoxCollider>();
            if (solid != null)
            {
                // The booth's own box plus ~0.6 m on each horizontal side (converted to local units)
                Vector3 scale = transform.lossyScale;
                const float margin = 0.6f;
                zoneCollider.center = solid.center;
                zoneCollider.size = solid.size + new Vector3(
                    2f * margin / Mathf.Max(0.0001f, Mathf.Abs(scale.x)), 0f,
                    2f * margin / Mathf.Max(0.0001f, Mathf.Abs(scale.z)));
            }
            else
            {
                // Any other collider: use its bounds (converted to local units) plus the same margin
                Collider other = null;
                foreach (Collider c in GetComponents<Collider>())
                {
                    if (c != zoneCollider && !c.isTrigger) { other = c; break; }
                }
                Vector3 scale = transform.lossyScale;
                Vector3 absScale = new Vector3(Mathf.Max(0.0001f, Mathf.Abs(scale.x)), Mathf.Max(0.0001f, Mathf.Abs(scale.y)), Mathf.Max(0.0001f, Mathf.Abs(scale.z)));
                if (other != null)
                {
                    Bounds b = other.bounds;
                    zoneCollider.center = transform.InverseTransformPoint(b.center);
                    zoneCollider.size = new Vector3((b.size.x + 1.2f) / absScale.x, b.size.y / absScale.y, (b.size.z + 1.2f) / absScale.z);
                }
                else
                {
                    zoneCollider.size = new Vector3(2f / absScale.x, 2f / absScale.y, 2f / absScale.z);
                }
            }
        }
        zoneCollider.isTrigger = true;

        // Setup lights
        if (boothLights != null)
        {
            foreach (Light light in boothLights)
            {
                if (light != null)
                {
                    light.color = normalLightColor;
                }
            }
        }

    }

    private void Update()
    {
        UpdateZoneTrigger();
        UpdateAtmosphere();
    }

    /// <summary>
    /// Handles zone trigger timing.
    /// </summary>
    private void UpdateZoneTrigger()
    {
        if (!useZoneTrigger || hasTriggered) return;

        // Don't interrupt a conversation already under way
        if (UIChat.Instance != null && UIChat.Instance.IsVisible()) return;

        if (playerInZone)
        {
            zoneTimer += Time.deltaTime;

            // Gradual atmosphere change while waiting (fog is added as a burst when Usher appears)
            float t = zoneTimer / zoneTriggerDelay;
            UpdateLightColors(t);

            if (zoneTimer >= zoneTriggerDelay)
            {
                TriggerUsher();
            }
        }
        else
        {
            zoneTimer = Mathf.Max(0f, zoneTimer - Time.deltaTime * 0.5f);
            float t = zoneTimer / zoneTriggerDelay;
            UpdateLightColors(t);
        }
    }

    /// <summary>
    /// Updates light colors based on activation progress.
    /// </summary>
    private void UpdateLightColors(float t)
    {
        if (boothLights == null) return;

        foreach (Light light in boothLights)
        {
            if (light != null)
            {
                light.color = Color.Lerp(normalLightColor, activeLightColor, t);
                light.intensity = Mathf.Lerp(1f, lightDimAmount, t);
            }
        }
    }

    /// <summary>
    /// Updates ambient atmosphere effects.
    /// </summary>
    private void UpdateAtmosphere()
    {
        // Subtle dust movement
        if (dustParticles != null && playerInZone)
        {
            var emission = dustParticles.emission;
            emission.rateOverTime = 20f + (zoneTimer * 10f);
        }
    }

    /// <summary>
    /// Triggers the Usher summoning sequence.
    /// </summary>
    private void TriggerUsher()
    {
        hasTriggered = true;
        Debug.Log("[BoothProp] Zone trigger - Summoning Usher");

        StartCoroutine(UsherSequence());
    }

    private System.Collections.IEnumerator UsherSequence()
    {
        // Creak sound
        if (AudioManager.Instance != null && creakClip != null)
        {
            AudioManager.Instance.PlaySFX(creakClip);
        }

        yield return new WaitForSeconds(0.5f);

        // Fog burst
        if (VFXManager.Instance != null)
        {
            VFXManager.Instance.AddFogBurst(fogIncreaseAmount);
        }

        // Start breathing ambience
        if (ambientSource != null && breathingClip != null)
        {
            ambientSource.clip = breathingClip;
            ambientSource.loop = true;
            ambientSource.volume = 0.3f;
            ambientSource.Play();
        }

        // Camera shake (subtle, like the house settling)
        if (CameraShake.Instance != null)
        {
            CameraShake.Instance.Shake(0.15f, 1f);
        }

        // Dim all booth lights
        if (boothLights != null)
        {
            foreach (Light light in boothLights)
            {
                if (light != null)
                {
                    light.intensity = 0.2f;
                }
            }
        }

        yield return new WaitForSeconds(0.5f);

        // Voice clip
        if (AudioManager.Instance != null && voiceClip != null)
        {
            AudioManager.Instance.PlaySFX(voiceClip);
        }

        // Summon spirit
        if (LLMManager.Instance != null)
        {
            LLMManager.Instance.SummonSpirit(spiritKey);
        }

        // Increment spook
        if (EventManager.Instance != null)
        {
            EventManager.Instance.IncrementSpook(spookIncrement);
        }

        // Show chat
        if (UIChat.Instance != null && !UIChat.Instance.IsVisible())
        {
            UIChat.Instance.Show();
        }

        // Reset after delay
        yield return new WaitForSeconds(15f);
        ResetBooth();
    }

    /// <summary>
    /// Resets the booth to initial state.
    /// </summary>
    private void ResetBooth()
    {
        // Re-arm only once the player has left; otherwise Usher would interrupt every few seconds
        if (playerInZone)
        {
            rearmOnExit = true;
        }
        else
        {
            hasTriggered = false;
        }
        zoneTimer = 0f;

        if (boothLights != null)
        {
            foreach (Light light in boothLights)
            {
                if (light != null)
                {
                    light.color = normalLightColor;
                    light.intensity = 1f;
                }
            }
        }

        if (ambientSource != null)
        {
            ambientSource.Stop();
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            playerInZone = true;
            Debug.Log("[BoothProp] Player entered booth zone");
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            playerInZone = false;
            if (rearmOnExit)
            {
                rearmOnExit = false;
                hasTriggered = false;
            }
            Debug.Log("[BoothProp] Player exited booth zone");
        }
    }

    public void OnInteract()
    {
        // Direct interaction also triggers
        if (!hasTriggered)
        {
            TriggerUsher();
        }
    }

    public void OnHighlightEnter()
    {
        isHighlighted = true;
    }

    public void OnHighlightExit()
    {
        isHighlighted = false;
    }
}
