// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M8

using UnityEngine;

/// <summary>
/// Makes a prop interactable and binds it to a specific Poe spirit.
/// Attach to Crystal Ball, Mirror, Booth, Table, etc.
/// </summary>
public class InteractableSpirit : MonoBehaviour, IInteractable
{
    [Header("Spirit Configuration")]
    [Tooltip("The spirit key (Raven, Narrator, Usher)")]
    [SerializeField] private string spiritKey = "Raven";

    [Tooltip("How much to increment spook level on interaction")]
    [SerializeField] private int spookIncrement = 1;

    [Header("Audio")]
    [Tooltip("Optional voice clip to play on interaction")]
    [SerializeField] private AudioClip voiceClip;

    [Tooltip("Optional ambient sound for this prop")]
    [SerializeField] private AudioClip ambientClip;

    [Header("Visual Feedback")]
    [Tooltip("Material to use when highlighted")]
    [SerializeField] private Material highlightMaterial;

    [Tooltip("Emission color when highlighted")]
    [SerializeField] private Color highlightColor = new Color(0.5f, 0.3f, 0.8f);

    [Tooltip("Light component for glow effect")]
    [SerializeField] private Light glowLight;

    // Cached components
    private Renderer propRenderer;
    private Material originalMaterial;
    private MaterialPropertyBlock propBlock;
    private static readonly int EmissionColor = Shader.PropertyToID("_EmissionColor");
    private bool isHighlighted = false;

    // Cooldown to prevent spam
    private float lastInteractTime = 0f;
    private float interactCooldown = 1f;

    private PropHighlight propHighlight;

    private void Awake()
    {
        // Optional richer highlight effect on the same prop
        propHighlight = GetComponent<PropHighlight>();

        // Cache renderer
        propRenderer = GetComponent<Renderer>();
        propBlock = new MaterialPropertyBlock();
        if (propRenderer != null)
        {
            originalMaterial = propRenderer.sharedMaterial;
        }

        // The generators put the glow light on a child named "GlowLight" (other lights, e.g. candles, are left alone)
        if (glowLight == null)
        {
            Transform glow = transform.Find("GlowLight");
            if (glow != null)
            {
                glowLight = glow.GetComponent<Light>();
            }
        }

        // Setup glow light
        if (glowLight != null)
        {
            glowLight.enabled = false;
            glowLight.color = highlightColor;
        }
    }

    /// <summary>
    /// Called when the player interacts with this object.
    /// </summary>
    public void OnInteract()
    {
        // Cooldown check
        if (Time.time - lastInteractTime < interactCooldown)
        {
            return;
        }
        lastInteractTime = Time.time;

        // Coming back to the spirit you're already talking to just reopens the chat:
        // no new greeting (which would cancel the reply in progress) and no extra spook
        if (LLMManager.Instance != null && LLMManager.Instance.ActiveSpirit == spiritKey)
        {
            if (UIChat.Instance != null)
            {
                UIChat.Instance.Show();
            }
            return;
        }

        Debug.Log($"[InteractableSpirit] Interacted with {gameObject.name}, summoning {spiritKey}");

        // Play interaction sound
        if (AudioManager.Instance != null)
        {
            AudioManager.Instance.PlayInteract();

            if (voiceClip != null)
            {
                AudioManager.Instance.PlaySFX(voiceClip);
            }
        }

        // Summon the spirit
        bool summoned = LLMManager.Instance != null && LLMManager.Instance.SummonSpirit(spiritKey);

        // Increment spook level the first time each spirit is called up (replies to the player raise it further)
        if (summoned && LLMManager.Instance.MarkFirstSummon(spiritKey) && EventManager.Instance != null)
        {
            EventManager.Instance.IncrementSpook(spookIncrement);
        }

        // Trigger visual effect
        TriggerInteractEffect();

        // Show chat UI if hidden
        if (UIChat.Instance != null && !UIChat.Instance.IsVisible())
        {
            UIChat.Instance.Show();
        }
    }

    /// <summary>
    /// Called when the player's raycast starts targeting this object.
    /// </summary>
    public void OnHighlightEnter()
    {
        if (isHighlighted) return;
        isHighlighted = true;

        Debug.Log($"[InteractableSpirit] Highlighting {gameObject.name}");

        // Apply highlight via MaterialPropertyBlock (no material instance leak); a PropHighlight on the
        // prop owns the material effect instead (a property block would hide its animated emission)
        if (propRenderer != null && propHighlight == null)
        {
            propRenderer.GetPropertyBlock(propBlock);
            propBlock.SetColor(EmissionColor, highlightColor * 0.5f);
            propRenderer.SetPropertyBlock(propBlock);
        }

        // Enable glow light
        if (glowLight != null)
        {
            glowLight.enabled = true;
        }

        if (propHighlight != null)
        {
            propHighlight.SetHighlighted(true);
        }
    }

    /// <summary>
    /// Called when the player's raycast stops targeting this object.
    /// </summary>
    public void OnHighlightExit()
    {
        if (!isHighlighted) return;
        isHighlighted = false;

        Debug.Log($"[InteractableSpirit] Unhighlighting {gameObject.name}");

        // Clear highlight: drop the override so the material's own emission shows again
        if (propRenderer != null && propHighlight == null)
        {
            propRenderer.SetPropertyBlock(null);
        }

        // Disable glow light
        if (glowLight != null)
        {
            glowLight.enabled = false;
        }

        if (propHighlight != null)
        {
            propHighlight.SetHighlighted(false);
        }
    }

    /// <summary>
    /// Triggers a visual effect on interaction.
    /// </summary>
    private void TriggerInteractEffect()
    {
        // Pulse the highlight
        StartCoroutine(InteractPulse());

        // Trigger prop-specific effects
        switch (spiritKey)
        {
            case "Raven":
                // Crystal ball glow
                if (VFXManager.Instance != null)
                {
                    VFXManager.Instance.EnableOrbGlow();
                }
                break;

            case "Narrator":
                // Mirror glitch
                if (PostFXController.Instance != null)
                {
                    PostFXController.Instance.TriggerGlitch(0.3f);
                }
                if (AudioManager.Instance != null)
                {
                    AudioManager.Instance.PlayHeartbeat();
                }
                break;

            case "Usher":
                // Fog burst
                if (VFXManager.Instance != null)
                {
                    VFXManager.Instance.AddFogBurst(0.03f);
                }
                break;
        }
    }

    /// <summary>
    /// Coroutine for interaction pulse effect.
    /// </summary>
    private System.Collections.IEnumerator InteractPulse()
    {
        if (glowLight == null) yield break;

        float originalIntensity = glowLight.intensity;
        float pulseIntensity = originalIntensity * 3f;

        // Pulse up
        float duration = 0.2f;
        float elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            glowLight.intensity = Mathf.Lerp(originalIntensity, pulseIntensity, elapsed / duration);
            yield return null;
        }

        // Pulse down
        elapsed = 0f;
        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            glowLight.intensity = Mathf.Lerp(pulseIntensity, originalIntensity, elapsed / duration);
            yield return null;
        }

        glowLight.intensity = originalIntensity;
    }

    /// <summary>
    /// Gets the spirit key associated with this prop.
    /// </summary>
    public string GetSpiritKey()
    {
        return spiritKey;
    }

    /// <summary>
    /// Sets the spirit key (for runtime configuration).
    /// </summary>
    public void SetSpiritKey(string key)
    {
        spiritKey = key;
    }

    private void OnValidate()
    {
        // Editor validation
        if (spookIncrement < 0) spookIncrement = 0;
        if (spookIncrement > 5) spookIncrement = 5;
    }
}
