// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M8 - Mirror Prop

using UnityEngine;

/// <summary>
/// Mirror prop - summons the Tell-Tale Heart Narrator.
/// Features reflection glitch, heartbeat audio, and paranoid responses.
/// </summary>
public class MirrorProp : MonoBehaviour, IInteractable
{
    [Header("Spirit Settings")]
    [SerializeField] private string spiritKey = "Narrator";
    [SerializeField] private int spookIncrement = 1;

    [Header("Visual Effects")]
    [SerializeField] private Material mirrorMaterial;
    [SerializeField] private float glitchIntensity = 0.5f;
    [SerializeField] private Light frameLight;
    [SerializeField] private ParticleSystem dustParticles;

    [Header("Shader Properties")]
    [SerializeField] private string distortionProperty = "_Distortion";
    [SerializeField] private string glitchProperty = "_GlitchAmount";
    [SerializeField] private string tintProperty = "_Tint";

    [Header("Audio")]
    [SerializeField] private AudioSource ambientSource;
    [SerializeField] private AudioClip whisperClip;
    [SerializeField] private AudioClip heartbeatClip;
    [SerializeField] private AudioClip crackClip;

    [Header("Gaze Detection")]
    [SerializeField] private bool useGazeDetection = true;
    [SerializeField] private float gazeThreshold = 0.8f;
    [SerializeField] private float gazeDuration = 2f;

    // State
    private bool isHighlighted = false;
    private bool isGlitching = false;
    private float gazeTimer = 0f;
    private bool hasTriggeredGaze = false;
    private Renderer mirrorRenderer;

    private void Start()
    {
        mirrorRenderer = GetComponent<Renderer>();
        if (mirrorRenderer != null && mirrorMaterial == null)
        {
            mirrorMaterial = mirrorRenderer.material;
        }

        if (frameLight != null)
        {
            frameLight.intensity = 0.3f;
        }

        // Start subtle dust
        if (dustParticles != null)
        {
            dustParticles.Play();
        }
    }

    private void Update()
    {
        UpdateGazeDetection();
        UpdateGlitchEffect();
        UpdateAmbientEffects();
    }

    /// <summary>
    /// Detects if player is staring at the mirror.
    /// </summary>
    private void UpdateGazeDetection()
    {
        if (!useGazeDetection || hasTriggeredGaze) return;

        // Check if camera is looking at mirror
        if (Camera.main != null)
        {
            Vector3 toMirror = (transform.position - Camera.main.transform.position).normalized;
            float dot = Vector3.Dot(Camera.main.transform.forward, toMirror);

            if (dot > gazeThreshold && isHighlighted)
            {
                gazeTimer += Time.deltaTime;

                // Increase unease while staring
                if (gazeTimer > 1f && mirrorMaterial != null)
                {
                    float glitch = Mathf.Sin(Time.time * 10f) * 0.1f * (gazeTimer / gazeDuration);
                    if (mirrorMaterial.HasProperty(glitchProperty))
                    {
                        mirrorMaterial.SetFloat(glitchProperty, glitch);
                    }
                }

                // Trigger after staring long enough
                if (gazeTimer >= gazeDuration)
                {
                    hasTriggeredGaze = true;
                    OnGazeTrigger();
                }
            }
            else
            {
                gazeTimer = Mathf.Max(0f, gazeTimer - Time.deltaTime * 0.5f);
            }
        }
    }

    /// <summary>
    /// Called when player stares too long.
    /// </summary>
    private void OnGazeTrigger()
    {
        Debug.Log("[MirrorProp] Gaze trigger activated!");

        // Glitch effect
        StartCoroutine(GlitchSequence(0.5f));

        // Play heartbeat
        if (AudioManager.Instance != null && heartbeatClip != null)
        {
            AudioManager.Instance.PlaySFX(heartbeatClip);
        }

        // Increment spook
        if (EventManager.Instance != null)
        {
            EventManager.Instance.IncrementSpook(1);
        }

        // Reset after delay
        Invoke(nameof(ResetGazeTrigger), 10f);
    }

    private void ResetGazeTrigger()
    {
        hasTriggeredGaze = false;
        gazeTimer = 0f;
    }

    /// <summary>
    /// Updates the glitch shader effect.
    /// </summary>
    private void UpdateGlitchEffect()
    {
        if (mirrorMaterial == null) return;

        if (isGlitching)
        {
            float glitch = Random.Range(0f, glitchIntensity);
            float distort = Mathf.Sin(Time.time * 20f) * 0.1f;

            if (mirrorMaterial.HasProperty(glitchProperty))
                mirrorMaterial.SetFloat(glitchProperty, glitch);
            if (mirrorMaterial.HasProperty(distortionProperty))
                mirrorMaterial.SetFloat(distortionProperty, distort);
        }
    }

    /// <summary>
    /// Updates ambient visual effects.
    /// </summary>
    private void UpdateAmbientEffects()
    {
        // Subtle frame light flicker
        if (frameLight != null)
        {
            float flicker = 0.3f + Mathf.PerlinNoise(Time.time * 2f, 0f) * 0.2f;
            frameLight.intensity = isHighlighted ? flicker * 2f : flicker;
        }
    }

    public void OnInteract()
    {
        Debug.Log("[MirrorProp] Interacted - Summoning Narrator");

        StartCoroutine(InteractionSequence());
    }

    /// <summary>
    /// Full interaction sequence.
    /// </summary>
    private System.Collections.IEnumerator InteractionSequence()
    {
        // Initial crack sound
        if (AudioManager.Instance != null && crackClip != null)
        {
            AudioManager.Instance.PlaySFX(crackClip);
        }

        // Camera shake
        if (CameraShake.Instance != null)
        {
            CameraShake.Instance.Shake(0.3f, 0.4f);
        }

        // Glitch sequence
        yield return StartCoroutine(GlitchSequence(1f));

        // PostFX glitch
        if (PostFXController.Instance != null)
        {
            PostFXController.Instance.TriggerGlitch(0.5f);
        }

        // Screen effect
        if (ScreenEffects.Instance != null)
        {
            ScreenEffects.Instance.TerrorFlash();
        }

        // Heartbeat
        if (HeartbeatEffect.Instance != null)
        {
            HeartbeatEffect.Instance.ForceBeat();
        }

        // Summon spirit
        if (LLMManager.Instance != null)
        {
            LLMManager.Instance.SummonSpirit(spiritKey);
        }

        // Increment spook
        if (EventManager.Instance != null)
        {
            EventManager.Instance.IncrementSpook(spookIncrement);
        }

        // Show chat
        if (UIChat.Instance != null && !UIChat.Instance.IsVisible())
        {
            UIChat.Instance.Show();
        }
    }

    /// <summary>
    /// Glitch visual sequence.
    /// </summary>
    private System.Collections.IEnumerator GlitchSequence(float duration)
    {
        isGlitching = true;

        yield return new WaitForSeconds(duration);

        isGlitching = false;

        // Reset material properties
        if (mirrorMaterial != null)
        {
            if (mirrorMaterial.HasProperty(glitchProperty))
                mirrorMaterial.SetFloat(glitchProperty, 0f);
            if (mirrorMaterial.HasProperty(distortionProperty))
                mirrorMaterial.SetFloat(distortionProperty, 0f);
        }
    }

    public void OnHighlightEnter()
    {
        isHighlighted = true;

        // Start whispers
        if (ambientSource != null && whisperClip != null)
        {
            ambientSource.clip = whisperClip;
            ambientSource.loop = true;
            ambientSource.volume = 0.2f;
            ambientSource.Play();
        }
    }

    public void OnHighlightExit()
    {
        isHighlighted = false;

        if (ambientSource != null)
        {
            ambientSource.Stop();
        }
    }
}
