// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M8 - Prop Ambient Sound

using UnityEngine;

/// <summary>
/// Handles ambient sound loops for interactive props.
/// Supports proximity-based volume, spook-level reactivity, and sound variations.
/// </summary>
public class PropAmbientSound : MonoBehaviour
{
    [Header("Audio Sources")]
    [SerializeField] private AudioSource primarySource;
    [SerializeField] private AudioSource secondarySource;

    [Header("Audio Clips")]
    [SerializeField] private AudioClip ambientLoop;
    [SerializeField] private AudioClip highlightLoop;
    [SerializeField] private AudioClip[] randomSounds;
    [SerializeField] private float randomSoundInterval = 10f;
    [SerializeField] private float randomSoundChance = 0.3f;

    [Header("Volume Settings")]
    [SerializeField] private float baseVolume = 0.2f;
    [SerializeField] private float highlightVolume = 0.5f;
    [SerializeField] private float maxVolume = 0.8f;
    [SerializeField] private float volumeTransitionSpeed = 3f;

    [Header("Proximity")]
    [SerializeField] private bool useProximity = true;
    [SerializeField] private float maxDistance = 10f;
    [SerializeField] private float minDistance = 2f;

    [Header("Spook Reactivity")]
    [SerializeField] private bool reactToSpook = true;
    [SerializeField] private float spookVolumeMultiplier = 0.1f;
    [SerializeField] private float spookPitchVariation = 0.1f;

    [Header("Variation")]
    [SerializeField] private bool usePitchVariation = true;
    [SerializeField] private float basePitch = 1f;
    [SerializeField] private float pitchVariationAmount = 0.05f;
    [SerializeField] private float pitchVariationSpeed = 0.5f;

    // State
    private bool isHighlighted = false;
    private float targetVolume;
    private float currentVolume;
    private float randomSoundTimer;
    private int currentSpookLevel = 0;
    private Transform playerTransform;

    private void Start()
    {
        // Setup primary audio source
        if (primarySource == null)
        {
            primarySource = gameObject.AddComponent<AudioSource>();
        }
        primarySource.spatialBlend = 1f; // 3D sound
        primarySource.rolloffMode = AudioRolloffMode.Linear;
        primarySource.maxDistance = maxDistance;
        primarySource.minDistance = minDistance;
        primarySource.loop = true;
        primarySource.playOnAwake = false;

        // Setup secondary source for overlays
        if (secondarySource == null)
        {
            secondarySource = gameObject.AddComponent<AudioSource>();
        }
        secondarySource.spatialBlend = 1f;
        secondarySource.rolloffMode = AudioRolloffMode.Linear;
        secondarySource.maxDistance = maxDistance;
        secondarySource.minDistance = minDistance;
        secondarySource.loop = false;
        secondarySource.playOnAwake = false;

        // Start ambient loop
        if (ambientLoop != null)
        {
            primarySource.clip = ambientLoop;
            primarySource.volume = baseVolume;
            primarySource.Play();
        }

        targetVolume = baseVolume;
        currentVolume = baseVolume;

        // Find player
        GameObject player = GameObject.FindGameObjectWithTag("Player");
        if (player != null)
        {
            playerTransform = player.transform;
        }

        // Subscribe to spook events
        if (reactToSpook && EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged += OnSpookLevelChanged;
        }
    }

    private void Update()
    {
        UpdateVolume();
        UpdatePitch();
        UpdateRandomSounds();
        UpdateProximity();
    }

    /// <summary>
    /// Updates volume interpolation.
    /// </summary>
    private void UpdateVolume()
    {
        // Calculate target volume based on state
        float baseTarget = isHighlighted ? highlightVolume : baseVolume;

        // Add spook modifier
        if (reactToSpook)
        {
            baseTarget += currentSpookLevel * spookVolumeMultiplier;
        }

        targetVolume = Mathf.Clamp(baseTarget, 0f, maxVolume);

        // Smooth transition
        currentVolume = Mathf.Lerp(currentVolume, targetVolume, volumeTransitionSpeed * Time.deltaTime);
        primarySource.volume = currentVolume;
    }

    /// <summary>
    /// Updates pitch variation for organic feel.
    /// </summary>
    private void UpdatePitch()
    {
        if (!usePitchVariation) return;

        float pitchOffset = Mathf.Sin(Time.time * pitchVariationSpeed) * pitchVariationAmount;

        // Add spook pitch variation
        if (reactToSpook)
        {
            pitchOffset -= currentSpookLevel * spookPitchVariation;
        }

        primarySource.pitch = basePitch + pitchOffset;
    }

    /// <summary>
    /// Handles random sound playback for variety.
    /// </summary>
    private void UpdateRandomSounds()
    {
        if (randomSounds == null || randomSounds.Length == 0) return;

        randomSoundTimer += Time.deltaTime;

        if (randomSoundTimer >= randomSoundInterval)
        {
            randomSoundTimer = 0f;

            // Chance-based playback
            if (Random.value < randomSoundChance)
            {
                PlayRandomSound();
            }
        }
    }

    /// <summary>
    /// Updates volume based on player proximity.
    /// </summary>
    private void UpdateProximity()
    {
        if (!useProximity || playerTransform == null) return;

        float distance = Vector3.Distance(transform.position, playerTransform.position);
        float proximityFactor = 1f - Mathf.Clamp01((distance - minDistance) / (maxDistance - minDistance));

        // Apply proximity to current volume
        primarySource.volume = currentVolume * proximityFactor;
    }

    /// <summary>
    /// Plays a random sound from the array.
    /// </summary>
    private void PlayRandomSound()
    {
        if (randomSounds == null || randomSounds.Length == 0) return;

        AudioClip clip = randomSounds[Random.Range(0, randomSounds.Length)];
        if (clip != null && secondarySource != null)
        {
            secondarySource.pitch = basePitch + Random.Range(-0.1f, 0.1f);
            secondarySource.PlayOneShot(clip, currentVolume * 0.8f);
        }
    }

    /// <summary>
    /// Handles spook level changes.
    /// </summary>
    private void OnSpookLevelChanged(int level)
    {
        currentSpookLevel = level;

        // Higher spook = more frequent random sounds
        if (level > 2)
        {
            randomSoundChance = 0.3f + (level * 0.1f);
            randomSoundInterval = Mathf.Max(5f, 10f - level);
        }
    }

    /// <summary>
    /// Sets highlighted state for volume boost.
    /// </summary>
    public void SetHighlighted(bool highlighted)
    {
        isHighlighted = highlighted;

        // Crossfade to highlight loop if available
        if (highlightLoop != null && highlighted && primarySource.clip != highlightLoop)
        {
            StartCoroutine(CrossfadeToClip(highlightLoop));
        }
        else if (!highlighted && ambientLoop != null && primarySource.clip != ambientLoop)
        {
            StartCoroutine(CrossfadeToClip(ambientLoop));
        }
    }

    /// <summary>
    /// Crossfades between audio clips.
    /// </summary>
    private System.Collections.IEnumerator CrossfadeToClip(AudioClip newClip)
    {
        float startVolume = primarySource.volume;

        // Fade out
        float elapsed = 0f;
        float fadeDuration = 0.3f;

        while (elapsed < fadeDuration)
        {
            elapsed += Time.deltaTime;
            primarySource.volume = Mathf.Lerp(startVolume, 0f, elapsed / fadeDuration);
            yield return null;
        }

        // Switch clip
        primarySource.clip = newClip;
        primarySource.Play();

        // Fade in
        elapsed = 0f;
        while (elapsed < fadeDuration)
        {
            elapsed += Time.deltaTime;
            primarySource.volume = Mathf.Lerp(0f, currentVolume, elapsed / fadeDuration);
            yield return null;
        }
    }

    /// <summary>
    /// Plays a one-shot sound effect.
    /// </summary>
    public void PlayOneShot(AudioClip clip, float volumeScale = 1f)
    {
        if (clip != null && secondarySource != null)
        {
            secondarySource.PlayOneShot(clip, currentVolume * volumeScale);
        }
    }

    /// <summary>
    /// Sets the ambient loop clip.
    /// </summary>
    public void SetAmbientClip(AudioClip clip)
    {
        ambientLoop = clip;
        if (primarySource != null && !isHighlighted)
        {
            primarySource.clip = clip;
            if (!primarySource.isPlaying)
            {
                primarySource.Play();
            }
        }
    }

    /// <summary>
    /// Stops all sounds.
    /// </summary>
    public void StopAll()
    {
        if (primarySource != null) primarySource.Stop();
        if (secondarySource != null) secondarySource.Stop();
    }

    /// <summary>
    /// Pauses ambient sound.
    /// </summary>
    public void Pause()
    {
        if (primarySource != null) primarySource.Pause();
    }

    /// <summary>
    /// Resumes ambient sound.
    /// </summary>
    public void Resume()
    {
        if (primarySource != null) primarySource.UnPause();
    }

    private void OnDestroy()
    {
        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnSpookLevelChanged -= OnSpookLevelChanged;
        }
    }
}
