// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M8 - Prop Highlight System

using UnityEngine;

/// <summary>
/// Handles visual highlighting of interactable props.
/// Supports outline glow, emission boost, and scale pulse effects.
/// </summary>
public class PropHighlight : MonoBehaviour
{
    [Header("Highlight Type")]
    [SerializeField] private HighlightMode highlightMode = HighlightMode.Emission;
    [SerializeField] private bool useScalePulse = true;

    [Header("Emission Settings")]
    [SerializeField] private Color highlightColor = new Color(0.5f, 0.3f, 0.8f);
    [SerializeField] private float highlightIntensity = 2f;
    [SerializeField] private float normalIntensity = 0f;
    [SerializeField] private string emissionProperty = "_EmissionColor";

    [Header("Outline Settings")]
    [SerializeField] private Material outlineMaterial;
    [SerializeField] private float outlineWidth = 0.02f;
    [SerializeField] private Color outlineColor = new Color(0.6f, 0.4f, 1f);

    [Header("Scale Pulse")]
    [SerializeField] private float pulseAmount = 0.05f;
    [SerializeField] private float pulseSpeed = 3f;

    [Header("Transition")]
    [SerializeField] private float transitionSpeed = 8f;

    public enum HighlightMode
    {
        Emission,
        Outline,
        Both
    }

    // State
    private bool isHighlighted = false;
    private float currentIntensity = 0f;
    private Vector3 originalScale;
    private Renderer[] renderers;
    private Material[] originalMaterials;
    private Material[] highlightMaterials;
    private GameObject outlineObject;

    private Color[] originalEmission;
    private bool materialsSwapped = false;
    private bool ownsOutlineMaterial = false;

    private void Start()
    {
        originalScale = transform.localScale;
        renderers = GetComponentsInChildren<Renderer>();

        // Cache original materials and create highlight versions
        CacheMaterials();

        // Setup outline if needed
        if (highlightMode == HighlightMode.Outline || highlightMode == HighlightMode.Both)
        {
            SetupOutline();
        }
    }

    /// <summary>
    /// Caches materials for emission highlighting.
    /// </summary>
    private void CacheMaterials()
    {
        if (renderers == null || renderers.Length == 0) return;

        // The highlight copies are made when a highlight starts (see BeginHighlightMaterials), from whatever
        // material is on the renderer then, so instances other components assign in their Start are respected
        originalMaterials = new Material[renderers.Length];
        highlightMaterials = new Material[renderers.Length];
        originalEmission = new Color[renderers.Length];
    }

    /// <summary>
    /// Puts emission-enabled copies of the renderers' current materials in place.
    /// </summary>
    private void BeginHighlightMaterials()
    {
        for (int i = 0; i < renderers.Length; i++)
        {
            // sharedMaterial: reading .material would create (and leak) an instance per renderer
            if (renderers[i] == null || renderers[i].sharedMaterial == null) continue;

            originalMaterials[i] = renderers[i].sharedMaterial;
            if (highlightMaterials[i] != null)
            {
                Destroy(highlightMaterials[i]);
            }
            highlightMaterials[i] = new Material(originalMaterials[i]);

            // Enable emission keyword, keeping any emission the material already had
            originalEmission[i] = Color.black;
            if (highlightMaterials[i].HasProperty(emissionProperty))
            {
                if (highlightMaterials[i].IsKeywordEnabled("_EMISSION"))
                {
                    originalEmission[i] = highlightMaterials[i].GetColor(emissionProperty);
                }
                highlightMaterials[i].EnableKeyword("_EMISSION");
            }
            renderers[i].sharedMaterial = highlightMaterials[i];
        }
        materialsSwapped = true;
    }

    /// <summary>
    /// Restores the materials that were on the renderers when the highlight started.
    /// </summary>
    private void EndHighlightMaterials()
    {
        for (int i = 0; i < renderers.Length; i++)
        {
            // Leave a renderer alone if something else replaced our copy in the meantime
            if (renderers[i] != null && originalMaterials[i] != null && renderers[i].sharedMaterial == highlightMaterials[i])
            {
                renderers[i].sharedMaterial = originalMaterials[i];
            }
        }
        materialsSwapped = false;
    }

    /// <summary>
    /// Sets up outline effect using a scaled duplicate mesh.
    /// </summary>
    private void SetupOutline()
    {
        if (outlineMaterial != null)
        {
            // The outline colour is animated: work on a copy, not the assigned asset
            outlineMaterial = new Material(outlineMaterial);
            ownsOutlineMaterial = true;
        }
        else
        {
            // Create simple outline material (the shader may be stripped from builds; assign a material instead)
            Shader shader = Shader.Find("Unlit/Color");
            if (shader == null)
            {
                Debug.LogWarning("[PropHighlight] No outline material assigned and 'Unlit/Color' is unavailable; outline disabled.");
                return;
            }
            outlineMaterial = new Material(shader);
            outlineMaterial.color = outlineColor;
            ownsOutlineMaterial = true;
        }

        // Create outline object
        MeshFilter meshFilter = GetComponent<MeshFilter>();
        if (meshFilter != null && meshFilter.sharedMesh != null)
        {
            outlineObject = new GameObject("Outline");
            outlineObject.transform.SetParent(transform);
            outlineObject.transform.localPosition = Vector3.zero;
            outlineObject.transform.localRotation = Quaternion.identity;
            outlineObject.transform.localScale = Vector3.one * (1f + outlineWidth);

            MeshFilter outlineMeshFilter = outlineObject.AddComponent<MeshFilter>();
            outlineMeshFilter.sharedMesh = meshFilter.sharedMesh;

            MeshRenderer outlineRenderer = outlineObject.AddComponent<MeshRenderer>();
            outlineRenderer.material = outlineMaterial;
            outlineRenderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            outlineRenderer.receiveShadows = false;

            outlineObject.SetActive(false);
        }
    }

    private void Update()
    {
        UpdateHighlight();
        UpdateScalePulse();
    }

    /// <summary>
    /// Updates highlight effect interpolation.
    /// </summary>
    private void UpdateHighlight()
    {
        float targetIntensity = isHighlighted ? highlightIntensity : normalIntensity;
        currentIntensity = Mathf.Lerp(currentIntensity, targetIntensity, transitionSpeed * Time.deltaTime);

        // Apply emission
        if (highlightMode == HighlightMode.Emission || highlightMode == HighlightMode.Both)
        {
            ApplyEmission();
        }

        // Apply outline
        if (highlightMode == HighlightMode.Outline || highlightMode == HighlightMode.Both)
        {
            ApplyOutline();
        }
    }

    /// <summary>
    /// Applies emission-based highlight to materials.
    /// </summary>
    private void ApplyEmission()
    {
        if (highlightMaterials == null) return;

        // Swap materials only when the highlight starts or fully fades, not every frame
        bool showHighlight = currentIntensity > 0.01f;
        if (showHighlight && !materialsSwapped)
        {
            BeginHighlightMaterials();
        }
        else if (!showHighlight && materialsSwapped)
        {
            EndHighlightMaterials();
        }

        if (!showHighlight) return;

        for (int i = 0; i < renderers.Length; i++)
        {
            if (highlightMaterials[i] != null && highlightMaterials[i].HasProperty(emissionProperty))
            {
                highlightMaterials[i].SetColor(emissionProperty, originalEmission[i] + highlightColor * currentIntensity);
            }
        }
    }

    /// <summary>
    /// Applies outline visibility.
    /// </summary>
    private void ApplyOutline()
    {
        if (outlineObject != null)
        {
            bool shouldShow = currentIntensity > 0.1f;
            if (outlineObject.activeSelf != shouldShow)
            {
                outlineObject.SetActive(shouldShow);
            }

            // Pulse outline alpha
            if (shouldShow && outlineMaterial != null)
            {
                float alpha = 0.5f + Mathf.Sin(Time.time * pulseSpeed) * 0.3f;
                Color c = outlineColor;
                c.a = alpha * (currentIntensity / highlightIntensity);
                outlineMaterial.color = c;
            }
        }
    }

    /// <summary>
    /// Updates scale pulse effect.
    /// </summary>
    private void UpdateScalePulse()
    {
        if (!useScalePulse) return;

        if (isHighlighted)
        {
            float pulse = 1f + Mathf.Sin(Time.time * pulseSpeed) * pulseAmount;
            transform.localScale = originalScale * pulse;
        }
        else
        {
            transform.localScale = Vector3.Lerp(transform.localScale, originalScale, transitionSpeed * Time.deltaTime);
        }
    }

    /// <summary>
    /// Enables highlight effect.
    /// </summary>
    public void EnableHighlight()
    {
        isHighlighted = true;
    }

    /// <summary>
    /// Disables highlight effect.
    /// </summary>
    public void DisableHighlight()
    {
        isHighlighted = false;
    }

    /// <summary>
    /// Sets highlight state directly.
    /// </summary>
    public void SetHighlighted(bool highlighted)
    {
        isHighlighted = highlighted;
    }

    /// <summary>
    /// Gets current highlight state.
    /// </summary>
    public bool IsHighlighted() => isHighlighted;

    /// <summary>
    /// Whether this component drives the renderer's emission (Emission or Both mode).
    /// </summary>
    public bool DrivesEmission => highlightMode == HighlightMode.Emission || highlightMode == HighlightMode.Both;

    /// <summary>
    /// Sets highlight color dynamically.
    /// </summary>
    public void SetHighlightColor(Color color)
    {
        highlightColor = color;
        if (outlineMaterial != null)
        {
            outlineColor = color;
        }
    }

    private void OnDestroy()
    {
        // Put the original materials back before destroying the highlight copies
        if (materialsSwapped && renderers != null && originalMaterials != null)
        {
            EndHighlightMaterials();
        }

        // Cleanup created materials
        if (highlightMaterials != null)
        {
            foreach (Material mat in highlightMaterials)
            {
                if (mat != null)
                {
                    Destroy(mat);
                }
            }
        }

        if (ownsOutlineMaterial && outlineMaterial != null)
        {
            Destroy(outlineMaterial);
        }
    }
}
