// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M8 - Table Prop

using UnityEngine;

/// <summary>
/// Séance Table prop - summons a random spirit.
/// Central gathering point with candles, ambient whispers, and ritual feel.
/// </summary>
public class TableProp : MonoBehaviour, IInteractable
{
    [Header("Spirit Settings")]
    [SerializeField] private bool useRandomSpirit = true;
    [SerializeField] private string[] availableSpirits = { "Raven", "Narrator", "Usher" };
    [SerializeField] private int spookIncrement = 1;

    [Header("Candles")]
    [SerializeField] private Light[] candleLights;
    [SerializeField] private CandleFlicker[] candleFlickers;

    [Header("Visual Effects")]
    [SerializeField] private ParticleSystem smokeParticles;
    [SerializeField] private ParticleSystem sparkParticles;
    [SerializeField] private GameObject ritualCircle;

    [Header("Audio")]
    [SerializeField] private AudioSource ambientSource;
    [SerializeField] private AudioClip whisperLoopClip;
    [SerializeField] private AudioClip activateClip;
    [SerializeField] private AudioClip bellClip;

    [Header("Séance Settings")]
    [SerializeField] private float seanceWarmupTime = 2f;
    [SerializeField] private Color normalCandleColor = new Color(1f, 0.8f, 0.5f);
    [SerializeField] private Color activeCandleColor = new Color(0.5f, 0.3f, 1f);

    // State
    private bool isHighlighted = false;
    private bool isSeanceActive = false;
    private string lastSummonedSpirit = "";
    private int summonCount = 0;

    private void Start()
    {
        // Initialize candles
        if (candleLights != null)
        {
            foreach (Light candle in candleLights)
            {
                if (candle != null)
                {
                    candle.color = normalCandleColor;
                }
            }
        }

        // Hide ritual circle initially
        if (ritualCircle != null)
        {
            ritualCircle.SetActive(false);
        }

        // Start subtle whisper ambience
        if (ambientSource != null && whisperLoopClip != null)
        {
            ambientSource.clip = whisperLoopClip;
            ambientSource.loop = true;
            ambientSource.volume = 0.1f;
            ambientSource.Play();
        }
    }

    private void Update()
    {
        UpdateCandleEffects();
    }

    /// <summary>
    /// Updates candle visual effects.
    /// </summary>
    private void UpdateCandleEffects()
    {
        if (!isSeanceActive || candleLights == null) return;

        // Pulsing candle colors during séance
        float pulse = (Mathf.Sin(Time.time * 3f) + 1f) / 2f;
        Color currentColor = Color.Lerp(normalCandleColor, activeCandleColor, pulse);

        foreach (Light candle in candleLights)
        {
            if (candle != null)
            {
                candle.color = currentColor;
            }
        }
    }

    public void OnInteract()
    {
        if (isSeanceActive) return;

        Debug.Log("[TableProp] Séance initiated");
        StartCoroutine(SeanceSequence());
    }

    /// <summary>
    /// Full séance ritual sequence.
    /// </summary>
    private System.Collections.IEnumerator SeanceSequence()
    {
        isSeanceActive = true;

        // Select spirit
        string spiritKey = SelectSpirit();
        Debug.Log($"[TableProp] Summoning spirit: {spiritKey}");

        // Phase 1: Warmup
        yield return StartCoroutine(SeanceWarmup());

        // Phase 2: Activation
        yield return StartCoroutine(SeanceActivation(spiritKey));

        // Phase 3: Cooldown
        yield return StartCoroutine(SeanceCooldown());

        isSeanceActive = false;
    }

    /// <summary>
    /// Séance warmup phase - building tension.
    /// </summary>
    private System.Collections.IEnumerator SeanceWarmup()
    {
        // Show ritual circle
        if (ritualCircle != null)
        {
            ritualCircle.SetActive(true);
        }

        // Increase whisper volume
        if (ambientSource != null)
        {
            float elapsed = 0f;
            while (elapsed < seanceWarmupTime)
            {
                elapsed += Time.deltaTime;
                ambientSource.volume = Mathf.Lerp(0.1f, 0.5f, elapsed / seanceWarmupTime);
                yield return null;
            }
        }

        // Candles flicker intensely
        if (candleFlickers != null)
        {
            foreach (CandleFlicker flicker in candleFlickers)
            {
                if (flicker != null)
                {
                    flicker.SetBaseIntensity(2f);
                }
            }
        }

        // Start smoke
        if (smokeParticles != null)
        {
            smokeParticles.Play();
        }

        // Bell sound
        if (AudioManager.Instance != null && bellClip != null)
        {
            AudioManager.Instance.PlaySFX(bellClip);
        }
    }

    /// <summary>
    /// Séance activation - spirit arrives.
    /// </summary>
    private System.Collections.IEnumerator SeanceActivation(string spiritKey)
    {
        // Activation sound
        if (AudioManager.Instance != null && activateClip != null)
        {
            AudioManager.Instance.PlaySFX(activateClip);
        }

        // All candles flare then dim
        if (candleLights != null)
        {
            foreach (Light candle in candleLights)
            {
                if (candle != null)
                {
                    candle.intensity = 5f;
                }
            }
        }

        // Camera shake
        if (CameraShake.Instance != null)
        {
            CameraShake.Instance.Shake(0.25f, 0.5f);
        }

        // Spark burst
        if (sparkParticles != null)
        {
            sparkParticles.Emit(50);
        }

        yield return new WaitForSeconds(0.3f);

        // Dim candles dramatically
        if (candleLights != null)
        {
            foreach (Light candle in candleLights)
            {
                if (candle != null)
                {
                    candle.intensity = 0.3f;
                    candle.color = activeCandleColor;
                }
            }
        }

        // Brief darkness
        if (ScreenEffects.Instance != null)
        {
            ScreenEffects.Instance.Flash(new Color(0f, 0f, 0f, 0.5f), 0.3f);
        }

        yield return new WaitForSeconds(0.5f);

        // Summon spirit
        if (LLMManager.Instance != null)
        {
            LLMManager.Instance.SummonSpirit(spiritKey);
        }

        // Increment spook
        if (EventManager.Instance != null)
        {
            EventManager.Instance.IncrementSpook(spookIncrement);
        }

        // Show chat
        if (UIChat.Instance != null && !UIChat.Instance.IsVisible())
        {
            UIChat.Instance.Show();
        }

        summonCount++;
    }

    /// <summary>
    /// Séance cooldown - returning to normal.
    /// </summary>
    private System.Collections.IEnumerator SeanceCooldown()
    {
        yield return new WaitForSeconds(3f);

        // Restore candles
        float elapsed = 0f;
        float duration = 2f;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / duration;

            if (candleLights != null)
            {
                foreach (Light candle in candleLights)
                {
                    if (candle != null)
                    {
                        candle.intensity = Mathf.Lerp(0.3f, 1f, t);
                        candle.color = Color.Lerp(activeCandleColor, normalCandleColor, t);
                    }
                }
            }

            if (ambientSource != null)
            {
                ambientSource.volume = Mathf.Lerp(0.5f, 0.1f, t);
            }

            yield return null;
        }

        // Reset flickers
        if (candleFlickers != null)
        {
            foreach (CandleFlicker flicker in candleFlickers)
            {
                if (flicker != null)
                {
                    flicker.SetBaseIntensity(1f);
                }
            }
        }

        // Hide ritual circle
        if (ritualCircle != null)
        {
            ritualCircle.SetActive(false);
        }

        // Stop smoke
        if (smokeParticles != null)
        {
            smokeParticles.Stop();
        }
    }

    /// <summary>
    /// Selects which spirit to summon.
    /// </summary>
    private string SelectSpirit()
    {
        if (!useRandomSpirit || availableSpirits.Length == 0)
        {
            return "Raven";
        }

        // Avoid repeating same spirit
        string selected;
        int attempts = 0;
        do
        {
            selected = availableSpirits[Random.Range(0, availableSpirits.Length)];
            attempts++;
        }
        while (selected == lastSummonedSpirit && attempts < 5 && availableSpirits.Length > 1);

        lastSummonedSpirit = selected;
        return selected;
    }

    public void OnHighlightEnter()
    {
        isHighlighted = true;

        // Candles react
        if (candleLights != null)
        {
            foreach (Light candle in candleLights)
            {
                if (candle != null)
                {
                    candle.intensity = 1.5f;
                }
            }
        }

        // Increase whispers
        if (ambientSource != null)
        {
            ambientSource.volume = 0.25f;
        }
    }

    public void OnHighlightExit()
    {
        isHighlighted = false;

        if (!isSeanceActive)
        {
            if (candleLights != null)
            {
                foreach (Light candle in candleLights)
                {
                    if (candle != null)
                    {
                        candle.intensity = 1f;
                    }
                }
            }

            if (ambientSource != null)
            {
                ambientSource.volume = 0.1f;
            }
        }
    }
}
