// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M18-M24 - Finale Manager

using UnityEngine;
using System.Collections;

/// <summary>
/// Manages the finale sequence in the OtherDimension scene.
/// Coordinates epilogue narration, visual effects, and final player choice.
/// </summary>
public class FinaleManager : SceneSingletonBase<FinaleManager>
{

    [Header("References")]
    [SerializeField] private EpilogueNarrator epilogueNarrator;
    [SerializeField] private UIEpilogue uiEpilogue;
    [SerializeField] private DimensionalLight spiritCore;
    [SerializeField] private Transform playerSpawn;

    [Header("Timing")]
    [SerializeField] private float introDelay = 2f;
    [SerializeField] private float epilogueDuration = 30f;
    [SerializeField] private float fadeOutDuration = 3f;

    [Header("Audio")]
    [SerializeField] private AudioSource ambientSource;
    [SerializeField] private AudioClip finaleAmbience;
    [SerializeField] private AudioClip awakenSound;

    [Header("State")]
    private bool finaleStarted = false;
    private bool epilogueComplete = false;
    private bool playerAwakening = false;

    private void Start()
    {
        // Find references if not assigned
        if (epilogueNarrator == null)
        {
            epilogueNarrator = FindFirstObjectByType<EpilogueNarrator>();
        }
        if (uiEpilogue == null)
        {
            uiEpilogue = FindFirstObjectByType<UIEpilogue>();
        }
        if (spiritCore == null)
        {
            spiritCore = FindFirstObjectByType<DimensionalLight>();
        }

        // Setup audio
        if (ambientSource == null)
        {
            ambientSource = gameObject.AddComponent<AudioSource>();
        }
        ambientSource.loop = true;
        ambientSource.volume = 0f;

        // Spawn player
        SpawnPlayer();

        // Start finale sequence
        StartCoroutine(FinaleSequence());
    }

    private void Update()
    {
        // Check for awakening input
        if (epilogueComplete && !playerAwakening && Input.GetKeyDown(KeyCode.E))
        {
            StartCoroutine(AwakenSequence());
        }
    }

    /// <summary>
    /// Spawns the player at the designated spawn point.
    /// </summary>
    private void SpawnPlayer()
    {
        // Find spawn marker
        if (playerSpawn == null)
        {
            PlayerSpawnMarker marker = FindFirstObjectByType<PlayerSpawnMarker>();
            if (marker != null)
            {
                playerSpawn = marker.transform;
            }
        }

        // Find or create player
        GameObject player = GameObject.FindGameObjectWithTag("Player");
        if (player != null && playerSpawn != null)
        {
            CharacterController cc = player.GetComponent<CharacterController>();
            if (cc != null) cc.enabled = false;

            player.transform.position = playerSpawn.position;
            player.transform.rotation = playerSpawn.rotation;

            if (cc != null) cc.enabled = true;

            Debug.Log("[FinaleManager] Player spawned at finale position");
        }
    }

    /// <summary>
    /// Main finale sequence coroutine.
    /// </summary>
    private IEnumerator FinaleSequence()
    {
        finaleStarted = true;
        Debug.Log("[FinaleManager] Finale sequence started");

        // Phase 1: Fade in ambience
        yield return StartCoroutine(FadeInAmbience());

        // Phase 2: Wait for intro
        yield return new WaitForSeconds(introDelay);

        // Phase 3: Start epilogue narration
        if (epilogueNarrator != null)
        {
            epilogueNarrator.BeginEpilogue();
        }

        // Phase 4: Intensify effects over time
        yield return StartCoroutine(IntensifyEffects());

        // Phase 5: Mark epilogue complete
        epilogueComplete = true;

        // Phase 6: Show awakening prompt
        if (uiEpilogue != null)
        {
            uiEpilogue.ShowPrompt();
        }

        Debug.Log("[FinaleManager] Epilogue complete, awaiting player input");
    }

    /// <summary>
    /// Fades in the ambient audio.
    /// </summary>
    private IEnumerator FadeInAmbience()
    {
        if (finaleAmbience != null && ambientSource != null)
        {
            ambientSource.clip = finaleAmbience;
            ambientSource.Play();

            float elapsed = 0f;
            float duration = 3f;

            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                ambientSource.volume = Mathf.Lerp(0f, 0.5f, elapsed / duration);
                yield return null;
            }
        }
    }

    /// <summary>
    /// Gradually intensifies visual effects during epilogue.
    /// </summary>
    private IEnumerator IntensifyEffects()
    {
        float elapsed = 0f;

        while (elapsed < epilogueDuration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / epilogueDuration;

            // Pulse spirit core intensity
            if (spiritCore != null)
            {
                spiritCore.SetIntensityMultiplier(1f + t * 0.5f);
            }

            // Increase fog slightly
            RenderSettings.fogDensity = Mathf.Lerp(0.05f, 0.08f, t);

            yield return null;
        }
    }

    /// <summary>
    /// Handles the awakening sequence when player presses E.
    /// </summary>
    private IEnumerator AwakenSequence()
    {
        playerAwakening = true;
        Debug.Log("[FinaleManager] Player awakening...");

        // Play awakening sound
        if (AudioManager.Instance != null && awakenSound != null)
        {
            AudioManager.Instance.PlaySFX(awakenSound);
        }

        // Flash white
        if (ScreenEffects.Instance != null)
        {
            ScreenEffects.Instance.Flash(Color.white, 1f);
        }

        // Save final memory
        SaveFinalMemory();

        // Fade to white
        yield return StartCoroutine(FadeToWhite());

        // Display final message
        if (uiEpilogue != null)
        {
            uiEpilogue.ShowFinalMessage("You awaken... but the whispers linger.");
        }

        yield return new WaitForSeconds(3f);

        // End application or return to menu
        EndExperience();
    }

    /// <summary>
    /// Saves the final spirit memory.
    /// </summary>
    private void SaveFinalMemory()
    {
        // Save all spirit memories
        string[] spirits = SpiritMemory.GetAllSavedSpirits();
        foreach (string spirit in spirits)
        {
            SpiritMemory memory = SpiritMemory.Load(spirit);
            if (memory != null)
            {
                memory.AddExchange("[FINALE]", "The portal closes, but the spirits remember...");
                SpiritMemory.Save(memory);
            }
        }

        Debug.Log("[FinaleManager] Final memories saved");
    }

    /// <summary>
    /// Fades the screen to white.
    /// </summary>
    private IEnumerator FadeToWhite()
    {
        if (ScreenEffects.Instance != null)
        {
            ScreenEffects.Instance.FadeTo(Color.white, fadeOutDuration);
        }

        // Fade out audio
        float elapsed = 0f;
        float startVolume = ambientSource.volume;

        while (elapsed < fadeOutDuration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / fadeOutDuration;

            if (ambientSource != null)
            {
                ambientSource.volume = Mathf.Lerp(startVolume, 0f, t);
            }

            yield return null;
        }
    }

    /// <summary>
    /// Ends the experience (quit or return to menu).
    /// </summary>
    private void EndExperience()
    {
        Debug.Log("[FinaleManager] Experience complete");

#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
    }

    /// <summary>
    /// Checks if finale is in progress.
    /// </summary>
    public bool IsFinaleInProgress()
    {
        return finaleStarted && !playerAwakening;
    }

    /// <summary>
    /// Checks if epilogue narration is complete.
    /// </summary>
    public bool IsEpilogueComplete()
    {
        return epilogueComplete;
    }
}
