// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M1 - Game Systems

using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Central game state manager for Cursed Portal.
/// Handles initialization, scene transitions, and game flow.
/// </summary>
public class GameManager : MonoBehaviour
{
    public static GameManager Instance { get; private set; }

    [Header("Game State")]
    [SerializeField] private GameState currentState = GameState.Playing;

    [Header("Scene Names")]
    [SerializeField] private string mainSceneName = "CursedPortal";
    [SerializeField] private string finaleSceneName = "OtherDimension";

    [Header("Settings")]
    [SerializeField] private bool autoInitialize = true;

    // Events
    public event System.Action<GameState> OnGameStateChanged;
    public event System.Action OnGameInitialized;

    public enum GameState
    {
        Initializing,
        Playing,
        Paused,
        InChat,
        Transitioning,
        Epilogue,
        GameOver
    }

    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
            return;
        }
    }

    private void Start()
    {
        if (autoInitialize)
        {
            Initialize();
        }
    }

    /// <summary>
    /// Initializes the game systems.
    /// </summary>
    public void Initialize()
    {
        SetState(GameState.Initializing);
        Debug.Log("[GameManager] Initializing game...");

        // Verify all managers exist
        VerifyManagers();

        // Subscribe to events
        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnDimensionBreach += OnDimensionBreach;
        }

        SetState(GameState.Playing);
        OnGameInitialized?.Invoke();
        Debug.Log("[GameManager] Game initialized");
    }

    /// <summary>
    /// Verifies all required managers are present.
    /// </summary>
    private void VerifyManagers()
    {
        if (EventManager.Instance == null)
            Debug.LogWarning("[GameManager] EventManager not found!");
        if (AudioManager.Instance == null)
            Debug.LogWarning("[GameManager] AudioManager not found!");
        if (LLMManager.Instance == null)
            Debug.LogWarning("[GameManager] LLMManager not found!");
    }

    /// <summary>
    /// Sets the current game state.
    /// </summary>
    public void SetState(GameState newState)
    {
        if (currentState == newState) return;

        GameState previousState = currentState;
        currentState = newState;

        Debug.Log($"[GameManager] State: {previousState} -> {newState}");
        OnGameStateChanged?.Invoke(newState);

        // Handle state-specific logic
        switch (newState)
        {
            case GameState.Paused:
                Time.timeScale = 0f;
                CursorManager.Instance?.UnlockCursor();
                break;
            case GameState.Playing:
                Time.timeScale = 1f;
                CursorManager.Instance?.LockCursor();
                break;
            case GameState.InChat:
                CursorManager.Instance?.UnlockCursor();
                break;
        }
    }

    /// <summary>
    /// Gets the current game state.
    /// </summary>
    public GameState GetState() => currentState;

    /// <summary>
    /// Pauses the game.
    /// </summary>
    public void Pause()
    {
        if (currentState == GameState.Playing)
        {
            SetState(GameState.Paused);
        }
    }

    /// <summary>
    /// Resumes the game.
    /// </summary>
    public void Resume()
    {
        if (currentState == GameState.Paused)
        {
            SetState(GameState.Playing);
        }
    }

    /// <summary>
    /// Called when dimension breach occurs.
    /// </summary>
    private void OnDimensionBreach()
    {
        SetState(GameState.Transitioning);
    }

    /// <summary>
    /// Restarts the game.
    /// </summary>
    public void RestartGame()
    {
        Time.timeScale = 1f;
        EventManager.Instance?.ResetSpook();
        SceneManager.LoadScene(mainSceneName);
        SetState(GameState.Playing);
    }

    /// <summary>
    /// Quits the game.
    /// </summary>
    public void QuitGame()
    {
        Debug.Log("[GameManager] Quitting game...");
#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
    }

    private void OnDestroy()
    {
        if (EventManager.Instance != null)
        {
            EventManager.Instance.OnDimensionBreach -= OnDimensionBreach;
        }
    }
}
