// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M2

/// <summary>
/// Interface for all interactable objects in the Cursed Portal.
/// Implement this on any prop that the player can interact with.
/// </summary>
public interface IInteractable
{
    /// <summary>
    /// Called when the player presses the interact key (E) while targeting this object.
    /// </summary>
    void OnInteract();

    /// <summary>
    /// Called when the player's raycast begins targeting this object.
    /// Use for visual feedback like outlines or glow effects.
    /// </summary>
    void OnHighlightEnter();

    /// <summary>
    /// Called when the player's raycast stops targeting this object.
    /// Use to reset visual feedback.
    /// </summary>
    void OnHighlightExit();
}
