// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M2

using UnityEngine;

/// <summary>
/// Handles player interaction with objects in the scene.
/// Raycasts from camera center and detects IInteractable objects.
/// </summary>
public class InteractionManager : SceneSingletonBase<InteractionManager>
{
    [Header("Interaction Settings")]
    [SerializeField] private float interactionRange = 3f;
    [SerializeField] private LayerMask interactableMask = ~0; // Default to all layers
    [SerializeField] private KeyCode interactKey = KeyCode.E;

    [Header("UI Feedback")]
    [SerializeField] private GameObject interactPromptUI; // Optional: "Press E to interact" prompt

    private Camera mainCamera;
    private IInteractable currentTarget;
    private IInteractable previousTarget;

    private void Start()
    {
        mainCamera = Camera.main;
        if (mainCamera == null)
        {
            Debug.LogError("[InteractionManager] No main camera found! Ensure camera is tagged 'MainCamera'.");
        }

        // Hide interact prompt initially
        if (interactPromptUI != null)
        {
            interactPromptUI.SetActive(false);
        }
    }

    private void Update()
    {
        if (mainCamera == null) return;

        PerformRaycast();
        HandleHighlighting();
        HandleInput();
    }

    /// <summary>
    /// Performs a raycast from the center of the screen to detect interactable objects.
    /// </summary>
    private void PerformRaycast()
    {
        Ray ray = mainCamera.ScreenPointToRay(new Vector3(Screen.width / 2f, Screen.height / 2f, 0f));

        // Ignore trigger volumes (e.g. SpookTriggerZone) so they don't hide the props inside them
        if (Physics.Raycast(ray, out RaycastHit hit, interactionRange, interactableMask, QueryTriggerInteraction.Ignore))
        {
            // Try to get IInteractable from hit object or its parents (handles child colliders)
            IInteractable interactable = hit.collider.GetComponentInParent<IInteractable>();
            currentTarget = interactable;
        }
        else
        {
            currentTarget = null;
        }
    }

    /// <summary>
    /// Handles highlight enter/exit callbacks when target changes.
    /// </summary>
    private void HandleHighlighting()
    {
        // Target changed
        if (currentTarget != previousTarget)
        {
            // Exit previous target
            if (previousTarget != null)
            {
                previousTarget.OnHighlightExit();
            }

            // Enter new target
            if (currentTarget != null)
            {
                currentTarget.OnHighlightEnter();
            }

            // Update UI prompt
            if (interactPromptUI != null)
            {
                interactPromptUI.SetActive(currentTarget != null);
            }

            previousTarget = currentTarget;
        }
    }

    /// <summary>
    /// Handles player input for interaction.
    /// </summary>
    private void HandleInput()
    {
        // Typing in the chat (or a running portal transition) must not trigger the prop behind it
        if (UIChat.Instance != null && UIChat.Instance.IsVisible()) return;
        if (PortalSequence.Instance != null && PortalSequence.Instance.IsTransitioning()) return;

        if (currentTarget != null && Input.GetKeyDown(interactKey))
        {
            currentTarget.OnInteract();
        }
    }

    /// <summary>
    /// Gets the currently targeted interactable object.
    /// </summary>
    public IInteractable GetCurrentTarget()
    {
        return currentTarget;
    }

    /// <summary>
    /// Checks if the player is currently targeting an interactable.
    /// </summary>
    public bool HasTarget()
    {
        return currentTarget != null;
    }
}
