// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M19

using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using System.Collections;

/// <summary>
/// Handles the portal transition sequence when spook level reaches maximum.
/// Manages the breach effect and scene transition to OtherDimension.
/// </summary>
public class PortalSequence : SingletonBase<PortalSequence>
{

    [Header("Transition Settings")]
    [SerializeField] private string targetSceneName = "OtherDimension";
    [SerializeField] private float transitionDuration = 6f;
    [SerializeField] private float preFadeDelay = 1f;

    [Header("UI References")]
    [SerializeField] private CanvasGroup fadeCanvasGroup;
    [SerializeField] private Image fadeImage;
    [SerializeField] private GameObject breachOverlay; // "DIMENSION BREACH" text

    [Header("Audio")]
    [SerializeField] private AudioClip breachSFX;
    [SerializeField] private AudioClip transitionAmbience;

    [Header("Visual Settings")]
    [SerializeField] private Color fadeStartColor = Color.clear;
    [SerializeField] private Color fadeEndColor = Color.black;
    [SerializeField] private float maxFogDensity = 0.6f;

    // State
    private bool isTransitioning = false;

    private void Start()
    {
        // Initialize fade canvas
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.alpha = 0f;
            fadeCanvasGroup.blocksRaycasts = false;
        }

        if (breachOverlay != null)
        {
            breachOverlay.SetActive(false);
        }
    }

    /// <summary>
    /// Starts the portal breach transition sequence.
    /// </summary>
    public void StartTransition()
    {
        if (isTransitioning)
        {
            Debug.LogWarning("[PortalSequence] Transition already in progress!");
            return;
        }

        if (!Application.CanStreamedLevelBeLoaded(targetSceneName))
        {
            Debug.LogError($"[PortalSequence] Scene '{targetSceneName}' is not in Build Settings. " +
                           "Run CursedPortal > Create OtherDimension Scene (it saves and registers the scene).");
        }

        Debug.Log("[PortalSequence] DIMENSION BREACH! Starting transition...");

        // The conversation ends here: stop any reply still streaming in and close the chat
        if (LLMStreamManager.Instance != null)
        {
            LLMStreamManager.Instance.CancelStream();
        }
        if (UIChat.Instance != null)
        {
            UIChat.Instance.Hide();
        }

        StartCoroutine(BreachSequence());
    }

    /// <summary>
    /// The main breach sequence coroutine.
    /// </summary>
    private IEnumerator BreachSequence()
    {
        isTransitioning = true;

        // Without a scene-wired fade canvas, build one now (it survives the load as our child)
        if (fadeCanvasGroup == null)
        {
            EnsureFadeCanvas(0f);
        }

        // Phase 1: Pre-breach effects
        yield return StartCoroutine(PreBreachPhase());

        // Phase 2: Main breach
        yield return StartCoroutine(BreachPhase());

        // Phase 3: Transition
        yield return StartCoroutine(TransitionPhase());
    }

    /// <summary>
    /// Pre-breach phase: Initial shock and visual warning.
    /// </summary>
    private IEnumerator PreBreachPhase()
    {
        Debug.Log("[PortalSequence] Pre-breach phase...");

        // Play breach sound
        if (AudioManager.Instance != null && breachSFX != null)
        {
            AudioManager.Instance.PlaySFX(breachSFX);
        }

        // Camera shake
        // TODO: Integrate with Cinemachine Impulse if available

        // Show breach overlay
        if (breachOverlay != null)
        {
            breachOverlay.SetActive(true);
        }

        // Trigger portal VFX
        if (VFXManager.Instance != null)
        {
            VFXManager.Instance.TriggerPortal();
        }

        // Maximum post-processing
        if (PostFXController.Instance != null)
        {
            PostFXController.Instance.SetLevel(5);
            PostFXController.Instance.TriggerGlitch(1f);
        }

        yield return new WaitForSeconds(preFadeDelay);
    }

    /// <summary>
    /// Main breach phase: Fade and fog increase.
    /// </summary>
    private IEnumerator BreachPhase()
    {
        Debug.Log("[PortalSequence] Breach phase...");

        float elapsed = 0f;
        float startFogDensity = RenderSettings.fogDensity;

        // Enable fade canvas
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.blocksRaycasts = true;
        }

        // Fade out the parlor's whispers and ambience so they don't carry into the finale
        if (AudioManager.Instance != null)
        {
            AudioManager.Instance.FadeOutAll(transitionDuration * 0.5f);

            if (transitionAmbience != null)
            {
                AudioManager.Instance.PlaySFX(transitionAmbience);
            }
        }

        while (elapsed < transitionDuration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / transitionDuration;

            // Ease in-out curve
            float smoothT = t * t * (3f - 2f * t);

            // Fade alpha
            if (fadeCanvasGroup != null)
            {
                fadeCanvasGroup.alpha = smoothT;
            }

            // Fade color (optional red tint before black)
            if (fadeImage != null)
            {
                Color midColor = new Color(0.3f, 0f, 0f); // Dark red
                if (t < 0.5f)
                {
                    fadeImage.color = Color.Lerp(fadeStartColor, midColor, t * 2f);
                }
                else
                {
                    fadeImage.color = Color.Lerp(midColor, fadeEndColor, (t - 0.5f) * 2f);
                }
            }

            // Increase fog density
            RenderSettings.fogDensity = Mathf.Lerp(startFogDensity, maxFogDensity, smoothT);

            yield return null;
        }

        // Ensure final values
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.alpha = 1f;
        }
        RenderSettings.fogDensity = maxFogDensity;
    }

    /// <summary>
    /// Transition phase: Load new scene.
    /// </summary>
    private IEnumerator TransitionPhase()
    {
        Debug.Log("[PortalSequence] Loading OtherDimension...");

        // Hide breach overlay before scene change
        if (breachOverlay != null)
        {
            breachOverlay.SetActive(false);
        }

        // Load the new scene
        AsyncOperation loadOperation = SceneManager.LoadSceneAsync(targetSceneName);

        if (loadOperation == null)
        {
            Debug.LogError($"[PortalSequence] Failed to load scene: {targetSceneName}");
            yield return StartCoroutine(RecoverFromFailedLoad());
            yield break;
        }

        // Wait for scene to load
        while (!loadOperation.isDone)
        {
            yield return null;
        }

        Debug.Log("[PortalSequence] OtherDimension loaded!");

        // After scene load, old scene-local UI references are destroyed.
        // Rebuild a temporary fade canvas if needed.
        if (fadeCanvasGroup == null)
        {
            EnsureFadeCanvas(1f);
        }

        // Brief pause in darkness
        yield return new WaitForSeconds(0.5f);

        // Fade in new scene
        yield return StartCoroutine(FadeIn());

        isTransitioning = false;
    }

    /// <summary>
    /// Returns to the parlor when the target scene can't be loaded, so the game isn't stuck in black.
    /// </summary>
    private IEnumerator RecoverFromFailedLoad()
    {
        if (breachOverlay != null)
        {
            breachOverlay.SetActive(false);
        }

        yield return StartCoroutine(FadeIn());

        isTransitioning = false;

        // Drop back below the breach so it can trigger again once the scene is fixed
        if (EventManager.Instance != null)
        {
            EventManager.Instance.SetSpookLevel(4);
        }
    }

    /// <summary>
    /// Creates a fade canvas when none is wired in the scene, as a child of this persistent object.
    /// </summary>
    /// <param name="startAlpha">Initial opacity (0 before the breach, 1 when created after the load)</param>
    private void EnsureFadeCanvas(float startAlpha)
    {
        GameObject canvasObj = new GameObject("PortalFadeCanvas");
        canvasObj.transform.SetParent(transform); // child of DontDestroyOnLoad object

        Canvas canvas = canvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.ScreenSpaceOverlay;
        canvas.sortingOrder = 999;

        fadeCanvasGroup = canvasObj.AddComponent<CanvasGroup>();
        fadeCanvasGroup.alpha = startAlpha;
        fadeCanvasGroup.blocksRaycasts = startAlpha > 0f;

        GameObject imageObj = new GameObject("FadeImage");
        imageObj.transform.SetParent(canvasObj.transform, false);

        RectTransform rt = imageObj.AddComponent<RectTransform>();
        rt.anchorMin = Vector2.zero;
        rt.anchorMax = Vector2.one;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;

        fadeImage = imageObj.AddComponent<Image>();
        fadeImage.color = startAlpha > 0f ? fadeEndColor : fadeStartColor;

        Debug.Log("[PortalSequence] Created fallback fade canvas for scene transition");
    }

    /// <summary>
    /// Fades in from black after scene transition.
    /// </summary>
    private IEnumerator FadeIn()
    {
        float duration = 2f;
        float elapsed = 0f;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / duration;

            if (fadeCanvasGroup != null)
            {
                fadeCanvasGroup.alpha = 1f - t;
            }

            // Reduce fog in new scene
            RenderSettings.fogDensity = Mathf.Lerp(maxFogDensity, 0.05f, t);

            yield return null;
        }

        // Cleanup
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.alpha = 0f;
            fadeCanvasGroup.blocksRaycasts = false;
        }
    }

    /// <summary>
    /// Checks if transition is in progress.
    /// </summary>
    public bool IsTransitioning()
    {
        return isTransitioning;
    }

    /// <summary>
    /// Force skip to scene (debug only).
    /// </summary>
    public void SkipToScene()
    {
        if (!isTransitioning)
        {
            Debug.Log("[PortalSequence] Debug skip to OtherDimension");
            SceneManager.LoadScene(targetSceneName);
        }
    }
}
