// Auto-generated by CursedPortal AI Spec v1.0
// Source: Module M19

using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using System.Collections;

/// <summary>
/// Handles the portal transition sequence when spook level reaches maximum.
/// Manages the breach effect and scene transition to OtherDimension.
/// </summary>
public class PortalSequence : SingletonBase<PortalSequence>
{

    [Header("Transition Settings")]
    [SerializeField] private string targetSceneName = "OtherDimension";
    [SerializeField] private float transitionDuration = 6f;
    [SerializeField] private float preFadeDelay = 1f;

    [Header("UI References")]
    [SerializeField] private CanvasGroup fadeCanvasGroup;
    [SerializeField] private Image fadeImage;
    [SerializeField] private GameObject breachOverlay; // "DIMENSION BREACH" text

    [Header("Audio")]
    [SerializeField] private AudioClip breachSFX;
    [SerializeField] private AudioClip transitionAmbience;

    [Header("Visual Settings")]
    [SerializeField] private Color fadeStartColor = Color.clear;
    [SerializeField] private Color fadeEndColor = Color.black;
    [SerializeField] private float maxFogDensity = 0.6f;

    // State
    private bool isTransitioning = false;

    private void Start()
    {
        // Initialize fade canvas
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.alpha = 0f;
            fadeCanvasGroup.blocksRaycasts = false;
        }

        if (breachOverlay != null)
        {
            breachOverlay.SetActive(false);
        }
    }

    /// <summary>
    /// Starts the portal breach transition sequence.
    /// </summary>
    public void StartTransition()
    {
        if (isTransitioning)
        {
            Debug.LogWarning("[PortalSequence] Transition already in progress!");
            return;
        }

        Debug.Log("[PortalSequence] DIMENSION BREACH! Starting transition...");
        StartCoroutine(BreachSequence());
    }

    /// <summary>
    /// The main breach sequence coroutine.
    /// </summary>
    private IEnumerator BreachSequence()
    {
        isTransitioning = true;

        // Phase 1: Pre-breach effects
        yield return StartCoroutine(PreBreachPhase());

        // Phase 2: Main breach
        yield return StartCoroutine(BreachPhase());

        // Phase 3: Transition
        yield return StartCoroutine(TransitionPhase());
    }

    /// <summary>
    /// Pre-breach phase: Initial shock and visual warning.
    /// </summary>
    private IEnumerator PreBreachPhase()
    {
        Debug.Log("[PortalSequence] Pre-breach phase...");

        // Play breach sound
        if (AudioManager.Instance != null && breachSFX != null)
        {
            AudioManager.Instance.PlaySFX(breachSFX);
        }

        // Camera shake
        // TODO: Integrate with Cinemachine Impulse if available

        // Show breach overlay
        if (breachOverlay != null)
        {
            breachOverlay.SetActive(true);
        }

        // Trigger portal VFX
        if (VFXManager.Instance != null)
        {
            VFXManager.Instance.TriggerPortal();
        }

        // Maximum post-processing
        if (PostFXController.Instance != null)
        {
            PostFXController.Instance.SetLevel(5);
            PostFXController.Instance.TriggerGlitch(1f);
        }

        yield return new WaitForSeconds(preFadeDelay);
    }

    /// <summary>
    /// Main breach phase: Fade and fog increase.
    /// </summary>
    private IEnumerator BreachPhase()
    {
        Debug.Log("[PortalSequence] Breach phase...");

        float elapsed = 0f;
        float startFogDensity = RenderSettings.fogDensity;

        // Enable fade canvas
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.blocksRaycasts = true;
        }

        // Start transition ambience
        if (AudioManager.Instance != null && transitionAmbience != null)
        {
            // Fade out current audio
            AudioManager.Instance.FadeOutAll(transitionDuration * 0.5f);
        }

        while (elapsed < transitionDuration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / transitionDuration;

            // Ease in-out curve
            float smoothT = t * t * (3f - 2f * t);

            // Fade alpha
            if (fadeCanvasGroup != null)
            {
                fadeCanvasGroup.alpha = smoothT;
            }

            // Fade color (optional red tint before black)
            if (fadeImage != null)
            {
                Color midColor = new Color(0.3f, 0f, 0f); // Dark red
                if (t < 0.5f)
                {
                    fadeImage.color = Color.Lerp(fadeStartColor, midColor, t * 2f);
                }
                else
                {
                    fadeImage.color = Color.Lerp(midColor, fadeEndColor, (t - 0.5f) * 2f);
                }
            }

            // Increase fog density
            RenderSettings.fogDensity = Mathf.Lerp(startFogDensity, maxFogDensity, smoothT);

            yield return null;
        }

        // Ensure final values
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.alpha = 1f;
        }
        RenderSettings.fogDensity = maxFogDensity;
    }

    /// <summary>
    /// Transition phase: Load new scene.
    /// </summary>
    private IEnumerator TransitionPhase()
    {
        Debug.Log("[PortalSequence] Loading OtherDimension...");

        // Hide breach overlay before scene change
        if (breachOverlay != null)
        {
            breachOverlay.SetActive(false);
        }

        // Load the new scene
        AsyncOperation loadOperation = SceneManager.LoadSceneAsync(targetSceneName);

        if (loadOperation == null)
        {
            Debug.LogError($"[PortalSequence] Failed to load scene: {targetSceneName}");
            isTransitioning = false;
            yield break;
        }

        // Wait for scene to load
        while (!loadOperation.isDone)
        {
            yield return null;
        }

        Debug.Log("[PortalSequence] OtherDimension loaded!");

        // Brief pause in darkness
        yield return new WaitForSeconds(0.5f);

        // Fade in new scene
        yield return StartCoroutine(FadeIn());

        isTransitioning = false;
    }

    /// <summary>
    /// Fades in from black after scene transition.
    /// </summary>
    private IEnumerator FadeIn()
    {
        float duration = 2f;
        float elapsed = 0f;

        while (elapsed < duration)
        {
            elapsed += Time.deltaTime;
            float t = elapsed / duration;

            if (fadeCanvasGroup != null)
            {
                fadeCanvasGroup.alpha = 1f - t;
            }

            // Reduce fog in new scene
            RenderSettings.fogDensity = Mathf.Lerp(maxFogDensity, 0.05f, t);

            yield return null;
        }

        // Cleanup
        if (fadeCanvasGroup != null)
        {
            fadeCanvasGroup.alpha = 0f;
            fadeCanvasGroup.blocksRaycasts = false;
        }
    }

    /// <summary>
    /// Checks if transition is in progress.
    /// </summary>
    public bool IsTransitioning()
    {
        return isTransitioning;
    }

    /// <summary>
    /// Force skip to scene (debug only).
    /// </summary>
    public void SkipToScene()
    {
        if (!isTransitioning)
        {
            Debug.Log("[PortalSequence] Debug skip to OtherDimension");
            SceneManager.LoadScene(targetSceneName);
        }
    }
}
